### ISSUE TITLE
Error in javascript adapter after update to 5.6.0

### ISSUE THREAD

**Issue by itProfi** [ioBroker/ioBroker.javascript#1007]
````
<html>
<body>
<!--StartFragment-->

host.iobroker-x64 | 2022-04-25 09:07:06.845 | error | instance system.adapter.javascript.2 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker-x64 | 2022-04-25 09:07:06.845 | error | Caught by controller[0]: at internal/main/run_main_module.js:17:47
host.iobroker-x64 | 2022-04-25 09:07:06.845 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
host.iobroker-x64 | 2022-04-25 09:07:06.845 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.iobroker-x64 | 2022-04-25 09:07:06.845 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:863:32)
host.iobroker-x64 | 2022-04-25 09:07:06.845 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
host.iobroker-x64 | 2022-04-25 09:07:06.844 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:999:30)
host.iobroker-x64 | 2022-04-25 09:07:06.844 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/main.js:97:38)
host.iobroker-x64 | 2022-04-25 09:07:06.844 | error | Caught by controller[0]: TypeError: Cannot read property 'split' of undefined
host.iobroker-x64 | 2022-04-25 09:07:06.844 | error | Caught by controller[0]: ^
host.iobroker-x64 | 2022-04-25 09:07:06.844 | error | Caught by controller[0]: const adapterName = packageJson.name.split('.').pop();
host.iobroker-x64 | 2022-04-25 09:07:06.844 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.javascript/main.js:97

<!--EndFragment-->
</body>
</html>
````
Same bug for another 3 instance of javascript

**Comment by Apollon77** [comment]
Please reinstall the adapter ... it seems your package.json is broken?

**Comment by Apollon77** [comment]
Additionally simply check /opt/iobroker/node_modules/iobroker.javascript/package.json and show the content ... it seems that the "name" proporty is missing on your system whcih normally can not be the case
