### ISSUE TITLE
[dev] How to setup adapter for development?

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.javascript#1052]
When following the documentation

https://github.com/ioBroker/ioBroker.javascript/blob/63570e2e66be174a49fa27fc1b60589fca17abe6/README.md?plain=1#L41-L44

```bash
git clone git@github.com:klein0r/ioBroker.javascript.git
cd ioBroker.javascript/
npm i
cd src/
npm i --legacy-peer-deps
cd ..
npm run build
```

Output:

```
> iobroker.javascript@5.8.2 build
> node node_modules/gulp/bin/gulp.js

[09:25:19] Using gulpfile ~/ioBroker.javascript/gulpfile.js
[09:25:19] Starting 'default'...
[09:25:19] Starting '6-patch-dep'...
[09:25:19] Starting '5-copy-dep'...
[09:25:19] Starting '3-build-dep'...
[09:25:19] Starting '2-npm'...
[09:25:19] Finished '2-npm' after 1.82 ms
[09:25:19] Starting '3-build'...
/home/mkleine/ioBroker.javascript/src/
Creating an optimized production build...

Compiled successfully.


File sizes after gzip:


  1.2 MB     build/static/js/12.e1771436.chunk.js

  531.62 kB  build/static/js/780.dcd96f5b.chunk.js

  203.89 kB  build/static/js/178.5c952989.chunk.js

  141.12 kB  build/static/js/62.465895ef.chunk.js

  122.39 kB  build/static/js/262.6a113200.chunk.js

  111.07 kB  build/static/js/257.32438e48.chunk.js

  43.49 kB   build/static/js/961.21586481.chunk.js

  42.6 kB    build/static/js/340.4f7382ee.chunk.js

  13.67 kB   build/static/js/230.f161f687.chunk.js

  10.23 kB   build/static/js/347.a1166539.chunk.js

  5.07 kB    build/static/js/270.edecf48a.chunk.js

  5.05 kB    build/static/css/62.5f92da38.chunk.css

  4.63 kB    build/static/js/main.9b0d4c85.js

  3.88 kB    build/static/js/821.947f04d2.chunk.js

  2.76 kB    build/static/js/526.b7e29abd.chunk.js

  1.6 kB     build/static/js/815.ab923bde.chunk.js

  1.6 kB     build/static/js/90.728d6560.chunk.js

  1.42 kB    build/static/js/449.7febd937.chunk.js

  586 B      build/static/js/652.30453175.chunk.js

  582 B      build/static/js/13.6f214f89.chunk.js

The bundle size is significantly larger than recommended.
Consider reducing it with code splitting: https://goo.gl/9VhYWB
You can also analyze the project dependencies: https://goo.gl/LeUzfb

The project was built assuming it is hosted at auto.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment


child process exited with code 0
[09:26:47] Finished '3-build' after 1.47 min
[09:26:47] Finished '3-build-dep' after 1.47 min
[09:26:47] Starting '5-copy'...
[09:26:47] Finished '5-copy' after 120 ms
[09:26:47] Finished '5-copy-dep' after 1.47 min
[09:26:47] Starting '6-patch'...
[09:26:48] The following tasks did not complete: default, 6-patch-dep, 6-patch
[09:26:48] Did you forget to signal async completion?
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: /home/mkleine/ioBroker.javascript/src/dist/index.html (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/mkleine/ioBroker.javascript/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (node:events:642:26)
    at Glob.emit (node:events:527:28)
    at Glob.emit (node:domain:475:12)
    at Glob._finish (/home/mkleine/ioBroker.javascript/node_modules/glob/glob.js:194:8)
    at done (/home/mkleine/ioBroker.javascript/node_modules/glob/glob.js:179:14)
    at Glob._processSimple2 (/home/mkleine/ioBroker.javascript/node_modules/glob/glob.js:685:12)
    at /home/mkleine/ioBroker.javascript/node_modules/glob/glob.js:673:10
    at Glob._stat2 (/home/mkleine/ioBroker.javascript/node_modules/glob/glob.js:769:12)
    at lstatcb_ (/home/mkleine/ioBroker.javascript/node_modules/glob/glob.js:761:12)
Emitted 'error' event on Domain instance at:
    at DestroyableTransform.emit (node:domain:525:12)
    at Pumpify.emit (node:events:527:28)
    at Pumpify.emit (node:domain:475:12)
    at Pumpify.Duplexify._destroy (/home/mkleine/ioBroker.javascript/node_modules/duplexify/index.js:191:15)
    at /home/mkleine/ioBroker.javascript/node_modules/duplexify/index.js:182:10
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  domainEmitter: DestroyableTransform {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: Transform {
        _readableState: ReadableState {
          objectMode: true,
          highWaterMark: 16,
          buffer: BufferList { head: null, tail: null, length: 0 },
          length: 0,
          pipes: [ [Transform] ],
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          constructed: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          errorEmitted: false,
          emitClose: true,
          autoDestroy: true,
          destroyed: false,
          errored: null,
          closed: false,
          closeEmitted: false,
          defaultEncoding: 'utf8',
          awaitDrainWriters: null,
          multiAwaitDrain: false,
          readingMore: false,
          dataEmitted: false,
          decoder: null,
          encoding: null,
          [Symbol(kPaused)]: false
        },
        _events: [Object: null prototype] {
          prefinish: [Function: prefinish],
          unpipe: [Function: onunpipe],
          drain: [Function (anonymous)],
          error: [Function: onerror],
          close: [Function: bound onceWrapper] {
            listener: [Function: onclose]
          },
          finish: [Function: bound onceWrapper] {
            listener: [Function: onfinish]
          },
          end: [Function: bound onceWrapper] { listener: [Function: onend] },
          data: [Function: ondata]
        },
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: WritableState {
          objectMode: true,
          highWaterMark: 16,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: false,
          decodeStrings: true,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: true,
          bufferProcessing: false,
          onwrite: [Function: bound onwrite],
          writecb: null,
          writelen: 0,
          afterWriteTickInfo: null,
          buffered: [],
          bufferedIndex: 0,
          allBuffers: true,
          allNoop: true,
          pendingcb: 0,
          constructed: true,
          prefinished: false,
          errorEmitted: false,
          emitClose: true,
          autoDestroy: true,
          errored: null,
          closed: false,
          closeEmitted: false,
          [Symbol(kOnFinished)]: []
        },
        allowHalfOpen: true,
        _transform: [Function: transform],
        [Symbol(kCapture)]: false,
        [Symbol(kCallback)]: null
      },
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [
        [Function: bound onceWrapper] { listener: [Function: onend] },
        [Function: bound onceWrapper] { listener: [Function: onend] }
      ],
      prefinish: [Function: prefinish],
      pipe: [Function: bound onceWrapper] { listener: [Function: onPipe] },
      data: [Function: ondata]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: CorkedRequest {
        next: null,
        entry: null,
        finish: [Function (anonymous)]
      }
    },
    writable: false,
    allowHalfOpen: true,
    _transformState: {
      afterTransform: [Function: bound afterTransform],
      needTransform: true,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: null
    },
    _destroyed: false,
    _transform: [Function: forward],
    _flush: [Function: flush],
    [Symbol(kCapture)]: false
  },
  domainThrown: false
}
```

**Comment by klein0r** [comment]
When running ``npm run start`` in the src directory, it get a lot of errors like this

```
ERROR in ./src/App.jsx 1:40-126
Module not found: Error: You attempted to import /home/mkleine/ioBroker.javascript/src/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
```

**Comment by klein0r** [comment]
Is the gulpfile still up to date? It uses ``src/dist``, but everything is build to ``src/build`` !?
When updating the gulpfile (replace /dist with /build) everything works like expected. 😕

**Comment by klein0r** [comment]
Build was successful with latest version 👍 Fixed in dc6148519995e49ed67d9885344594b5f0d9ba57

```
[09:27:08] Finished '3-build' after 2.6 min
[09:27:08] Finished '3-build-dep' after 2.6 min
[09:27:08] Starting '5-copy'...
[09:27:09] Finished '5-copy' after 723 ms
[09:27:09] Finished '5-copy-dep' after 2.62 min
[09:27:09] Starting '6-patch'...
[09:27:09] Finished '6-patch' after 541 ms
[09:27:09] Finished '6-patch-dep' after 2.63 min
[09:27:09] Finished 'default' after 2.63 min
```
