### ISSUE TITLE
Problems with node_modules

### ISSUE THREAD

**Issue by duczz** [ioBroker/ioBroker.javascript#1070]
someone can help me in this case?
My Javascript Adapter won't start, and nothing works anymore :(

nodejs = v16.15.1
node = v16.15.1
npm = 8.11.0

`<html>
<body>

host.ioBroker | 2022-07-12 20:37:56.386 | error | instance system.adapter.javascript.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at node:internal/main/run_main_module:17:47
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/main.js:58:23)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/lib/request.js:5:18)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/index.js:143:19)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.386 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:11:21)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/node_modules/http-signature/lib/index.js:3:14)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/node_modules/http-signature/lib/parser.js:5:13)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/node_modules/http-signature/lib/utils.js:4:13)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/sshpk/lib/index.js:3:11)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/sshpk/lib/key.js:8:19)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.385 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/sshpk/lib/fingerprint.js:11:18)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/sshpk/lib/private-key.js:10:17)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/sshpk/lib/signature.js:10:13)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1105:14)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/sshpk/lib/utils.js:32:10)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1069:27)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at wrapSafe (node:internal/modules/cjs/loader:1033:15)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: at Object.compileFunction (node:vm:352:18)
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: SyntaxError: Unexpected end of input
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]:
host.ioBroker | 2022-07-12 20:37:56.384 | error | Caught by controller[0]: var u = b.y.toBigInteger().multiply(
host.ioBroker | 2022-07-12 20:37:56.383 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.javascript/node_modules/ecc-jsbn/lib/ec.js:126

</body>
</html>`

**Comment by duczz** [comment]
This fixed the problem:
1. /opt/iobroker/node_modules/iobroker.javascript\node_modules umbenennen z.b. *.old
2. npm rebuild iobroker.javascript
