### ISSUE TITLE
Upgrade v5.8.5 > v5.8.7 fails

### ISSUE THREAD

**Issue by EvilEls** [ioBroker/ioBroker.javascript#1072]
Adapter does not start any more after upgrade to v5.8.7

```
host.| 2022-07-13 10:14:37.693 | error | instance system.adapter.javascript.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.| 2022-07-13 10:14:37.693 | error | Caught by controller[0]: }
host.| 2022-07-13 10:14:37.693 | error | Caught by controller[0]:   ]
host.| 2022-07-13 10:14:37.693 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.javascript/main.js'
host.| 2022-07-13 10:14:37.693 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/coffee-compiler/coffee-compiler.js',
host.| 2022-07-13 10:14:37.692 | error | Caught by controller[0]:   requireStack: [
host.| 2022-07-13 10:14:37.692 | error | Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
host.| 2022-07-13 10:14:37.692 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:974:19) {
host.| 2022-07-13 10:14:37.692 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
host.| 2022-07-13 10:14:37.692 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:950:32)
host.| 2022-07-13 10:14:37.692 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
host.| 2022-07-13 10:14:37.692 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
host.| 2022-07-13 10:14:37.692 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/coffee-compiler/coffee-compiler.js:7:10)
host.| 2022-07-13 10:14:37.691 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:101:18)
host.| 2022-07-13 10:14:37.691 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:974:19)
host.| 2022-07-13 10:14:37.691 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
host.| 2022-07-13 10:14:37.691 | error | Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
host.| 2022-07-13 10:14:37.691 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.javascript/main.js
host.| 2022-07-13 10:14:37.691 | error | Caught by controller[0]: - /opt/iobroker/node_modules/coffee-compiler/coffee-compiler.js
host.| 2022-07-13 10:14:37.691 | error | Caught by controller[0]: Require stack:
host.| 2022-07-13 10:14:37.690 | error | Caught by controller[0]: Error: Cannot find module 'coffee-script'
host.| 2022-07-13 10:14:37.690 | error | Caught by controller[0]:   ^
host.| 2022-07-13 10:14:37.690 | error | Caught by controller[0]:   throw err;
host.| 2022-07-13 10:14:37.690 | error | Caught by controller[0]: internal/modules/cjs/loader.js:905
```

node: v14.19.3, js-controller: 4.0.23

**Comment by EvilEls** [comment]
upgrade to 5.8.8 is working

```$ iobroker upgrade javascript@5.8.8 --debug
Update javascript from @5.8.5 to @5.8.8
NPM version: 6.14.17
Installing iobroker.javascript@5.8.8... (System call)
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated node-inspect@2.0.0: This module is part of Node.js core and does not need to be installed separately. It is now unmaintained.
> iobroker.javascript@5.8.8 postinstall /opt/iobroker/node_modules/iobroker.javascript> node ./install/installTypings.js
Installing NodeJS typings...
latest @types: 18, installed node: 14
npm WARN @zwave-js/log-transport-json@2.0.1 requires a peer of winston@^3.7.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
+ iobroker.javascript@5.8.8added 1 package from 1 contributor, removed 12 packages and updated 2 packages in 20.653s
113 packages are looking for funding
run `npm fund` for details
Update "system.adapter.javascript.0"
...
Process exited with code 0
```


`starting. Version 5.8.8 in /opt/iobroker/node_modules/iobroker.javascript, node: v14.19.3, js-controller: 4.0.23`

Thank you! 👍
