### ISSUE TITLE
Typescript-Script ReferenceError with 3.7.0

### ISSUE THREAD

**Issue by Hypnos3** [ioBroker/ioBroker.javascript#118]
With Javascript Adapter 3.7.0 on compiling a Typescript I get the Error "ReferenceError: exports is not defined". I have tested the regular (https://github.com/ioBroker/ioBroker.javascript) and the Version from AlCalzone (https://github.com/AlCalzone/ioBroker.javascript/tarball/better-editor), in both the same error.

Back to 3.6.4, all is working fine.

```
javascript.0	2018-05-18 20:19:02.802	error	at ContextifyScript.Script.runInContext (vm.js:35:29)
javascript.0	2018-05-18 20:19:02.802	error	at script.js.common.Status.Stauberechnung_ts:2:23
javascript.0	2018-05-18 20:19:02.802	error	ReferenceError: exports is not defined
javascript.0	2018-05-18 20:19:02.802	error	^
javascript.0	2018-05-18 20:19:02.802	error	Object.defineProperty(exports, "__esModule", { value: true });
javascript.0	2018-05-18 20:19:02.800	error	script.js.common.Status.Stauberechnung_ts: script.js.common.Status.Stauberechnung_ts:2
javascript.0	2018-05-18 20:19:02.796	info	script.js.common.Status.Stauberechnung_ts: TypeScript compilation successful
javascript.0	2018-05-18 20:19:02.686	info	script.js.common.Status.Stauberechnung_ts: compiling TypeScript source...
javascript.0	2018-05-18 20:19:02.686	error	at ContextifyScript.Script.runInContext (vm.js:35:29)
javascript.0	2018-05-18 20:19:02.685	error	at script.js.common.Status.TüreFenster_ts:2:23
javascript.0	2018-05-18 20:19:02.685	error	ReferenceError: exports is not defined
javascript.0	2018-05-18 20:19:02.685	error	^
javascript.0	2018-05-18 20:19:02.685	error	Object.defineProperty(exports, "__esModule", { value: true });
javascript.0	2018-05-18 20:19:02.685	error	script.js.common.Status.TüreFenster_ts: script.js.common.Status.TüreFenster_ts:2
javascript.0	2018-05-18 20:19:02.680	info	script.js.common.Status.TüreFenster_ts: TypeScript compilation successful
javascript.0	2018-05-18 20:19:02.501	info	script.js.common.Status.TüreFenster_ts: compiling TypeScript source...
javascript.0	2018-05-18 20:19:02.501	error	at ContextifyScript.Script.runInContext (vm.js:35:29)
javascript.0	2018-05-18 20:19:02.501	error	at script.js.common.System.AlarmControl_ts:2:23
javascript.0	2018-05-18 20:19:02.501	error	ReferenceError: exports is not defined
javascript.0	2018-05-18 20:19:02.501	error	^
javascript.0	2018-05-18 20:19:02.500	error	Object.defineProperty(exports, "__esModule", { value: true });
javascript.0	2018-05-18 20:19:02.489	error	script.js.common.System.AlarmControl_ts: script.js.common.System.AlarmControl_ts:2
javascript.0	2018-05-18 20:19:02.486	info	script.js.common.System.AlarmControl_ts: TypeScript compilation successful
javascript.0	2018-05-18 20:19:02.420	info	script.js.common.System.AlarmControl_ts: compiling TypeScript source...
```

**Comment by GermanBluefox** [comment]
Vm2 says something  about it

**Comment by AlCalzone** [comment]
Ok then I'll try adding `exports` as a property to the sandbox later.

**Comment by Hypnos3** [comment]
Sagt bescheid, wenn ich helfen kann (z. B. testen).

Diese Mail ✉ wurde von meinem Mobiltelefon📱 gesendet.

AlCalzone <notifications@github.com> schrieb am Di., 22. Mai 2018, 20:10:

**Comment by AlCalzone** [comment]
@Hypnos3 Bitte testen :) Die Änderung ist jetzt im Master-Branch bzw. in meinem better-editor Branch

**Comment by Hypnos3** [comment]
Hallo,
habe jetzt deine Version (https://github.com/AlCalzone/ioBroker.javascript/tarball/better-editor) am laufen.

Mittlerweile funktioniert alles. ich musste nur folgendes anpassen:
- die Definition von DictionaryLike wurde entfernt - kein Problem hab ich bei mir angepasst
- in "normalen" Javascript Scripten müssen variablen jetzt definiert sein

zu letzterem, ich hatte in einem js Script eine Variable, wo das "let" oder "var" vorher fehlte. Bisher wurde das nicht als Fehler angezeigt. Jetzt hat er einen Fehler ausgegeben.
zur Klarstellung: Für mich ist das völlig OK und richtig, wenn das jetzt als Fehler ausgegeben wird (daher hab ich schon soviel wie möglich auf typescript umgestellt).

Ich hab das nochmal verifiziert:
```
let testfunk = 'test mal';

function testit() {
 einTest = 'blub';

}

testit();
```

bringt:
```
23:59:36.445 | [info] | javascript.0 Start javascript script.js.common.Skript1
-- | -- | --
23:59:36.445 | [error] | javascript.0 script.js.common.Skript1: script.js.common.Skript1:5
23:59:36.445 | [error] | javascript.0 at testit (script.js.common.Skript1:5:10)
23:59:36.445 | [error] | javascript.0 at script.js.common.Skript1:9:1
```

folgendes geht dann:
```
let testfunk = 'test mal';

function testit() {
 let einTest = 'blub';

}

testit();
```

Es kann auch sein, das dies nur bei mir so ist. ich habe in meinen Globalen Scripten die Anweisung `"use strict";`. Ich bin mir aber sicher, das bisher dieser Fehler nicht angemeckert wurde (sonst wäre mir das fehlerhafte Script aufgefallen).

Gruß

**Comment by Hypnos3** [comment]
@AlCalzone:
gleich mal zu deinem Editor:
Der ist super, aber jetzt zeigt er alles was an globalen Funktionen definiert ist als Fehler an.

Könnte man da nicht eine Möglichkeit bieten eine eigene Definitionsdatei einzubinden?

Dann hab ich noch etwas zweites, das ich mal melden wollte:
Ich habe herausgefunden, dass man für das "normale" compilieren und starten die Definitionen der Funktionen aus den globalen Scripte nicht benötigt. Lediglich beim Start (oder Neustart) des Javascript Adapters werden die Funktionen als nicht vorhanden beim compilieren angemeckert. Sobald alle Funktionen dann einmal "durchcompiliert"/gestartet (oder zumindest versucht) wurden, kann man die Scripte normal neu starten und dann funktioniert auch wieder alles (er findet die Funktionen aus den globalen Scripten beim compilieren der Scripte unter common).

Ich habe mir daher einen Workaround gebaut, ein Script wie folge:
```
//---------------------------------------------------------
//This Script is for restart all Scripts after a time
//---------------------------------------------------------
//var exports:any = {};
 
setTimeout(() => {
    // restart script
    //runScript('groupName.scriptName1');
    let myName : string = name;
    log('Script ' + myName + ' started!', 'info');

    $('javascript.0.scriptEnabled.common.*').each( (id :string, index:number):boolean => {
        try {
            let scriptName : string = id.replace('javascript.0.scriptEnabled.','');
            if (myName.indexOf(scriptName) < 0) {
                if (isScriptActive(scriptName)) {
                    log('restart active script ' + scriptName, 'info');
                    // restart script
                    runScript(scriptName);
                }
            }
        } catch (err) {
            log('Error:' + id,'error');
            log(JSON.stringify(err),'error');
        }
        return true;
    } );
    log('Script ' + name + ' ended!', 'info');
},10000); /* end */
```

Also ich starte einfach alle Scripte neu und dann werden alle geladen. (Ist ein hässlicher Workaround.)
Vielleicht könnte man beim Adapter Start es so gestalten das der Workaround nicht nötig ist?

**Comment by AlCalzone** [comment]
> die Definition von DictionaryLike wurde entfernt - kein Problem hab ich bei mir angepasst

`DictionaryLike<T>` ist noch ein Relikt aus einer Zeit, in der ich von `Record<string, T>` nicht wusste. Wollte das so früh wie möglich entfernen.

> in "normalen" Javascript Scripten müssen variablen jetzt definiert sein

Zur Klarstellung: Das müssen sie nur, wenn "use strict" verwendet wird. Dass du diese Definition in deinen globalen Skripten hast, kann der Editor aktuell leider nicht wissen. Abhilfe schafft `"use strict";` am Anfang deiner lokalen Skripte.  
Dass das bisher kein Fehler gewesen sein soll, kann ich so nicht nachvollziehen - an der Ausführung habe ich aber nichts geändert.

> Könnte man da nicht eine Möglichkeit bieten eine eigene Definitionsdatei einzubinden?

Auch das ist in der aktuellen Form des Adapters leider nicht möglich. Ab NodeJS 10 kann die Script-VM Module, damit will ich mich demnächst beschäftigen. Dann könntest du einfach per `require` oder `import` anderweitig definierte Module (z.b. globale Funktionen) einbinden, ohne dass die vor jedes Skript gehängt werden.
Du kannst aber deine globalen Funktionen in lokalen Funktionen deklarieren (analog zu einer eigenen Definitionsdatei). Dazu am Anfang deines lokalen Skriptes z.B. folgendes einfügen:
```ts
declare function globaleFunktion(arg1: string, arg2: any): void;
```
Die Signatur muss deiner globalen Funktion entsprechen, aber ohne Implementation. Ich nehm das mal als Anregung auf, dass automatisch Definitionen für globale TypeScripts erzeugt und geladen werden.

**Comment by Hypnos3** [comment]
Hallo AlCalzone,

das ich die globalen Funktionen in den lokalen Funktionen deklarieren kann (analog zu einer eigenen Definitionsdatei) ist mir bekannt.

In jede der >20 Scriptdateien einen großen Definitionsblock hängen zu müssen, auch wenn das Script selbst dann nur einige Zeilen groß ist, ist mit Kanonen auf Spatzen schießen.

Ob die Definitionen für die globalen TypeScripts automatisch gehen müssen weiß ich nicht. Es würde sicher helfen, wenn es erstmal manuell möglich wäre.

Gruß

**Comment by AlCalzone** [comment]
> Ob die Definitionen für die globalen TypeScripts automatisch gehen müssen weiß ich nicht. Es würde sicher helfen, wenn es erstmal manuell möglich wäre.

Helfen würde es, ist aber aus programmiersicht wesentlich mehr Aufwand ;)

**Comment by AlCalzone** [comment]
Die Generierung der Definitionen und Einbindung in die Kompilierung der globalen Scripts wird mit #121 erledigt. Muss ich aber noch testen. Wenn das geht, lasse ich die auch automatisch in den Editor einbinden.

**Comment by Hypnos3** [comment]
Werden damit auch Definitionen für Prototypen erzeugt?

Definition:
```
	interface String {
		/** removes spaces on the left side (beginning) of the string
		 *  @returns            string without spaces on the beginning
		 */	
		ltrim(): string;

		/** removes spaces on the right side (ending) of the string
		 *  @returns            string without spaces on the end
		 */	
		rtrim(): string;

		/** Replace repeated spaces, newlines and tabs with a single space
		 *  @returns            string with no duplicate spaces
		 */
		normalizeSpace (): string;

		/** check if a string start with a string
		 *  @param     part     the string to search for
		 *  @returns            true if the string start with the string in the part parameter
		 */
		startsWith(part: string): boolean;

		/** check if a string ends with a string
		 *  @param     part     the string to search for
		 *  @returns            true if the string ends with the string in the part parameter
		 */
		 endsWith(part: string): boolean;

		/** check if a string contains an other string
		 *  @param     part     the string to search for
		 *  @returns            true if the string contains the string in the part parameter
		 */
		contains(part: string): boolean;
		
		/** converts a string to a boolean
		 *  @returns            true if the string starts with 1, t(rue), y(es), j(a), w(ahr), r(ight)
		 */
		toBool(): boolean;
		
		/** replace all occurences in a string
		 *  @param     find     the string to search for
		 *  @param     replace  the new string which should be used instead of the find string
		 *  @returns            string, where all occurencs of find are replaced with replace
		 */
		replaceAll(find: string, replace: string): string;
	}

	interface StringConstructor {
		/** Check if a string is null, undefined or empty
		 *  @param     val   the string value to check for null, undefined or empty
		 *  @returns         true if the given Parameter is an null, undefined or empty String
		 */
		isNullOrEmpty: (val: any) => boolean;
	}

```

globales Typescript:
```
if (typeof String.prototype.ltrim === 'undefined') {
	/** removes spaces on the left side (beginning) of the string
	 *  @returns            string without spaces on the beginning
	 */
    String.prototype.ltrim = function (this : string): string {
        return this.replace(/^\s+/, "");
    };
}

if (typeof String.prototype.rtrim === 'undefined') {
	/** removes spaces on the right side (ending) of the string
	 *  @returns            string without spaces on the end
	 */
    String.prototype.rtrim = function (this : string): string {
        return this.replace(/\s+$/, "");
    };
}

if (typeof String.prototype.normalizeSpace === 'undefined') {
	/** Replace repeated spaces, newlines and tabs with a single space
	 *  @returns            string with no duplicate spaces
	 */
    String.prototype.normalizeSpace = function (this : string): string {
        return this.replace(/^\s*|\s(?=\s)|\s*$/g, "");
    };
}

if (typeof String.prototype.startsWith === 'undefined') {
	/** check if a string start with a string
	 *  @param     part     the string to search for
	 *  @returns            true if the string start with the string in the part parameter
	 */
    String.prototype.startsWith = function (this : string, part: string): boolean {
        return this.slice(0, part.length) == part;
    };
}

if (typeof String.prototype.endsWith === 'undefined') {
		/** check if a string ends with a string
	 *  @param     part     the string to search for
	 *  @returns            true if the string ends with the string in the part parameter
	 */
    String.prototype.endsWith = function (this : string, part: string): boolean {
        return this.slice(part.length) == part;
    };
}


if (typeof String.prototype.contains === 'undefined') {
	/** check if a string contains an other string
	 *  @param     part     the string to search for
	 *  @returns            true if the string contains the string in the part parameter
	 */
    String.prototype.contains = function(this : string, part : string): boolean {
        return this.indexOf(part) !== -1;
    };
}

if (typeof String.prototype.toBool === 'undefined') {
	/** converts a string to a boolean
	 *  @returns            true if the string starts with 1, t(rue), y(es), j(a), w(ahr), r(ight)
	 */
    String.prototype.toBool = function (): boolean {
        
        if ((<any>String).isNullOrEmpty(this)) {
            return false;
        }
        
        let toTest = this.toLowerCase().trim();
        
        if (toTest.indexOf("t") === 0 || //true
            toTest.indexOf("1") === 0 ||
            toTest.indexOf("w") === 0 || //wahr
            toTest.indexOf("y") === 0 || //yes
            toTest.indexOf("j") === 0 || //ja
            toTest.indexOf("r") === 0) {
            return true;
        }
        return false;
    };
}

if (typeof String.prototype.replaceAll === 'undefined') {
	/** replace all occurences in a string
	 *  @param     find     the string to search for
	 *  @param     replace  the new string which should be used instead of the find string
	 *  @returns            string, where all occurencs of find are replaced with replace
	 */
	String.prototype.replaceAll = function(this: string, find: string, replace: string): string {
		var str:string = this;
		return str.replace(new RegExp(find.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "\\$1"), 'g'), replace);
	};
}

if (typeof String.isNullOrEmpty === 'undefined') {
	/** Check if a string is null, undefined or empty
	 *  @param     val   the string value to check for null, undefined or empty
	 *  @returns         true if the given Parameter is an null, undefined or empty String
	 */
    String.isNullOrEmpty = function (val: any): boolean {
        if (val === undefined || val === null || val.trim() === '') {
            return true;
        }
        return false;
    };
}
```

**Comment by AlCalzone** [comment]
Wenn die ergänzten Interface-Definitionen in dem globalen Skripten stehen, sollte das gehen.
