### ISSUE TITLE
Build for v7.0.1 fails with errors

### ISSUE THREAD

**Issue by githtz** [ioBroker/ioBroker.javascript#1274]
**Describe the bug**  

I would like to contribute to this project, if possible. Therefore I wanted to get familiar with the code, build the project and play around with it, execute tests and such.
Sadly, v7.0.1 can not be build following the provided instructions. I could use some help.

**To Reproduce**  

1. `git clone git@github.com:ioBroker/ioBroker.javascript.git`
2. `git checkout ea54f9feaa25dc0bfada469d673e7ca23ee11fd1`
3. `npm install`
4. `cd src`
5. `npm install`
6. `cd ..`
7. `npm run build`

**Expected behavior**  

Project should build.

**Screenshots & Logfiles**  
```
npm run build

> iobroker.javascript@7.0.1 build
> node node_modules/gulp/bin/gulp.js

[17:28:21] Using gulpfile ~/git/ioBroker.javascript/gulpfile.js
[17:28:21] Starting 'default'...
[17:28:21] Starting '6-patch-dep'...
[17:28:21] Starting '5-copy-dep'...
[17:28:21] Starting '3-build-dep'...
[17:28:21] Starting '2-npm'...
[17:28:21] Finished '2-npm' after 447 μs
[17:28:21] Starting '3-build'...
ioBroker.javascript/src/
ioBroker.javascript/src/node_modules/craco-module-federation/index.js:43
        new webpack.container.ModuleFederationPlugin(
                              ^

TypeError: Cannot read properties of undefined (reading 'ModuleFederationPlugin')
    at Object.overrideWebpackConfig (ioBroker.javascript/src/node_modules/craco-module-federation/index.js:43:31)
    at overrideWebpack (ioBroker.javascript/src/node_modules/@craco/craco/dist/lib/features/plugins.js:36:38)
    at ioBroker.javascript/src/node_modules/@craco/craco/dist/lib/features/plugins.js:53:29
    at Array.forEach (<anonymous>)
    at applyWebpackConfigPlugins (ioBroker.javascript/src/node_modules/@craco/craco/dist/lib/features/plugins.js:52:29)
    at mergeWebpackConfig (ioBroker.javascript/src/node_modules/@craco/craco/dist/lib/features/webpack/merge-webpack-config.js:119:70)
    at overrideWebpackProd (ioBroker.javascript/src/node_modules/@craco/craco/dist/lib/features/webpack/override.js:14:80)
    at ioBroker.javascript/src/node_modules/@craco/craco/dist/scripts/build.js:20:40

child process exited with code 1
[17:28:22] '3-build' errored after 917 ms
[17:28:22] Error: Exit code: 1
    at formatError (ioBroker.javascript/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (ioBroker.javascript/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (node:events:402:35)
    at Gulp.emit (node:domain:475:12)
    at Object.error (ioBroker.javascript/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (ioBroker.javascript/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (ioBroker.javascript/node_modules/once/once.js:25:25)
    at f (ioBroker.javascript/node_modules/once/once.js:25:25)
    at tryCatch (ioBroker.javascript/node_modules/async-done/index.js:24:15)
    at done (ioBroker.javascript/node_modules/async-done/index.js:40:12)
[17:28:22] '3-build-dep' errored after 919 ms
[17:28:22] '5-copy-dep' errored after 919 ms
[17:28:22] '6-patch-dep' errored after 920 ms
[17:28:22] 'default' errored after 921 ms
```

**Versions:**  
https://github.com/ioBroker/ioBroker.javascript/releases/tag/v7.0.1

**Additional context**  
```
node --version
v19.7.0
npm --version
9.5.0
```

**Comment by Apollon77** [comment]
Pleas einstall "npm install -f" in the src directory, else it might be stuff missing because the dependency issues

**Comment by githtz** [comment]
Hi there Apollon, thanks for your response :)

Using `npm install -f` in `./src` solved the problem in `6.1.4`, but with the commit mentioned above for `7.0.2` I still get the same error message.

**Comment by Apollon77** [comment]
But why you checkout a special commit? Please always use master branch

**Comment by githtz** [comment]
Sorry for the confusion, I should have explained it in more detail.

I started with the master branch and experienced the same problem as I described above. I assumed the master branch might not be in a stable state, so I used the commit of the last release (7.0.1) - because I assumed that release should be stable.

**Comment by Apollon77** [comment]
All working, also on github actions.

Try to temove all node-modules and package-lock again and execute the two "npm i" again (in src with -f)

**Comment by githtz** [comment]
Hey there, sorry for the late response. The issue remains the same. Checked out the code again from scratch and tried the suggested steps, with the same result as before.

**Comment by Apollon77** [comment]
@GermanBluefox any idea?

**Comment by GermanBluefox** [comment]
Latest github version is working again: https://github.com/ioBroker/ioBroker.javascript/actions/runs/5010803326
