### ISSUE TITLE
Adapter process does not terminate correctly if using some 3rd party modules

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.javascript#1278]
I'm using [exclusive keyboard](https://www.npmjs.com/package/exclusive-keyboard) to read input from a Bluetooth remote. This node module seems rather ill behaved and can cause the Javascript adapter to crash. Not in itself a problem with the adapter, but...

... when the adapter crashes and is restarted duplicate processes appear. Eg, crash...

```
2023-03-22 07:43:59.013  - error: javascript.10 (15976) An error happened which is most likely from one of your scripts, but the originating script could not be detected.
2023-03-22 07:43:59.014  - error: javascript.10 (15976) Error: Attempt to access memory outside buffer bounds
2023-03-22 07:43:59.015  - error: javascript.10 (15976) RangeError: Attempt to access memory outside buffer bounds
    at new NodeError (node:internal/errors:387:5)
    at boundsError (node:internal/buffer:84:11)
    at Buffer.readUInt16LE (node:internal/buffer:243:5)
    at parse (/opt/iobroker/node_modules/iobroker.javascript/node_modules/exclusive-keyboard/index.js:16:14)
    at ReadStream.onData (/opt/iobroker/node_modules/iobroker.javascript/node_modules/exclusive-keyboard/index.js:54:21)
    at ReadStream.emit (node:events:513:28)
    at ReadStream.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at ReadStream.Readable.push (node:internal/streams/readable:228:10)
    at node:internal/fs/streams:279:14
    at FSReqCallback.wrapper [as oncomplete] (node:fs:671:5)
```

... restart...

```
2023-03-22 07:44:37.417  - info: host.pl stopInstance system.adapter.javascript.10 (force=false, process=true)
2023-03-22 07:44:37.476  - info: host.pl stopInstance system.adapter.javascript.10 send kill signal
2023-03-22 07:44:38.477  - info: host.pl stopInstance system.adapter.javascript.10 killing pid 15976
2023-03-22 07:44:40.650  - info: host.pl instance system.adapter.javascript.10 started with pid 3282
2023-03-22 07:44:45.278  - info: javascript.10 (3282) starting. Version 6.1.4 in /opt/iobroker/node_modules/iobroker.javascript, node: v16.19.0, js-controller: 4.0.24
2023-03-22 07:44:45.524  - info: javascript.10 (3282) requesting all states
2023-03-22 07:44:45.526  - info: javascript.10 (3282) requesting all objects
2023-03-22 07:44:47.787  - info: javascript.10 (3282) received all objects
2023-03-22 07:44:48.044  - info: javascript.10 (3282) received all states
```

... and yet now there are 2 processes running:

```
$ ps -ef | grep javascript.10 | grep -v grep
iobroker  3282  8519  3 07:44 ?        00:00:31 io.javascript.10
iobroker 15976  8519  0 Mar21 ?        00:02:07 io.javascript.10
```

**Comment by raintonr** [comment]
In fact, it is not only crash which causes this. `iob stop javascript.10` fails to exit the process normally even though IoB thinks it's doing so:

```
$ iob stop javascript.10
The adapter "javascript.10" was stopped.
$ tail -20 /opt/iobroker/log/iobroker.current.log  | grep 'javascript.10'
2023-03-23 07:23:10.557  - info: javascript.10 (23025) script.js.Whole_House.amazonRemote: powered: true
2023-03-23 07:23:10.560  - info: javascript.10 (23025) script.js.Whole_House.amazonRemote: powered: true
2023-03-23 07:23:25.398  - info: host.pl "system.adapter.javascript.10" disabled
2023-03-23 07:23:25.399  - info: host.pl stopInstance system.adapter.javascript.10 (force=false, process=true)
2023-03-23 07:23:25.415  - info: javascript.10 (23025) Got terminate signal TERMINATE_YOURSELF
2023-03-23 07:23:25.483  - info: host.pl stopInstance system.adapter.javascript.10 send kill signal
2023-03-23 07:23:25.417  - info: javascript.10 (23025) Stop script script.js.Whole_House.amazonRemote
2023-03-23 07:23:25.418  - info: javascript.10 (23025) script.js.Whole_House.amazonRemote: Stopping androidRemote
2023-03-23 07:23:25.419  - info: javascript.10 (23025) script.js.Whole_House.amazonRemote: Closing keyboard
2023-03-23 07:23:25.496  - info: javascript.10 (23025) script.js.Whole_House.amazonRemote: Connection closed
2023-03-23 07:23:25.503  - info: javascript.10 (23025) terminating
2023-03-23 07:23:25.508  - info: javascript.10 (23025) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-03-23 07:23:26.486  - info: host.pl stopInstance system.adapter.javascript.10 killing pid 23025
$ ps -ef | grep java | grep -v grep
iobroker 10756 10553 51 Mar22 ?        11:43:30 io.javascript.0
iobroker 23025 10553 11 07:21 ?        00:00:35 io.javascript.10
```

**Comment by raintonr** [comment]
Clues... https://github.com/pfirpfel/node-exclusive-keyboard/issues/5

Yes, it sounds like this is caused by a bug in underlying package, but IoB should be able to handle that all the same and maybe should `SIGTERM` if not exiting properly?

**Comment by klein0r** [comment]
This sounds like an enhancement for https://github.com/ioBroker/ioBroker.js-controller (if not already implemented)

**Comment by raintonr** [comment]
@klein0r ... has this really been fixed in js-controller? There is no mention of it in the changelog and I can't find a related js-controller issue the issue has been tracked under.

**Comment by klein0r** [comment]
> has this really been fixed in js-controller?

I've nerver said something like that...

**Comment by raintonr** [comment]
Oh. So what does, "Closed as completed" mean then?

**Comment by klein0r** [comment]
It means, that this is not the correct repository for that issue.
The js-controller is responsible for process management.
