### ISSUE TITLE
Problem mit fehlenden Modulen

### ISSUE THREAD

**Issue by Hypnos3** [ioBroker/ioBroker.javascript#131]
Hallo,

Javascript 3.7.0 ist zwar noch nicht offiziell, aber ich hatte damit getestet (Monaco Editor) und das Problem, das hier das Modul "util" nicht gefunden wird:

Die Scripte, welche es verwenden bringen einen Fehler:
```
2018-06-08 00:01:35.828 - error: javascript.0 Error in callback: ReferenceError: util is not defined
--
2018-06-08 00:01:35.828 - error: javascript.0 at logDebug1 (script.js.common.Status.TüreFenster_ts:60:27)
2018-06-08 00:01:35.828 - error: javascript.0 at setGenericStates (script.js.common.Status.TüreFenster_ts:69:5)
2018-06-08 00:01:35.828 - error: javascript.0 at getStateBalkontuer (script.js.common.Status.TüreFenster_ts:634:5)
2018-06-08 00:01:35.828 - error: javascript.0 at Object. (script.js.common.Status.TüreFenster_ts:483:5)
2018-06-08 00:01:35.828 - error: javascript.0 at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:731:38)
2018-06-08 00:01:35.829 - error: javascript.0 at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:309:21)
2018-06-08 00:01:35.829 - error: javascript.0 at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3425:37)
2018-06-08 00:01:35.829 - error: javascript.0 at RedisClient. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:596:25)
2018-06-08 00:01:35.829 - error: javascript.0 at emitThree (events.js:116:13)
2018-06-08 00:01:35.829 - error: javascript.0 at RedisClient.emit (events.js:194:7)

```

In den Einstelungen ist es vorhanden:
![image](https://user-images.githubusercontent.com/12692680/41205569-15062d9c-6cf6-11e8-9605-18e786fec37e.png)

Bin zurück auf 3.6.4 und alles funktioniert wieder.

**Comment by AlCalzone** [comment]
Um sicher zu gehen:
* Bitte mal den Code-Auszug mit der Zeile posten, wo der Fehler auftritt.
* Ist das ein TypeScript?
* Wenn ja, funktioniert die entsprechende Zeile in einem JavaScript?

**Comment by Hypnos3** [comment]
Ja, ist Typescript. Ich Teste das heute Abend.

**Comment by Hypnos3** [comment]
Das globale Script (Typescript):

```
"use strict";
// ##############################################################################
// ### Globale Funktionen zum vereinfachten loggen
// ### Version:             1.3.3
// ##############################################################################
///
/// Beschreibung:        Ermöglicht innerhalb eines Javascript-Scripts vereinfactes logging
///
/// Funktionen:
///             isPrimitive(obj)            Gibt true zurück, wenn ein Objekt ein String, Integer
///                                         oder Boolean ist und false bei einem komplexen Objekt.
///
///             logDebug(...)               Schreibt die übergebenen Argumente ins Logfile als
///                                         Debug-Meldung. Werden als Argumente komplexe Objekte
///                                         übergeben, werden diese als JSon ausgegeben. 
///                                         Zur Ausgabe dieser Meldungen muss der Javascript
///                                         Adapter auf debug gestellt sein!
///
///             logInfo(...)                Schreibt die übergebenen Argumente ins Logfile als
///                                         Info-Meldung. Werden als Argumente komplexe Objekte
///                                         übergeben, werden diese als JSon ausgegeben. 
///
///             logWarning(...)             Schreibt die übergebenen Argumente ins Logfile als
///                                         Warnung-Meldung. Werden als Argumente komplexe Objekte
///                                         übergeben, werden diese als JSon ausgegeben. 
///
///             logError(...)               Schreibt die übergebenen Argumente ins Logfile als
///                                         Fehler-Meldung. Werden als Argumente komplexe Objekte
///                                         übergeben, werden diese als JSon ausgegeben. 
///

/*
TypeScript Definitionen:
declare function isPrimitive(obj:any):boolean
declare function logDebug(...param: any[]):void;
declare function logInfo(...param: any[]):void;
declare function logWarning(...param: any[]):void;
declare function logError(...param: any[]):void;
*/
/// <reference path="node.d.ts"/>
import util = require("util");

/**
 * Function for check if a object is a primitive object (string, number, etc)
 * @param    obj           any object to check if it is a primitive object
 * @returns              boolean which is true if object in parameter is a primitive object
 */
function isPrimitive(obj:any):boolean {
    return (obj !== Object(obj));
}


/**
 * write any objects given as parameter to log as debug
 * @param    param       a nist of different objects
 */
function logDebug(...param: any[]):void {
	if (arguments.length > 0) {
		var text:string[] = [];
		for (var i = 0; i < arguments.length; i++) {
            if (typeof arguments[i] === 'string' || arguments[i] instanceof String) {
                text.push(arguments[i]);
		    } else if(arguments[i] === null) {
                text.push('null');
		    } else if(arguments[i] === undefined) {
                text.push('undefined');
            } else if (isPrimitive(arguments[i])) {
                text.push(arguments[i]);
            } else {
                text.push(util.inspect(arguments[i], { showHidden: false, depth: 10, maxArrayLength: null, breakLength: Infinity }));
            }
            //enum close bracket cannot be found in "channel[state.id=*.TEMPERATURE](rooms=WZ|Wohnung|Wohnzimmer"
			
		}
		//log(text.join(' '), 'debug');
		log(text.join(' '), 'debug');
	}
}

/**
 * write any objects given as parameter to log as Information
 * @param    param       a nist of different objects
 */
function logInfo(...param: any[]):void {
	if (arguments.length > 0) {
		var text:string[] = [];
		for (var i = 0; i < arguments.length; i++) {
            if (typeof arguments[i] === 'string' || arguments[i] instanceof String) {
                text.push(arguments[i]);
		    } else if(arguments[i] === null) {
                text.push('null');
		    } else if(arguments[i] === undefined) {
                text.push('undefined');
            } else if (isPrimitive(arguments[i])) {
                text.push(arguments[i]);
            } else {
                text.push(util.inspect(arguments[i], { showHidden: false, depth: 10, maxArrayLength: null, breakLength: Infinity }));
            }
            //enum close bracket cannot be found in "channel[state.id=*.TEMPERATURE](rooms=WZ|Wohnung|Wohnzimmer"
			
		}
		log(text.join(' '), 'info');
		setState("javascript.0.Ereignisliste.event",'INFO|'+text.join(' '));
	}
    //logEnhanced(logtext, 'info');
	//console.debug(p);
	//logs(logtext,loglevels.debug);
}

/**
 * write any objects given as parameter to log as warning
 * @param    param       a nist of different objects
 */
function logWarning(...param: any[]):void {
	if (arguments.length > 0) {
		var text:string[] = [];
		for (var i = 0; i < arguments.length; i++) {
            if (typeof arguments[i] === 'string' || arguments[i] instanceof String) {
                text.push(arguments[i]);
		    } else if(arguments[i] === null) {
                text.push('null');
		    } else if(arguments[i] === undefined) {
                text.push('undefined');
            } else if (isPrimitive(arguments[i])) {
                text.push(arguments[i]);
            } else {
                text.push(util.inspect(arguments[i], { showHidden: false, depth: 10, maxArrayLength: null, breakLength: 80 }));
            }
            //enum close bracket cannot be found in "channel[state.id=*.TEMPERATURE](rooms=WZ|Wohnung|Wohnzimmer"
			
		}
		log(text.join(' '), 'warn');
		setState("javascript.0.Ereignisliste.event",'WARN|'+text.join(' '));
	}
    //logEnhanced(logtext, 'warn');
	//console.warn(p);
	//logs(logtext,loglevels.warn);
} 

/**
 * write any objects given as parameter to log as error
 * @param    param       a nist of different objects
 */
function logError(...param: any[]):void {
	if (arguments.length > 0) {
		var text:string[] = [];
		for (var i = 0; i < arguments.length; i++) {
            if (typeof arguments[i] === 'string' || arguments[i] instanceof String) {
                text.push(arguments[i]);
		    } else if(arguments[i] === null) {
                text.push('null');
		    } else if(arguments[i] === undefined) {
                text.push('undefined');
            } else if (isPrimitive(arguments[i])) {
                text.push(arguments[i]);
            } else {
                text.push(util.inspect(arguments[i], { showHidden: false, depth: 10, maxArrayLength: null, breakLength: 80 }));
            }
            //enum close bracket cannot be found in "channel[state.id=*.TEMPERATURE](rooms=WZ|Wohnung|Wohnzimmer"
			
		}
		log(text.join(' '), 'error');
		setState("javascript.0.Ereignisliste.event",'ERROR|'+text.join(' '));
	}
}

// ##############################################################################
// ### Globale Funktionen zum vereinfachten loggen - Ende
// ##############################################################################
```

die weiteren Tests konnte ich leider nicht durchführen, weil ich mir irgendwie das Zerschossen habe und nicht weiß wie ich das wieder gerade biegen soll:
https://forum.iobroker.net/viewtopic.php?f=20&t=14829

**Comment by Hypnos3** [comment]
Ich glaube mein Problem kommt woanders her.

**Comment by AlCalzone** [comment]
Konnte auf den ersten Blick auch kein wirkliches Problem sehen.
Zwei Anmerkungen:

1. Wenn du meinen Monaco-Editor-Branch verwendest (#124), ist folgendes nicht mehr nötig, da sie automatische generiert und an andere Skripte übergeben werden
> ```js
> /*
> TypeScript Definitionen:
> declare function isPrimitive(obj:any):boolean
> declare function logDebug(...param: any[]):void;
> declare function logInfo(...param: any[]):void;
> declare function logWarning(...param: any[]):void;
> declare function logError(...param: any[]):void;
> */
> ```

2. Das hier sollte auch nicht nötig sein, da die Node Typings sowieso bereitgestellt werden.  
> `/// <reference path="node.d.ts"/>`

Außerdem gibt es meiner Info nach keine `node.d.ts`, korrekt wäre eher  
`/// <reference types="node" />`

**Comment by Hypnos3** [comment]
@AlCalzone Danke für deine Hinweise.

Ich bin aktuell zurück auf  3.6.4.

Hier hatte ich plötzlich Probleme, das die Zeile mit `import request = require("request");` angemeckert wurde. Diese Definitonen habe ich entfernt und seit dem läuft mit 3.6.4 alles. Da hab ich aktuell nur das Problem mit dem kaputte Javascript Editor.

Ich hatte gestern auch einen kurzen Test unter 3.7.0 - Monaco-Editor-Branch probiert. Hier kam aber wieder das Problem mit util, so dass ich jetzt wieder zurück auf 3.6.4 bin.

Den Issue hab ich geschlossen, weil ich nicht sagen kann ob es von meinem System kommt. Ich muss erstmal wieder mein System richtig zum Laufen bekommen (fehlende Buttons im Editor).

**Comment by AlCalzone** [comment]
`import request = require("request")` hab ich war schon mal gesehen, ich verwende aber i.d.R. eine der folgenden Varianten:
* `const request = require("request")`
* `import * as request from "request"`

Könnte es sein, dass das "util"-Modul, das du im Konfig-Dialog eingetragen hast, nicht das ist, was du willst? "util" ist soweit ich weiß ein immer installiertes core Modul von NodeJS.

Die fehlenden Buttons hatte ich auch. Lässt sich beheben, indem man das Adapter-Instanz-Objekt bearbeitet. Danach ist eventuell ein Upload bzw. Leeren des Browser-Caches nötig.
![unbenannt](https://user-images.githubusercontent.com/17641229/41280651-c1ee5072-6e2f-11e8-9b8d-4d3caa4e5fad.PNG)

**Comment by Hypnos3** [comment]
Besten Dank!!

Die Variante `const request = require("request")` funktioniert auch nicht. Die Variante `import * as request from "request"` hingegen funktioniert.

Damit kommt kein Fehler mehr.

Das Anpassen des Adapter-Instanz-Objekt hat auch funktioniert!

**Comment by Apollon77** [comment]
Das Modul request ist automatisch da als Variable request. Muss nicht mehr required werden.

**Comment by Hypnos3** [comment]
Ja, aber util muss das.

Ich bin immer noch am testen. Gerade mit 1.7.0

Bei 1.7.0 macht `import * as util from "util"` Probleme, dafür funktioniert es scheinbar hier mit `const request = require("request")`.

Jetzt geht es zumindest..

**Comment by AlCalzone** [comment]
Hast du mal das nachträglich installierte Modul util gelöscht? Und welchen Fehler gibt es denn? Evtl kann man dir helfen wenn man genauer weiß was faul ist 😉

**Comment by Hypnos3** [comment]
kein Problem

Also ich habe jetzt am laufen:
iobroker.admin = 3.4.5
iobroker.javascript= 3.7.0 (die Version mit Monaco Editor)

util entfernt und wieder hinzugefügt - bringt keine Fehler:
![image](https://user-images.githubusercontent.com/12692680/41369543-7662a0c4-6f45-11e8-912b-198ac11e8b78.png)

Die Tests:
Test Script 1 👍:
```
const utilx = require("util");

function doTest() {
    let t = {
        a : "1",
        b : 2,
        c : [ 3,4,5],
        d : {
            x : "Hallo"
        }
    }

    log(utilx.inspect(t, { showHidden: false, depth: 10, maxArrayLength: null, breakLength: Infinity }));

}
doTest();
```

Ausgabe:
```
20:14:20.577 | [info] | javascript.0 script.js.common.xTest_ts: compiling TypeScript source...
20:14:20.578 | [info] | javascript.0 script.js.common.xTest_ts: TypeScript compilation successful
20:14:20.578 | [info] | javascript.0 script.js.common.xTest_ts: { a: '1', b: 2, c: [ 3, 4, 5 ], d: { x: 'Hallo' } }
20:14:20.578 | [info] | javascript.0 script.js.common.xTest_ts: registered 0 subscriptions and 0 schedules
```

Test2 👎 :
```
import utilx = require("util");

function doTest() {
    let t = {
        a : "1",
        b : 2,
        c : [ 3,4,5],
        d : {
            x : "Hallo"
        }
    }

    log(utilx.inspect(t, { showHidden: false, depth: 10, maxArrayLength: null, breakLength: Infinity }));

}
doTest();
```

Ausgabe:
```
20:15:40.534 | [info] | javascript.0 script.js.common.xTest_ts: compiling TypeScript source...
20:15:40.534 | [warn] | javascript.0 script.js.common.xTest_ts: TypeScript compilation had errors: import utilx = require("util"); ^ ERROR: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
20:15:40.534 | [error] | javascript.0 script.js.common.xTest_ts: script.js.common.xTest_ts:40
20:15:40.534 | [error] | javascript.0 at doTest (script.js.common.xTest_ts:40:9)
20:15:40.534 | [error] | javascript.0 at script.js.common.xTest_ts:42:1
```

Test3 👎 :
```
import * as util from "util"

function doTest() {
    let t = {
        a : "1",
        b : 2,
        c : [ 3,4,5],
        d : {
            x : "Hallo"
        }
    }

    log(utilx.inspect(t, { showHidden: false, depth: 10, maxArrayLength: null, breakLength: Infinity }));

}
doTest();
```

Ausgabe:

```
20:17:13.901 | [info] | javascript.0 script.js.common.xTest_ts: compiling TypeScript source...
20:17:13.901 | [warn] | javascript.0 script.js.common.xTest_ts: TypeScript compilation had errors: log(utilx.inspect(t, { showHidden: false, depth: 10, maxArrayLength: null, breakLength: Infinity })); ^ ERROR: Cannot find name 'utilx'. Did you mean 'util'?
20:17:13.901 | [error] | javascript.0 script.js.common.xTest_ts: script.js.common.xTest_ts:40
20:17:13.902 | [error] | javascript.0 at doTest (script.js.common.xTest_ts:40:9)
20:17:13.902 | [error] | javascript.0 at script.js.common.xTest_ts:42:1
```

**Comment by AlCalzone** [comment]
Vorab, du brauchst "util" nicht extra installiert haben, das ist in NodeJS sowieso enthalten. Was du installierst, ist dieses Paket: https://www.npmjs.com/package/util
> You usually do not have to install util yourself. If your code runs in Node.js, util is built in. If your code runs in the browser, bundlers like browserify or webpack also include the util module.

Mit der aktuellsten GitHub-Version laufen deine Tests bei mir allesamt. Bitte nochmal von Github updaten (ioBroker-Repo, Master-Branch) und danach einen upload und restart der Instanz durchführen.

**Comment by Hypnos3** [comment]
> Vorab, du brauchst "util" nicht extra installiert haben, das ist in NodeJS sowieso enthalten. Was du installierst, ist dieses Paket: https://www.npmjs.com/package/util

Damit könnte man Util doch genauso einfach gleich von vornherein bereitstellen wie request.
