### ISSUE TITLE
`context.logWithLineInfo` ist nicht definiert (1.7.0)

### ISSUE THREAD

**Issue by Hypnos3** [ioBroker/ioBroker.javascript#132]
Wenn man mit 1.7.0 ein setState auf ein Objekt macht, welches nicht existiert, kommt eine hässliche Exception.

Beispielsweise:
`setState('javascript.0.gibtEsNicht', (new Date).toString());`

dann kommt:
```
2018-06-12 21:47:50.478  - [31merror[39m: javascript.0 Error in callback: TypeError: Cannot read property 'warn' of null
2018-06-12 21:47:50.478  - [31merror[39m: javascript.0     at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1174:44)
2018-06-12 21:47:50.478  - [31merror[39m: javascript.0     at Object.<anonymous> (script.js.common.Messages.TelegramCmd_ts:536:5)
2018-06-12 21:47:50.478  - [31merror[39m: javascript.0     at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:731:38)
2018-06-12 21:47:50.478  - [31merror[39m: javascript.0     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:324:21)
2018-06-12 21:47:50.478  - [31merror[39m: javascript.0     at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3425:37)
2018-06-12 21:47:50.478  - [31merror[39m: javascript.0     at RedisClient.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:596:25)
2018-06-12 21:47:50.478  - [31merror[39m: javascript.0     at emitThree (events.js:116:13)
2018-06-12 21:47:50.479  - [31merror[39m: javascript.0     at RedisClient.emit (events.js:194:7)
2018-06-12 21:47:50.479  - [31merror[39m: javascript.0     at return_pub_sub (/opt/iobroker/node_modules/redis/index.js:794:18)
2018-06-12 21:47:50.479  - [31merror[39m: javascript.0     at RedisClient.return_reply (/opt/iobroker/node_modules/redis/index.js:833:9)
2018-06-12 21:47:50.479  - [31merror[39m: javascript.0     at JavascriptRedisParser.returnReply (/opt/iobroker/node_modules/redis/index.js:192:18)
2018-06-12 21:47:50.479  - [31merror[39m: javascript.0     at JavascriptRedisParser.execute (/opt/iobroker/node_modules/redis-parser/lib/parser.js:574:12)
2018-06-12 21:47:50.479  - [31merror[39m: javascript.0     at Socket.<anonymous> (/opt/iobroker/node_modules/redis/index.js:274:27)
2018-06-12 21:47:50.479  - [31merror[39m: javascript.0     at emitOne (events.js:96:13)
2018-06-12 21:47:50.479  - [31merror[39m: javascript.0     at Socket.emit (events.js:188:7)
2018-06-12 21:47:50.479  - [31merror[39m: javascript.0     at readableAddChunk (_stream_readable.js:176:18)
2018-06-12 21:47:50.479  - [31merror[39m: javascript.0     at Socket.Readable.push (_stream_readable.js:134:10)
2018-06-12 21:47:50.479  - [31merror[39m: javascript.0     at TCP.onread (net.js:559:20)

```

**Comment by AlCalzone** [comment]
Scheint nicht direkt mit setState zu tun zu haben. Ich schau später mal rein.

**Comment by BuZZy1337** [comment]
Hatte ich heute auch den Fehler, da war in einer Tradfri Gruppe der Datenpunkt Brightness auf "null %".. Nachdem ich dann den Datenpunkt manuell auf 0% gesetzt hatte ging auch das Script wieder.
