### ISSUE TITLE
> 7.0.3 does not work with "global" scripts

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.javascript#1335]
> @klein0r Ich hab's mit deiner master-Version probiert. Geht leider nicht.
>
> Das ist das betreffende (als erstes kompilierte) Script: https://github.com/agross/iobroker-scripts/blob/master/home/global/Shared/Device.ts
>
> Lokal kompiliert es problemlos nachdem ich die TS-dependency auf `~5.1.3` anhebe.

<details>

```
2023-06-12 09:23:37.215  - info: javascript.0 (629891) script.js.global.Shared.Device: compiling TypeScript source...
2023-06-12 09:23:37.399  - error: javascript.0 (629891) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-06-12 09:23:37.400  - error: javascript.0 (629891) unhandled promise rejection: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.
2023-06-12 09:23:37.401  - error: javascript.0 (629891) Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.
    at cast (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:1170:18)
    at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:111076:31)
    at pipelineEmitWithHint (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:111061:9)
    at pipelineEmitWithComments (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:114845:7)
    at pipelineEmit (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:111010:7)
    at emitIdentifierName (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:110984:7)
    at emitClassDeclarationOrExpression (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112891:9)
    at emitClassDeclaration (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:112873:7)
    at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:111243:20)
    at pipelineEmitWithHint (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:111061:9)
    at pipelineEmitWithComments (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:114845:7)
    at pipelineEmit (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:111010:7)
    at emit (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:110978:7)
    at emitListItemWithParenthesizerRule (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:115291:5)
    at emitNodeListItems (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:114002:9)
    at emitNodeList (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:113941:9)
    at emitList (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:113899:7)
    at emitSourceFileWorker (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:113579:7)
    at emitBodyWithDetachedComments (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:114951:9)
    at emitSourceFile (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:113507:9)
    at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:111074:16)
    at pipelineEmitWithHint (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:111061:9)
    at pipelineEmit (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:111010:7)
    at print (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:110923:7)
    at writeFile2 (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:110907:7)
    at printFile (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:110747:7)
    at Object.printNode (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:110724:18)
    at transformScriptBeforeCompilation (/opt/iobroker/node_modules/iobroker.javascript/lib/typescriptTools.js:447:31)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/main.js:1123:67)
    at processImmediate (node:internal/timers:478:21)
2023-06-12 09:23:37.402  - error: javascript.0 (629891) Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.
2023-06-12 09:23:37.448  - info: javascript.0 (629891) terminating
2023-06-12 09:23:37.451  - warn: javascript.0 (629891) Terminated (UNCAUGHT_EXCEPTION): Without reason
```

</details>

_Originally posted by @agross in https://github.com/ioBroker/ioBroker.javascript/issues/1325#issuecomment-1586742982_

**Comment by agross** [comment]
With 7.1.1 I now see this:

```
2023-06-22 22:44:03.821  - error: javascript.0 (5824) Error: Debug Failure. Unhandled SyntaxKind: Unknown.
    at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111517:13)
    at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
    at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7)
    at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
    at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7)
    at emitEnumDeclaration (/opt/iobroker/node_modules/typescript/lib/typescript.js:112957:7)
    at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111249:20)
    at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
    at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7)
    at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
    at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7)
    at emitListItemWithParenthesizerRule (/opt/iobroker/node_modules/typescript/lib/typescript.js:115291:5)
    at emitNodeListItems (/opt/iobroker/node_modules/typescript/lib/typescript.js:114002:9)
    at emitNodeList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113941:9)
    at emitList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113899:7)
    at emitSourceFileWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:113579:7)
    at emitBodyWithDetachedComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114951:9)
    at emitSourceFile (/opt/iobroker/node_modules/typescript/lib/typescript.js:113507:9)
    at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111074:16)
    at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
    at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
    at print (/opt/iobroker/node_modules/typescript/lib/typescript.js:110923:7)
    at writeFile2 (/opt/iobroker/node_modules/typescript/lib/typescript.js:110907:7)
    at printFile (/opt/iobroker/node_modules/typescript/lib/typescript.js:110747:7)
    at Object.printNode (/opt/iobroker/node_modules/typescript/lib/typescript.js:110724:18)
    at transformScriptBeforeCompilation (/opt/iobroker/node_modules/iobroker.javascript/lib/typescriptTools.js:447:31)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/main.js:1123:67)
    at processImmediate (node:internal/timers:478:21)
```
```

**Comment by kuckuckmann** [comment]
For me it's the same. When updating from 7.0.3 to higher version I am getting 

`javascript.0
	2023-06-25 15:00:29.052	error	Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.
javascript.0
	2023-06-25 15:00:29.052	error	Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'. at cast (/opt/iobroker/node_modules/typescript/lib/typescript.js:1170:18) at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111076:31) at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9) at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7) at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7) at emitIdentifierName (/opt/iobroker/node_modules/typescript/lib/typescript.js:110984:7) at emitClassDeclarationOrExpression (/opt/iobroker/node_modules/typescript/lib/typescript.js:112891:9) at emitClassDeclaration (/opt/iobroker/node_modules/typescript/lib/typescript.js:112873:7) at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111243:20) at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9) at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7) at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7) at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7) at emitListItemWithParenthesizerRule (/opt/iobroker/node_modules/typescript/lib/typescript.js:115291:5) at emitNodeListItems (/opt/iobroker/node_modules/typescript/lib/typescript.js:114002:9) at emitNodeList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113941:9) at emitList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113899:7) at emitBlockStatements (/opt/iobroker/node_modules/typescript/lib/typescript.js:112494:7) at emitModuleBlock (/opt/iobroker/node_modules/typescript/lib/typescript.js:112989:7) at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111253:20) at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9) at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7) at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7) at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7) at emitModuleDeclaration (/opt/iobroker/node_modules/typescript/lib/typescript.js:112984:7) at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111251:20) at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9) at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7) at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7) at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7) at emitListItemWithParenthesizerRule (/opt/iobroker/node_modules/typescript/lib/typescript.js:115291:5) at emitNodeListItems (/opt/iobroker/node_modules/typescript/lib/typescript.js:114002:9) at emitNodeList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113941:9) at emitList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113899:7) at emitSourceFileWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:113579:7) at emitBodyWithDetachedComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114951:9) at emitSourceFile (/opt/iobroker/node_modules/typescript/lib/typescript.js:113507:9) at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111074:16) at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9) at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7) at print (/opt/iobroker/node_modules/typescript/lib/typescript.js:110923:7) at writeFile2 (/opt/iobroker/node_modules/typescript/lib/typescript.js:110907:7) at printFile (/opt/iobroker/node_modules/typescript/lib/typescript.js:110747:7) at Object.printNode (/opt/iobroker/node_modules/typescript/lib/typescript.js:110724:18) at transformGlobalDeclarations (/opt/iobroker/node_modules/iobroker.javascript/lib/typescriptTools.js:501:31) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/main.js:1168:64) at processImmediate (node:internal/timers:473:21)
javascript.0
	2023-06-25 15:00:29.052	error	unhandled promise rejection: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.
javascript.0
	2023-06-25 15:00:29.051	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

**Comment by agross** [comment]
Confirmed to be working, thanks!

**Comment by klein0r** [comment]
Gerne

**Comment by kuckuckmann** [comment]
Geht bei mir noch nicht

**Comment by agross** [comment]
Scratch that. Didn't have the GitHub version installed. @kuckuckmann Perhaps you should try installing from GitHub as well.
