### ISSUE TITLE
JS 7.0.8 UNCAUGHT_EXCEPTION

### ISSUE THREAD

**Issue by Scotty-89** [ioBroker/ioBroker.javascript#1336]
**Describe the bug**  
JS not working .... 

**To Reproduce**  
just start adapter ... 

**Expected behavior**  

**Screenshots & Logfiles**  
<html>
<body>

host.iobroker | 2023-06-12 22:23:40.754 | error | instance system.adapter.javascript.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
javascript.0 | 2023-06-12 22:23:39.873 | error | Debug Failure. Unhandled SyntaxKind: Unknown.
javascript.0 | 2023-06-12 22:23:39.873 | error | Error: Debug Failure. Unhandled SyntaxKind: Unknown. at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111517:13) at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9) at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7) at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7) at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7) at emitFunctionDeclarationOrExpression (/opt/iobroker/node_modules/typescript/lib/typescript.js:112776:7) at emitFunctionDeclaration (/opt/iobroker/node_modules/typescript/lib/typescript.js:112766:7) at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111241:20) at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9) at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7) at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7) at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7) at emitListItemWithParenthesizerRule (/opt/iobroker/node_modules/typescript/lib/typescript.js:115291:5) at emitNodeListItems (/opt/iobroker/node_modules/typescript/lib/typescript.js:114002:9) at emitNodeList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113941:9) at emitList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113899:7) at emitSourceFileWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:113579:7) at emitBodyWithDetachedComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114951:9) at emitSourceFile (/opt/iobroker/node_modules/typescript/lib/typescript.js:113507:9) at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111074:16) at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9) at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7) at print (/opt/iobroker/node_modules/typescript/lib/typescript.js:110923:7) at writeFile2 (/opt/iobroker/node_modules/typescript/lib/typescript.js:110907:7) at printFile (/opt/iobroker/node_modules/typescript/lib/typescript.js:110747:7) at Object.printNode (/opt/iobroker/node_modules/typescript/lib/typescript.js:110724:18) at transformScriptBeforeCompilation (/opt/iobroker/node_modules/iobroker.javascript/lib/typescriptTools.js:447:31) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/main.js:1123:67) at processImmediate (node:internal/timers:478:21)
javascript.0 | 2023-06-12 22:23:39.872 | error | unhandled promise rejection: Debug Failure. Unhandled SyntaxKind: Unknown.
javascript.0 | 2023-06-12 22:23:39.872 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>

**Versions:**  
 - Adapter version: 7.0.8
 - JS-Controller version: 5.0.2
 - Node version: v18.16.0
 - Operating system: <os-name>

**Additional context**

**Comment by JohGrei** [comment]
Bei mir tritt das selbe bei Version 7.1.0 auf.

`2023-06-13 20:26:24.137  - info:  javascript.0 (1135592) starting. Version 7.1.0 in  /opt/iobroker/node_modules/iobroker.javascript, node: v18.16.0,  js-controller: 4.0.24
--
2023-06-13 20:26:24.189  - info: javascript.0 (1135592) npm install simple-ssh --omit=dev (System call)
2023-06-13 20:27:07.221  - error: javascript.0 (1135592) npm
2023-06-13 20:27:07.222  - error: javascript.0 (1135592)  WARN deprecated har-validator@5.1.5: this library is no longer supported
2023-06-13 20:27:07.354  - error: javascript.0 (1135592) npm
2023-06-13 20:27:07.356  - error:  javascript.0 (1135592) WARN deprecated node-inspect@2.0.0: This module  is part of Node.js core and does not need to be installed separately. It  is now unmaintained.
2023-06-13 20:27:07.412  - error: javascript.0 (1135592) npm
2023-06-13 20:27:07.414  - error:  javascript.0 (1135592) WARN deprecated uuid@3.4.0: Please upgrade  to  version 7 or higher.  Older versions may use Math.random() in certain  circumstances, which is known to be problematic.  See  https://v8.dev/blog/math-random for details.
2023-06-13 20:27:07.451  - error: javascript.0 (1135592) npm
2023-06-13 20:27:07.452  - error:  javascript.0 (1135592) WARN deprecated request@2.88.2: request has been  deprecated, see https://github.com/request/request/issues/3142
2023-06-13 20:27:16.758  - info: javascript.0 (1135592)
added 92 packages, and audited 98 packages in 51s
2023-06-13 20:27:16.760  - info: javascript.0 (1135592)
4 packages are looking for funding
run `npm fund` for details
2023-06-13 20:27:16.766  - info: javascript.0 (1135592)
1 moderate severity vulnerability
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
2023-06-13 20:27:16.791  - info: javascript.0 (1135592) npm install modbus-serial --omit=dev (System call)
2023-06-13 20:27:21.781  - info: javascript.0 (1135592)
added 18 packages, and audited 116 packages in 4s
2023-06-13 20:27:21.784  - info: javascript.0 (1135592)
16 packages are looking for funding
run `npm fund` for details
2023-06-13 20:27:21.786  - info: javascript.0 (1135592)
1 moderate severity vulnerability
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
2023-06-13 20:27:21.814  - info: javascript.0 (1135592) npm install cheerio --omit=dev (System call)
2023-06-13 20:27:26.411  - info: javascript.0 (1135592)
added 28 packages, and audited 144 packages in 4s
2023-06-13 20:27:26.414  - info: javascript.0 (1135592)
29 packages are looking for funding
run `npm fund` for details
2023-06-13 20:27:26.419  - info: javascript.0 (1135592)
1 moderate severity vulnerability
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
2023-06-13 20:27:27.722  - warn: javascript.0 (1135592) Alias alias.0.Wetter.TEMP_MIN has no target 12
2023-06-13 20:27:27.723  - warn: javascript.0 (1135592) Alias alias.0.Wetter.TEMP_MAX has no target 12
2023-06-13 20:27:27.725  - warn: javascript.0 (1135592) Alias alias.0.NSPanel_1.alexa2.0.Echo-Devices.G2A1B5030504097G.SET has no target 12
2023-06-13 20:27:27.795  - info: javascript.0 (1135592) requesting all states
2023-06-13 20:27:27.796  - info: javascript.0 (1135592) requesting all objects
2023-06-13 20:27:29.115  - info: javascript.0 (1135592) received all objects
2023-06-13 20:27:29.523  - info: javascript.0 (1135592) received all states
2023-06-13 20:27:38.491  - info: javascript.0 (1135592) script.js.global.IconsSelector: compiling TypeScript source...
2023-06-13 20:27:41.622  - info: javascript.0 (1135592) script.js.global.IconsSelector: TypeScript compilation successful
2023-06-13 20:27:41.670  - error:  javascript.0 (1135592) Unhandled promise rejection. This error  originated either by throwing inside of an async function without a  catch block, or by rejecting a promise which was not handled with  .catch().
2023-06-13 20:27:41.671  - error:  javascript.0 (1135592) unhandled promise rejection: Debug Failure.  Invalid cast. The supplied value [object Object] did not pass the test  'isIdentifier'.
2023-06-13 20:27:41.671  - error:  javascript.0 (1135592) Error: Debug Failure. Invalid cast. The supplied  value [object Object] did not pass the test 'isIdentifier'.
at cast (/opt/iobroker/node_modules/typescript/lib/typescript.js:1170:18)
at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111076:31)
at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7)
at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
at emitIdentifierName (/opt/iobroker/node_modules/typescript/lib/typescript.js:110984:7)
at emitClassDeclarationOrExpression (/opt/iobroker/node_modules/typescript/lib/typescript.js:112891:9)
at emitClassDeclaration (/opt/iobroker/node_modules/typescript/lib/typescript.js:112873:7)
at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111243:20)
at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7)
at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7)
at emitListItemWithParenthesizerRule (/opt/iobroker/node_modules/typescript/lib/typescript.js:115291:5)
at emitNodeListItems (/opt/iobroker/node_modules/typescript/lib/typescript.js:114002:9)
at emitNodeList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113941:9)
at emitList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113899:7)
at emitBlockStatements (/opt/iobroker/node_modules/typescript/lib/typescript.js:112494:7)
at emitModuleBlock (/opt/iobroker/node_modules/typescript/lib/typescript.js:112989:7)
at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111253:20)
at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7)
at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7)
at emitModuleDeclaration (/opt/iobroker/node_modules/typescript/lib/typescript.js:112984:7)
at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111251:20)
at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
at pipelineEmitWithComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7)
at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7)
at emitListItemWithParenthesizerRule (/opt/iobroker/node_modules/typescript/lib/typescript.js:115291:5)
at emitNodeListItems (/opt/iobroker/node_modules/typescript/lib/typescript.js:114002:9)
at emitNodeList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113941:9)
at emitList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113899:7)
at emitSourceFileWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:113579:7)
at emitBodyWithDetachedComments (/opt/iobroker/node_modules/typescript/lib/typescript.js:114951:9)
at emitSourceFile (/opt/iobroker/node_modules/typescript/lib/typescript.js:113507:9)
at pipelineEmitWithHintWorker (/opt/iobroker/node_modules/typescript/lib/typescript.js:111074:16)
at pipelineEmitWithHint (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
at pipelineEmit (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
at print (/opt/iobroker/node_modules/typescript/lib/typescript.js:110923:7)
at writeFile2 (/opt/iobroker/node_modules/typescript/lib/typescript.js:110907:7)
at printFile (/opt/iobroker/node_modules/typescript/lib/typescript.js:110747:7)
at Object.printNode (/opt/iobroker/node_modules/typescript/lib/typescript.js:110724:18)
at transformGlobalDeclarations (/opt/iobroker/node_modules/iobroker.javascript/lib/typescriptTools.js:501:31)
at Immediate. (/opt/iobroker/node_modules/iobroker.javascript/main.js:1168:64)
at processImmediate (node:internal/timers:478:21)
2023-06-13 20:27:41.672  - error: javascript.0 (1135592) Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.
2023-06-13 20:27:41.730  - info: javascript.0 (1135592) terminating
2023-06-13 20:27:41.731  - warn: javascript.0 (1135592) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-06-13 20:27:43.478  - error:  host.vm-iobroker Caught by controller[0]: This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2023-06-13 20:27:43.483  - error:  host.vm-iobroker Caught by controller[1]: Error: Debug Failure. Invalid  cast. The supplied value [object Object] did not pass the test  'isIdentifier'.
2023-06-13 20:27:43.484  - error: host.vm-iobroker Caught by controller[1]:     at cast (/opt/iobroker/node_modules/typescript/lib/typescript.js:1170:18)
2023-06-13 20:27:43.484  - error:  host.vm-iobroker Caught by controller[1]:     at  pipelineEmitWithHintWorker  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111076:31)
2023-06-13 20:27:43.484  - error:  host.vm-iobroker Caught by controller[1]:     at pipelineEmitWithHint  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
2023-06-13 20:27:43.484  - error:  host.vm-iobroker Caught by controller[1]:     at  pipelineEmitWithComments  (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7)
2023-06-13 20:27:43.484  - error:  host.vm-iobroker Caught by controller[1]:     at pipelineEmit  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
2023-06-13 20:27:43.485  - error:  host.vm-iobroker Caught by controller[1]:     at emitIdentifierName  (/opt/iobroker/node_modules/typescript/lib/typescript.js:110984:7)
2023-06-13 20:27:43.485  - error:  host.vm-iobroker Caught by controller[1]:     at  emitClassDeclarationOrExpression  (/opt/iobroker/node_modules/typescript/lib/typescript.js:112891:9)
2023-06-13 20:27:43.485  - error:  host.vm-iobroker Caught by controller[1]:     at emitClassDeclaration  (/opt/iobroker/node_modules/typescript/lib/typescript.js:112873:7)
2023-06-13 20:27:43.485  - error:  host.vm-iobroker Caught by controller[1]:     at  pipelineEmitWithHintWorker  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111243:20)
2023-06-13 20:27:43.485  - error:  host.vm-iobroker Caught by controller[1]:     at pipelineEmitWithHint  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
2023-06-13 20:27:43.485  - error:  host.vm-iobroker Caught by controller[1]:     at  pipelineEmitWithComments  (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7)
2023-06-13 20:27:43.486  - error:  host.vm-iobroker Caught by controller[1]:     at pipelineEmit  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
2023-06-13 20:27:43.486  - error: host.vm-iobroker Caught by controller[1]:     at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7)
2023-06-13 20:27:43.486  - error:  host.vm-iobroker Caught by controller[1]:     at  emitListItemWithParenthesizerRule  (/opt/iobroker/node_modules/typescript/lib/typescript.js:115291:5)
2023-06-13 20:27:43.486  - error:  host.vm-iobroker Caught by controller[1]:     at emitNodeListItems  (/opt/iobroker/node_modules/typescript/lib/typescript.js:114002:9)
2023-06-13 20:27:43.486  - error:  host.vm-iobroker Caught by controller[1]:     at emitNodeList  (/opt/iobroker/node_modules/typescript/lib/typescript.js:113941:9)
2023-06-13 20:27:43.486  - error: host.vm-iobroker Caught by controller[1]:     at emitList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113899:7)
2023-06-13 20:27:43.487  - error:  host.vm-iobroker Caught by controller[1]:     at emitBlockStatements  (/opt/iobroker/node_modules/typescript/lib/typescript.js:112494:7)
2023-06-13 20:27:43.487  - error:  host.vm-iobroker Caught by controller[1]:     at emitModuleBlock  (/opt/iobroker/node_modules/typescript/lib/typescript.js:112989:7)
2023-06-13 20:27:43.487  - error:  host.vm-iobroker Caught by controller[1]:     at  pipelineEmitWithHintWorker  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111253:20)
2023-06-13 20:27:43.487  - error:  host.vm-iobroker Caught by controller[1]:     at pipelineEmitWithHint  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
2023-06-13 20:27:43.487  - error:  host.vm-iobroker Caught by controller[1]:     at  pipelineEmitWithComments  (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7)
2023-06-13 20:27:43.487  - error:  host.vm-iobroker Caught by controller[1]:     at pipelineEmit  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
2023-06-13 20:27:43.487  - error: host.vm-iobroker Caught by controller[1]:     at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7)
2023-06-13 20:27:43.487  - error:  host.vm-iobroker Caught by controller[1]:     at emitModuleDeclaration  (/opt/iobroker/node_modules/typescript/lib/typescript.js:112984:7)
2023-06-13 20:27:43.488  - error:  host.vm-iobroker Caught by controller[1]:     at  pipelineEmitWithHintWorker  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111251:20)
2023-06-13 20:27:43.488  - error:  host.vm-iobroker Caught by controller[1]:     at pipelineEmitWithHint  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
2023-06-13 20:27:43.489  - error:  host.vm-iobroker Caught by controller[1]:     at  pipelineEmitWithComments  (/opt/iobroker/node_modules/typescript/lib/typescript.js:114845:7)
2023-06-13 20:27:43.489  - error:  host.vm-iobroker Caught by controller[1]:     at pipelineEmit  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
2023-06-13 20:27:43.489  - error: host.vm-iobroker Caught by controller[1]:     at emit (/opt/iobroker/node_modules/typescript/lib/typescript.js:110978:7)
2023-06-13 20:27:43.489  - error:  host.vm-iobroker Caught by controller[1]:     at  emitListItemWithParenthesizerRule  (/opt/iobroker/node_modules/typescript/lib/typescript.js:115291:5)
2023-06-13 20:27:43.489  - error:  host.vm-iobroker Caught by controller[1]:     at emitNodeListItems  (/opt/iobroker/node_modules/typescript/lib/typescript.js:114002:9)
2023-06-13 20:27:43.489  - error:  host.vm-iobroker Caught by controller[1]:     at emitNodeList  (/opt/iobroker/node_modules/typescript/lib/typescript.js:113941:9)
2023-06-13 20:27:43.490  - error: host.vm-iobroker Caught by controller[1]:     at emitList (/opt/iobroker/node_modules/typescript/lib/typescript.js:113899:7)
2023-06-13 20:27:43.490  - error:  host.vm-iobroker Caught by controller[1]:     at emitSourceFileWorker  (/opt/iobroker/node_modules/typescript/lib/typescript.js:113579:7)
2023-06-13 20:27:43.490  - error:  host.vm-iobroker Caught by controller[1]:     at  emitBodyWithDetachedComments  (/opt/iobroker/node_modules/typescript/lib/typescript.js:114951:9)
2023-06-13 20:27:43.490  - error:  host.vm-iobroker Caught by controller[1]:     at emitSourceFile  (/opt/iobroker/node_modules/typescript/lib/typescript.js:113507:9)
2023-06-13 20:27:43.490  - error:  host.vm-iobroker Caught by controller[1]:     at  pipelineEmitWithHintWorker  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111074:16)
2023-06-13 20:27:43.491  - error:  host.vm-iobroker Caught by controller[1]:     at pipelineEmitWithHint  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111061:9)
2023-06-13 20:27:43.491  - error:  host.vm-iobroker Caught by controller[1]:     at pipelineEmit  (/opt/iobroker/node_modules/typescript/lib/typescript.js:111010:7)
2023-06-13 20:27:43.491  - error: host.vm-iobroker Caught by controller[1]:     at print (/opt/iobroker/node_modules/typescript/lib/typescript.js:110923:7)
2023-06-13 20:27:43.491  - error: host.vm-iobroker Caught by controller[1]:     at writeFile2 (/opt/iobroker/node_modules/typescript/lib/typescript.js:110907:7)
2023-06-13 20:27:43.491  - error: host.vm-iobroker Caught by controller[1]:     at printFile (/opt/iobroker/node_modules/typescript/lib/typescript.js:110747:7)
2023-06-13 20:27:43.492  - error:  host.vm-iobroker Caught by controller[1]:     at Object.printNode  (/opt/iobroker/node_modules/typescript/lib/typescript.js:110724:18)
2023-06-13 20:27:43.492  - error:  host.vm-iobroker Caught by controller[1]:     at  transformGlobalDeclarations  (/opt/iobroker/node_modules/iobroker.javascript/lib/typescriptTools.js:501:31)
2023-06-13 20:27:43.492  - error: host.vm-iobroker Caught by controller[1]:     at Immediate. (/opt/iobroker/node_modules/iobroker.javascript/main.js:1168:64)
2023-06-13 20:27:43.492  - error: host.vm-iobroker Caught by controller[1]:     at processImmediate (node:internal/timers:478:21)
2023-06-13 20:27:43.493  - error: host.vm-iobroker instance system.adapter.javascript.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-06-13 20:28:15.975  - info:  javascript.0 (1136555) starting. Version 7.1.0 in  /opt/iobroker/node_modules/iobroker.javascript, node: v18.16.0,  js-controller: 4.0.24`

**Comment by cy-fre** [comment]
Bei mir tritt dasselbe Problem mit javascript@7.1.0 auf: 
`error: javascript.0 (...) Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.`

Da ich von gleichzeitig von javascript 7.0.3 auf 7.1.0 und von js-controller 4.0.24 auf 5.0.3 upgedatet habe und der js-controler 5.0.3 beta ist, hatte ich gedacht, dass es am js-controller liegt. Dem ist aber nicht so. Der Fehler tritt auch mit js-controller 4.0.24 auf und sowohl mit node-js 16 als auch mit node-js 18.

Ein Downgrade auf 7.0.3 behebt das Problem wieder.

**Comment by fre4242** [comment]
Bei mir tritt dasselbe Problem mit javascript@7.1.0 auf:
error: javascript.0 (...) Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.

Da ich von gleichzeitig von javascript 7.0.3 auf 7.1.0 und von js-controller 4.0.24 auf 5.0.3 upgedatet habe und der js-controler 5.0.3 beta ist, hatte ich gedacht, dass es am js-controller liegt. Dem ist aber nicht so. Der Fehler tritt auch mit js-controller 4.0.24 auf und sowohl mit node-js 16 als auch mit node-js 18.

Ein Downgrade auf 7.0.3 behebt das Problem wieder.

**Comment by fzoellne** [comment]
Bei mir ab 7.0.4 aufwärts die gleichen Fehlermeldungen wie bei Euch...
js-controller 5.0.5, 6pm 9.5.1, nodes 18.16.0.

**Comment by DocGame69** [comment]
Bei mir genaue die gleichen Meldungen wie bei @JohGrei 
Mittlerweile sind die letzten Tage so viele Updates gekommen (bei mit war die 7.0.3 die lief....alles darüber geht nicht mehr) das die niederste Versionsnummer zum Downgrade die 7.0.4 ist.
Gott sei dank habe ich noch ein Snapshot mit der 7.0.3.
Ist schon Bekannt wo das Problem liegt?
Node.js: v18.16.0
NPM: 9.5.1
js-controller:  5.0.1-alpha.0-20230403-fd495c2e
admin: 6.5.7

**Comment by klein0r** [comment]
Maybe a duplicate of #1335 (same error message)

**Comment by klein0r** [comment]
Please test with >= 7.1.4

**Comment by Scotty-89** [comment]
scheint damit wieder zu gehen.
werde es die Tage unter Beobachtung halten.

VIELEN DANK!

**Comment by fzoellne** [comment]
Hi,

läuft, super und vielen Dank

Frank


Von: Matthias Kleine ***@***.***>
Gesendet: Samstag, 12. August 2023 09:36
An: ioBroker/ioBroker.javascript ***@***.***>
Cc: Zoellner, Frank ***@***.***>; Comment ***@***.***>
Betreff: Re: [ioBroker/ioBroker.javascript] JS 7.0.8 UNCAUGHT_EXCEPTION (Issue #1336)


Please test with >= 7.1.4
