### ISSUE TITLE
Zur Info - bitte einmal die Warn Meldungen ansehen - ggf. was wichtiges?

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.javascript#1466]
Kann jemand etwas mit diesen Meldungen anfangen? Ich sehe bei mir aktuell keine Probleme das irgend etwas nicht (vielleicht bis jetzt unbemerkt) funktioniert. Vielleicht sind die Meldungen wichtig oder ein "Vorbote" von irgend etwas ?!?! Wollte es hier einfach nur mal posten.

Node: 18.18.2
NPM: 9.8.1
Admin: 6.13.3
jscontroller: 5.0.17

```

javascript.0
3872	2023-12-23 08:07:26.175	warn	at Immediate._onImmediate (C:\ioBroker\GLT\node_modules\@iobroker\js-controller-adapter\src\lib\adapter\adapter.ts:11229:62)

javascript.0
3872	2023-12-23 08:07:26.175	warn	at Object.stateChange (C:\ioBroker\GLT\node_modules\iobroker.javascript\main.js:641:29)

javascript.0
3872	2023-12-23 08:07:26.175	warn	at processImmediate (node:internal/timers:476:21)

javascript.0
3872	2023-12-23 08:07:26.174	warn	at Object.callback (C:\ioBroker\GLT\node_modules\iobroker.javascript\lib\sandbox.js:1266:38)
```

**Comment by Apollon77** [comment]
Please provide more log. This error seems incomplete

**Comment by klein0r** [comment]
> Kann jemand etwas mit diesen Meldungen anfangen?

Nein, weil das nicht das komplette Log ist
