### ISSUE TITLE
Version v7.6.3 introduced uncaught exception

### ISSUE THREAD

**Issue by seb2010** [ioBroker/ioBroker.javascript#1482]
**Describe the bug**  
After upgrading to v7.6.3 3 of 4 Javascript instances crash with the following error:
2024-01-13 10:11:59.220  - info: host.sjserver01 instance system.adapter.javascript.1 started with pid 246024
2024-01-13 10:11:59.328  - error: host.sjserver01 Caught by controller[0]: /opt/iobroker/node_modules/iobroker.javascript/node_modules/tough-cookie/lib/cookie.js:1144
2024-01-13 10:11:59.328  - error: host.sjserver01 Caught by controller[0]:     //   The cookie's host-only-flag is false and the cano
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:                                                           
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]: SyntaxError: Unexpected end of input
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at internalCompileFunction (node:internal/vm:73:18)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at wrapSafe (node:internal/modules/cjs/loader:1274:20)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1320:27)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:1013:12)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1225:19)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at require (node:internal/modules/helpers:177:18)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/lib/cookies.js:3:13)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:1013:12)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1225:19)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at require (node:internal/modules/helpers:177:18)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/index.js:18:15)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:1013:12)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1225:19)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at require (node:internal/modules/helpers:177:18)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/lib/request.js:5:18)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:1013:12)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1225:19)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at require (node:internal/modules/helpers:177:18)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/main.js:44:23)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:1013:12)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]:     at node:internal/main/run_main_module:28:49
2024-01-13 10:11:59.329  - error: host.sjserver01 Caught by controller[0]: Node.js v18.19.0
2024-01-13 10:11:59.329  - error: host.sjserver01 instance system.adapter.javascript.1 terminated with code 1 (JS_CONTROLLER_STOPPED)

**To Reproduce**  
1. Update from v7.6.2 to v7.6.3
2. Have instances crash. The detailed circumstances are unknown. The adapter starts and crashes before installing any necessary modules.

**Expected behavior**  
Smooth startup and installation of additional modules

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: 7.6.3
 - JS-Controller version: 5.0.17
 - Node version: v18.19.0
 - Operating system: debian bookworm

**Comment by Apollon77** [comment]
Hm ... also der Fehler sieht für mich eher aus als ob das angegebene File kaputt gegangen ist.
Datei und Zeile stehen am anfang

SD Karte? Filesystem fehler?

**Comment by seb2010** [comment]
Hi. Das ist ein recht neues System (Dez 23) mit SSD.
BTW: wenn ich die Instanz 0 starte, funktioniert es...
Wie kann ich denn die Datei "erneuern"?

**Comment by Apollon77** [comment]
Auch die Zeile 1144 und folgende sind ok? :-)

AM besten  javascript stoppen, alle instanzen. Dann "rm - rf /opt/iobroker/node_modules/iobroker.javascript/node_modules/tough-cookie" und dann neu starten ... das SOLLTE das neu installieren

**Comment by seb2010** [comment]
Ich habe letztendlich alle node_modules gelöscht und danach den Adapter nochmal geupdated. Der neue Aufbau der MOdules scheint es gebracht zu haben. Merci!
