### ISSUE TITLE
Adapter crashes if script has an error that is not immediately invoked from user code

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#160]
Example:
https://forum.iobroker.net/viewtopic.php?f=22&t=15700&p=165320#p165320

**Comment by AlCalzone** [comment]
Repro:
```js
// Filename: test.js
const vm = require("vm");
try {
	vm.runInNewContext(
		`setTimeout(() => { throw new Error("boo!") }, 1000);`,
		{
			setTimeout,
		}, {filename: "script.js.global.foo"}
	);
} catch (e) {
	console.log("Hah, caught one!");
	console.dir(e);
}

setInterval(() => console.log("okay!"), 500);
setTimeout(() => process.exit(0), 3000);
```
Running this with `node test.js` leads to a crash:
```
okay!
script.js.global.foo:1
setTimeout(() => { throw new Error("boo!") }, 1000);
                   ^

Error: boo!
    at Timeout.setTimeout [as _onTimeout] (script.js.global.foo:1:26)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
```
