### ISSUE TITLE
[Bug]: Cannot calculate astro date

### ISSUE THREAD

**Issue by LMey** [ioBroker/ioBroker.javascript#1600]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Cannot calculate astro date "nightEnd" for my location and when I try to load the overview the loading bar runs into a loop and the javascript adapter crashes. 

![Bildschirmfoto 2024-06-09 um 16 47 26](https://github.com/ioBroker/ioBroker.javascript/assets/34010056/6fe54cb9-7a42-4a10-babe-9d4c9102ecd5)

javascript.0	17:09:24.165	info	Stopping script script.js.Skript_1
javascript.0	17:09:27.701	info	Start JavaScript script.js.Skript_1 (Javascript/js)
javascript.0	17:09:27.709	info	script.js.Skript_1: =====================
javascript.0	17:09:27.709	info	script.js.Skript_1: Astro Werte für heute
javascript.0	17:09:27.709	info	script.js.Skript_1: =====================
javascript.0	17:09:27.709	warn	script.js.Skript_1: Cannot calculate astro date "nightEnd" for 51.812, 9.188
javascript.0	17:09:27.710	info	script.js.Skript_1: (0) nightEnd (Ende der Nacht)........................: Invalid Date
javascript.0	17:09:27.710	info	script.js.Skript_1: (1) nauticalDawn (naut. Dämmerung Morgens)...........: 3:05:18 AM
javascript.0	17:09:27.710	info	script.js.Skript_1: (2) dawn (Dämmerung Morgens).........................: 4:19:00 AM
javascript.0	17:09:27.710	info	script.js.Skript_1: (3) sunrise (Sonnenaufgang)..........................: 5:06:35 AM
javascript.0	17:09:27.710	info	script.js.Skript_1: (4) sunriseEnd (Ende des Sonnenaufgangs).............: 5:11:05 AM
javascript.0	17:09:27.710	info	script.js.Skript_1: (5) goldenHourEnd (Ende der Golden Hour VM)..........: 6:00:47 AM
javascript.0	17:09:27.710	info	script.js.Skript_1: (6) solarNoon (Mittag)...............................: 1:23:57 PM
javascript.0	17:09:27.710	info	script.js.Skript_1: (7) goldenHour (Start der Golden Hour NM)............: 8:47:07 PM
javascript.0	17:09:27.710	info	script.js.Skript_1: (8) sunsetStart (Start des Sonnenuntergangs).........: 9:36:48 PM
javascript.0	17:09:27.710	info	script.js.Skript_1: (9) sunset (Sonnenuntergang).........................: 9:41:19 PM
javascript.0	17:09:27.710	info	script.js.Skript_1: (10) dusk (Dämmerung Abends)..........................: 10:28:54 PM
javascript.0	17:09:27.710	info	script.js.Skript_1: (11) nauticalDusk (naut. Dämmerung Abends)............: 11:42:36 PM
javascript.0	17:09:27.710	warn	script.js.Skript_1: Cannot calculate astro date "night" for 51.812, 9.188
javascript.0	17:09:27.711	info	script.js.Skript_1: (12) night (Start der Nacht)..........................: Invalid Date
javascript.0	17:09:27.711	info	script.js.Skript_1: (13) nadir (Mitternacht)..............................: 1:23:57 AM
javascript.0	17:09:27.711	info	script.js.Skript_1: =====================
javascript.0	17:09:27.711	warn	script.js.Skript_1: Cannot calculate astro date "night" for 51.812, 9.188
javascript.0	17:09:27.711	info	script.js.Skript_1: Night starts tomorrow at Invalid Date
javascript.0	17:09:27.711	info	script.js.Skript_1: registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions

### iobroker.current.log (in debug mode!)

2024-06-09 17:00:00.020 - info: host.iobroker instance system.adapter.dwd.0 started with pid 6754
2024-06-09 17:00:00.617 - info: dwd.0 (6754) starting. Version 2.8.5 in /opt/iobroker/node_modules/iobroker.dwd, node: v18.20.3, js-controller: 5.0.19
2024-06-09 17:00:01.197 - info: dwd.0 (6754) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2024-06-09 17:00:01.710 - info: host.iobroker instance system.adapter.dwd.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2024-06-09 17:00:04.030 - info: host.iobroker instance system.adapter.daswetter.0 started with pid 6769
2024-06-09 17:00:04.604 - info: daswetter.0 (6769) starting. Version 3.1.13 in /opt/iobroker/node_modules/iobroker.daswetter, node: v18.20.3, js-controller: 5.0.19
2024-06-09 17:00:04.847 - info: daswetter.0 (6769) Terminated (ADAPTER_REQUESTED_TERMINATION): All data handled, adapter stopped until next scheduled moment
2024-06-09 17:00:05.353 - info: daswetter.0 (6769) cleaned everything up...
2024-06-09 17:00:05.361 - info: host.iobroker instance system.adapter.daswetter.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2024-06-09 17:00:08.039 - info: host.iobroker instance system.adapter.ical.0 started with pid 6784
2024-06-09 17:00:08.652 - info: ical.0 (6784) starting. Version 1.15.0 in /opt/iobroker/node_modules/iobroker.ical, node: v18.20.3, js-controller: 5.0.19
2024-06-09 17:00:08.942 - info: ical.0 (6784) processing URL: Abfalltermine 2024 https://calendar.google.com/calendar/ical/674a12fb1135d68c8731b44e7ce2e4790f21118098ab252ccc30c8726671dc0f%40group.calendar.google.com/private-812b5cfa0935a36ae21d4ac5cab6c86c/basic.ics
2024-06-09 17:00:13.971 - info: ical.0 (6784) Terminated (NO_ERROR): Without reason
2024-06-09 17:00:14.483 - info: host.iobroker instance system.adapter.ical.0 terminated with code 0 (NO_ERROR)
2024-06-09 17:01:00.005 - warn: javascript.0 (6723) script.js.Sent_date-time_to_knx: Cannot calculate astro date "night" for 51.8124766, 9.188491
2024-06-09 17:01:00.005 - warn: javascript.0 (6723) script.js.Sent_date-time_to_knx: missing or unrecognized endTime expression: NaN
2024-06-09 17:01:00.005 - warn: javascript.0 (6723) script.js.Sent_date-time_to_knx: Cannot calculate astro date "night" for 51.8124766, 9.188491
2024-06-09 17:02:00.003 - warn: javascript.0 (6723) script.js.Sent_date-time_to_knx: Cannot calculate astro date "night" for 51.8124766, 9.188491
2024-06-09 17:02:00.003 - warn: javascript.0 (6723) script.js.Sent_date-time_to_knx: missing or unrecognized endTime expression: NaN
2024-06-09 17:02:00.003 - warn: javascript.0 (6723) script.js.Sent_date-time_to_knx: Cannot calculate astro date "night" for 51.8124766, 9.188491
2024-06-09 17:02:40.186 - info: host.iobroker stopInstance system.adapter.admin.0 (force=false, process=true)
2024-06-09 17:02:40.187 - info: admin.0 (612) Got terminate signal TERMINATE_YOURSELF
2024-06-09 17:02:40.188 - info: admin.0 (612) terminating http server on port 8081
2024-06-09 17:02:40.190 - info: admin.0 (612) terminating
2024-06-09 17:02:40.190 - info: admin.0 (612) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2024-06-09 17:02:40.228 - info: host.iobroker stopInstance system.adapter.admin.0 send kill signal
2024-06-09 17:02:40.691 - info: admin.0 (612) terminating
2024-06-09 17:02:40.720 - info: host.iobroker instance system.adapter.admin.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2024-06-09 17:02:43.245 - info: host.iobroker instance system.adapter.admin.0 started with pid 6799
2024-06-09 17:02:43.989 - info: admin.0 (6799) starting. Version 6.13.16 in /opt/iobroker/node_modules/iobroker.admin, node: v18.20.3, js-controller: 5.0.19
2024-06-09 17:02:44.002 - info: admin.0 (6799) requesting all objects
2024-06-09 17:02:44.262 - info: admin.0 (6799) received all objects
2024-06-09 17:02:44.399 - info: admin.0 (6799) socket.io server listening on port 8081
2024-06-09 17:02:44.404 - info: admin.0 (6799) http server listening on port 8081
2024-06-09 17:02:44.404 - info: admin.0 (6799) Use link "http://127.0.0.1:8081" to configure.
2024-06-09 17:02:47.063 - info: admin.0 (6799) ==> Connected system.user.admin from ::ffff:192.168.178.28
2024-06-09 17:02:59.154 - info: host.iobroker stopInstance system.adapter.javascript.0 (force=false, process=true)
2024-06-09 17:02:59.156 - info: javascript.0 (6723) Got terminate signal TERMINATE_YOURSELF
2024-06-09 17:02:59.157 - info: javascript.0 (6723) Stopping script script.js.Müll_Notification
2024-06-09 17:02:59.158 - info: javascript.0 (6723) Stopping script script.js.Sent_date-time_to_knx
2024-06-09 17:02:59.158 - info: javascript.0 (6723) Stopping script script.js.DWD_Warning_Notification
2024-06-09 17:02:59.159 - info: javascript.0 (6723) terminating
2024-06-09 17:02:59.160 - info: javascript.0 (6723) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2024-06-09 17:02:59.196 - info: host.iobroker stopInstance system.adapter.javascript.0 send kill signal
2024-06-09 17:02:59.657 - info: javascript.0 (6723) terminating
2024-06-09 17:02:59.682 - info: host.iobroker instance system.adapter.javascript.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2024-06-09 17:03:02.215 - info: host.iobroker instance system.adapter.javascript.0 started with pid 6814
2024-06-09 17:03:03.059 - info: javascript.0 (6814) starting. Version 8.3.1 in /opt/iobroker/node_modules/iobroker.javascript, node: v18.20.3, js-controller: 5.0.19
2024-06-09 17:03:03.153 - info: javascript.0 (6814) requesting all states
2024-06-09 17:03:03.154 - info: javascript.0 (6814) requesting all objects
2024-06-09 17:03:03.315 - info: javascript.0 (6814) received all objects
2024-06-09 17:03:03.322 - info: javascript.0 (6814) received all states
2024-06-09 17:03:03.383 - info: javascript.0 (6814) Start JavaScript script.js.Müll_Notification (Blockly)
2024-06-09 17:03:03.403 - info: javascript.0 (6814) script.js.Müll_Notification: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions
2024-06-09 17:03:03.403 - info: javascript.0 (6814) Start JavaScript script.js.Sent_date-time_to_knx (Blockly)
2024-06-09 17:03:03.439 - info: javascript.0 (6814) script.js.Sent_date-time_to_knx: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions
2024-06-09 17:03:03.440 - info: javascript.0 (6814) Start JavaScript script.js.DWD_Warning_Notification (Blockly)
2024-06-09 17:03:03.442 - info: javascript.0 (6814) script.js.DWD_Warning_Notification: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions
2024-06-09 17:03:17.837 - info: host.iobroker stopInstance system.adapter.javascript.0 (force=false, process=true)
2024-06-09 17:03:17.838 - info: javascript.0 (6814) Got terminate signal TERMINATE_YOURSELF
2024-06-09 17:03:17.840 - info: javascript.0 (6814) Stopping script script.js.Müll_Notification
2024-06-09 17:03:17.840 - info: javascript.0 (6814) Stopping script script.js.Sent_date-time_to_knx
2024-06-09 17:03:17.840 - info: javascript.0 (6814) Stopping script script.js.DWD_Warning_Notification
2024-06-09 17:03:17.841 - info: javascript.0 (6814) terminating
2024-06-09 17:03:17.842 - info: javascript.0 (6814) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2024-06-09 17:03:17.880 - info: host.iobroker stopInstance system.adapter.javascript.0 send kill signal
2024-06-09 17:03:18.340 - info: javascript.0 (6814) terminating
2024-06-09 17:03:18.366 - info: host.iobroker instance system.adapter.javascript.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2024-06-09 17:03:20.896 - info: host.iobroker instance system.adapter.javascript.0 started with pid 6829
2024-06-09 17:03:21.532 - debug: javascript.0 (6829) Redis Objects: Use Redis connection: 127.0.0.1:9001
2024-06-09 17:03:21.545 - debug: javascript.0 (6829) Objects client ready ... initialize now
2024-06-09 17:03:21.546 - debug: javascript.0 (6829) Objects create System PubSub Client
2024-06-09 17:03:21.546 - debug: javascript.0 (6829) Objects create User PubSub Client
2024-06-09 17:03:21.551 - debug: javascript.0 (6829) Objects client initialize lua scripts
2024-06-09 17:03:21.554 - debug: javascript.0 (6829) Objects connected to redis: 127.0.0.1:9001
2024-06-09 17:03:21.562 - debug: javascript.0 (6829) Redis States: Use Redis connection: 127.0.0.1:9000
2024-06-09 17:03:21.564 - debug: javascript.0 (6829) States create System PubSub Client
2024-06-09 17:03:21.564 - debug: javascript.0 (6829) States create User PubSub Client
2024-06-09 17:03:21.567 - debug: javascript.0 (6829) States connected to redis: 127.0.0.1:9000
2024-06-09 17:03:21.576 - debug: javascript.0 (6829) Plugin sentry Initialize Plugin (enabled=true)
2024-06-09 17:03:21.699 - info: javascript.0 (6829) starting. Version 8.3.1 in /opt/iobroker/node_modules/iobroker.javascript, node: v18.20.3, js-controller: 5.0.19
2024-06-09 17:03:21.709 - debug: javascript.0 (6829) config.subscribe (Do not subscribe all states on start): false
2024-06-09 17:03:21.721 - debug: javascript.0 (6829) Loaded TypeScript definitions for node: ["node_modules/@types/node/package.json","node_modules/@types/node/index.d.ts","node_modules/@types/node/assert.d.ts","node_modules/@types/node/assert/strict.d.ts","node_modules/@types/node/globals.d.ts","node_modules/@types/node/async_hooks.d.ts","node_modules/@types/node/buffer.d.ts","node_modules/@types/node/child_process.d.ts","node_modules/@types/node/cluster.d.ts","node_modules/@types/node/console.d.ts","node_modules/@types/node/constants.d.ts","node_modules/@types/node/crypto.d.ts","node_modules/@types/node/dgram.d.ts","node_modules/@types/node/diagnostics_channel.d.ts","node_modules/@types/node/dns.d.ts","node_modules/@types/node/dns/promises.d.ts","node_modules/@types/node/domain.d.ts","node_modules/@types/node/dom-events.d.ts","node_modules/@types/node/events.d.ts","node_modules/@types/node/fs.d.ts","node_modules/@types/node/fs/promises.d.ts","node_modules/@types/node/http.d.ts","node_modules/@types/node/http2.d.ts","node_modules/@types/node/https.d.ts","node_modules/@types/node/inspector.d.ts","node_modules/@types/node/module.d.ts","node_modules/@types/node/net.d.ts","node_modules/@types/node/os.d.ts","node_modules/@types/node/path.d.ts","node_modules/@types/node/perf_hooks.d.ts","node_modules/@types/node/process.d.ts","node_modules/@types/node/punycode.d.ts","node_modules/@types/node/querystring.d.ts","node_modules/@types/node/readline.d.ts","node_modules/@types/node/readline/promises.d.ts","node_modules/@types/node/repl.d.ts","node_modules/@types/node/sea.d.ts","node_modules/@types/node/stream.d.ts","node_modules/@types/node/stream/promises.d.ts","node_modules/@types/node/stream/consumers.d.ts","node_modules/@types/node/stream/web.d.ts","node_modules/@types/node/string_decoder.d.ts","node_modules/@types/node/test.d.ts","node_modules/@types/node/timers.d.ts","node_modules/@types/node/timers/promises.d.ts","node_modules/@types/node/tls.d.ts","node_modules/@types/node/trace_events.d.ts","node_modules/@types/node/tty.d.ts","node_modules/@types/node/url.d.ts","node_modules/@types/node/util.d.ts","node_modules/@types/node/v8.d.ts","node_modules/@types/node/vm.d.ts","node_modules/@types/node/wasi.d.ts","node_modules/@types/node/worker_threads.d.ts","node_modules/@types/node/zlib.d.ts","node_modules/@types/node/globals.global.d.ts"]
2024-06-09 17:03:21.726 - debug: javascript.0 (6829) Loaded TypeScript definitions for request: ["node_modules/@types/request/package.json","node_modules/@types/request/index.d.ts"]
2024-06-09 17:03:21.794 - info: javascript.0 (6829) requesting all states
2024-06-09 17:03:21.794 - info: javascript.0 (6829) requesting all objects
2024-06-09 17:03:21.948 - info: javascript.0 (6829) received all objects
2024-06-09 17:03:21.956 - info: javascript.0 (6829) received all states
2024-06-09 17:03:22.010 - info: javascript.0 (6829) Start JavaScript script.js.Müll_Notification (Blockly)
2024-06-09 17:03:22.031 - info: javascript.0 (6829) script.js.Müll_Notification: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions
2024-06-09 17:03:22.031 - info: javascript.0 (6829) Start JavaScript script.js.Sent_date-time_to_knx (Blockly)
2024-06-09 17:03:22.060 - info: javascript.0 (6829) script.js.Sent_date-time_to_knx: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions
2024-06-09 17:03:22.062 - info: javascript.0 (6829) Start JavaScript script.js.DWD_Warning_Notification (Blockly)
2024-06-09 17:03:22.064 - info: javascript.0 (6829) script.js.DWD_Warning_Notification: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions
2024-06-09 17:03:42.304 - info: admin.0 (6799) ==> Connected system.user.admin from ::ffff:192.168.178.28
2024-06-09 17:04:00.006 - warn: javascript.0 (6829) script.js.Sent_date-time_to_knx: Cannot calculate astro date "night" for 51.812, 9.188
2024-06-09 17:04:00.006 - warn: javascript.0 (6829) script.js.Sent_date-time_to_knx: missing or unrecognized endTime expression: NaN
2024-06-09 17:04:00.006 - warn: javascript.0 (6829) script.js.Sent_date-time_to_knx: Cannot calculate astro date "night" for 51.812, 9.188
2024-06-09 17:04:03.939 - info: admin.0 (6799) <== Disconnect system.user.admin from ::ffff:192.168.178.28 javascript
2024-06-09 17:04:10.235 - info: admin.0 (6799) ==> Connected system.user.admin from ::ffff:192.168.178.28
2024-06-09 17:04:15.727 - error: javascript.0 (6829) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-06-09 17:04:15.727 - error: javascript.0 (6829) unhandled promise rejection: Invalid time value
2024-06-09 17:04:15.727 - error: javascript.0 (6829) RangeError: Invalid time value
at Date.toISOString ()
at /opt/iobroker/node_modules/iobroker.javascript/main.js:817:145
at Array.forEach ()
at Object.message (/opt/iobroker/node_modules/iobroker.javascript/main.js:817:34)
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11112:47)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37)
at processImmediate (node:internal/timers:476:21)
2024-06-09 17:04:15.727 - error: javascript.0 (6829) Invalid time value
2024-06-09 17:04:15.734 - info: javascript.0 (6829) Stopping script script.js.Müll_Notification
2024-06-09 17:04:15.735 - info: javascript.0 (6829) Stopping script script.js.Sent_date-time_to_knx
2024-06-09 17:04:15.735 - info: javascript.0 (6829) Stopping script script.js.DWD_Warning_Notification
2024-06-09 17:04:15.736 - info: javascript.0 (6829) terminating
2024-06-09 17:04:15.736 - debug: javascript.0 (6829) Plugin sentry destroyed
2024-06-09 17:04:15.736 - warn: javascript.0 (6829) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-06-09 17:04:16.235 - info: javascript.0 (6829) terminating
2024-06-09 17:04:16.263 - error: host.iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2024-06-09 17:04:16.263 - error: host.iobroker Caught by controller[0]: RangeError: Invalid time value
2024-06-09 17:04:16.263 - error: host.iobroker Caught by controller[0]: at Date.toISOString ()
2024-06-09 17:04:16.263 - error: host.iobroker Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.javascript/main.js:817:145
2024-06-09 17:04:16.263 - error: host.iobroker Caught by controller[0]: at Array.forEach ()
2024-06-09 17:04:16.263 - error: host.iobroker Caught by controller[0]: at Object.message (/opt/iobroker/node_modules/iobroker.javascript/main.js:817:34)
2024-06-09 17:04:16.263 - error: host.iobroker Caught by controller[0]: at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11112:47)
2024-06-09 17:04:16.263 - error: host.iobroker Caught by controller[0]: at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37)
2024-06-09 17:04:16.263 - error: host.iobroker Caught by controller[0]: at processImmediate (node:internal/timers:476:21)
2024-06-09 17:04:16.263 - error: host.iobroker instance system.adapter.javascript.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-06-09 17:04:16.263 - info: host.iobroker Restart adapter system.adapter.javascript.0 because enabled
2024-06-09 17:04:46.281 - info: host.iobroker instance system.adapter.javascript.0 started with pid 6845
2024-06-09 17:04:46.912 - debug: javascript.0 (6845) Redis Objects: Use Redis connection: 127.0.0.1:9001
2024-06-09 17:04:46.925 - debug: javascript.0 (6845) Objects client ready ... initialize now
2024-06-09 17:04:46.926 - debug: javascript.0 (6845) Objects create System PubSub Client
2024-06-09 17:04:46.926 - debug: javascript.0 (6845) Objects create User PubSub Client
2024-06-09 17:04:46.931 - debug: javascript.0 (6845) Objects client initialize lua scripts
2024-06-09 17:04:46.934 - debug: javascript.0 (6845) Objects connected to redis: 127.0.0.1:9001
2024-06-09 17:04:46.941 - debug: javascript.0 (6845) Redis States: Use Redis connection: 127.0.0.1:9000
2024-06-09 17:04:46.943 - debug: javascript.0 (6845) States create System PubSub Client
2024-06-09 17:04:46.943 - debug: javascript.0 (6845) States create User PubSub Client
2024-06-09 17:04:46.989 - debug: javascript.0 (6845) States connected to redis: 127.0.0.1:9000
2024-06-09 17:04:46.999 - debug: javascript.0 (6845) Plugin sentry Initialize Plugin (enabled=true)
2024-06-09 17:04:47.122 - info: javascript.0 (6845) starting. Version 8.3.1 in /opt/iobroker/node_modules/iobroker.javascript, node: v18.20.3, js-controller: 5.0.19
2024-06-09 17:04:47.132 - debug: javascript.0 (6845) config.subscribe (Do not subscribe all states on start): false
2024-06-09 17:04:47.144 - debug: javascript.0 (6845) Loaded TypeScript definitions for node: ["node_modules/@types/node/package.json","node_modules/@types/node/index.d.ts","node_modules/@types/node/assert.d.ts","node_modules/@types/node/assert/strict.d.ts","node_modules/@types/node/globals.d.ts","node_modules/@types/node/async_hooks.d.ts","node_modules/@types/node/buffer.d.ts","node_modules/@types/node/child_process.d.ts","node_modules/@types/node/cluster.d.ts","node_modules/@types/node/console.d.ts","node_modules/@types/node/constants.d.ts","node_modules/@types/node/crypto.d.ts","node_modules/@types/node/dgram.d.ts","node_modules/@types/node/diagnostics_channel.d.ts","node_modules/@types/node/dns.d.ts","node_modules/@types/node/dns/promises.d.ts","node_modules/@types/node/domain.d.ts","node_modules/@types/node/dom-events.d.ts","node_modules/@types/node/events.d.ts","node_modules/@types/node/fs.d.ts","node_modules/@types/node/fs/promises.d.ts","node_modules/@types/node/http.d.ts","node_modules/@types/node/http2.d.ts","node_modules/@types/node/https.d.ts","node_modules/@types/node/inspector.d.ts","node_modules/@types/node/module.d.ts","node_modules/@types/node/net.d.ts","node_modules/@types/node/os.d.ts","node_modules/@types/node/path.d.ts","node_modules/@types/node/perf_hooks.d.ts","node_modules/@types/node/process.d.ts","node_modules/@types/node/punycode.d.ts","node_modules/@types/node/querystring.d.ts","node_modules/@types/node/readline.d.ts","node_modules/@types/node/readline/promises.d.ts","node_modules/@types/node/repl.d.ts","node_modules/@types/node/sea.d.ts","node_modules/@types/node/stream.d.ts","node_modules/@types/node/stream/promises.d.ts","node_modules/@types/node/stream/consumers.d.ts","node_modules/@types/node/stream/web.d.ts","node_modules/@types/node/string_decoder.d.ts","node_modules/@types/node/test.d.ts","node_modules/@types/node/timers.d.ts","node_modules/@types/node/timers/promises.d.ts","node_modules/@types/node/tls.d.ts","node_modules/@types/node/trace_events.d.ts","node_modules/@types/node/tty.d.ts","node_modules/@types/node/url.d.ts","node_modules/@types/node/util.d.ts","node_modules/@types/node/v8.d.ts","node_modules/@types/node/vm.d.ts","node_modules/@types/node/wasi.d.ts","node_modules/@types/node/worker_threads.d.ts","node_modules/@types/node/zlib.d.ts","node_modules/@types/node/globals.global.d.ts"]
2024-06-09 17:04:47.149 - debug: javascript.0 (6845) Loaded TypeScript definitions for request: ["node_modules/@types/request/package.json","node_modules/@types/request/index.d.ts"]
2024-06-09 17:04:47.222 - info: javascript.0 (6845) requesting all states
2024-06-09 17:04:47.222 - info: javascript.0 (6845) requesting all objects
2024-06-09 17:04:47.390 - info: javascript.0 (6845) received all objects
2024-06-09 17:04:47.397 - info: javascript.0 (6845) received all states
2024-06-09 17:04:47.458 - info: javascript.0 (6845) Start JavaScript script.js.Müll_Notification (Blockly)
2024-06-09 17:04:47.478 - info: javascript.0 (6845) script.js.Müll_Notification: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions
2024-06-09 17:04:47.478 - info: javascript.0 (6845) Start JavaScript script.js.Sent_date-time_to_knx (Blockly)
2024-06-09 17:04:47.504 - info: javascript.0 (6845) script.js.Sent_date-time_to_knx: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions
2024-06-09 17:04:47.506 - info: javascript.0 (6845) Start JavaScript script.js.DWD_Warning_Notification (Blockly)
2024-06-09 17:04:47.515 - info: javascript.0 (6845) script.js.DWD_Warning_Notification: registered 0 subscriptions, 1 schedule, 0 messages, 0 logs and 0 file subscriptions
2024-06-09 17:04:55.327 - info: admin.0 (6799) <== Disconnect system.user.admin from ::ffff:192.168.178.28 javascript
2024-06-09 17:05:00.006 - warn: javascript.0 (6845) script.js.Sent_date-time_to_knx: Cannot calculate astro date "night" for 51.812, 9.188
2024-06-09 17:05:00.006 - warn: javascript.0 (6845) script.js.Sent_date-time_to_knx: missing or unrecognized endTime expression: NaN
2024-06-09 17:05:00.007 - warn: javascript.0 (6845) script.js.Sent_date-time_to_knx: Cannot calculate astro date "night" for 51.812, 9.188
2024-06-09 17:05:00.012 - info: host.iobroker instance system.adapter.dwd.0 started with pid 6860
2024-06-09 17:05:00.599 - info: dwd.0 (6860) starting. Version 2.8.5 in /opt/iobroker/node_modules/iobroker.dwd, node: v18.20.3, js-controller: 5.0.19
2024-06-09 17:05:00.856 - info: dwd.0 (6860) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2024-06-09 17:05:01.371 - info: host.iobroker instance system.adapter.dwd.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)

### Version of nodejs

18.20.3

### Version of ioBroker js-controller

5.0.19

### Version of adapter

Javascript Adapter: 8.3.1

**Comment by LMey** [comment]
some further information: 
I thought the error had occurred after the updates I carried out yesterday, but this is not the case. The older logs show the same information.

I set the coordinates system-wide and shortened them to three digits after the dot in the hope that this would help, but unfortunately not. The “Use System Settings” checkbox is checked in the adapter.

**Comment by LMey** [comment]
And, I found a reference somewhere in an older post to the fact that if you live at the North Pole or something like that, there could be difficulties. 
I live near Paderborn, in the middle of Germany - so I think that can be ruled out.

**Comment by mcm1957** [comment]
nördlich 48,6° gibt es in der hellsten Jahreszeit des Sommer keine Nacht.
Siehe z.B. https://de.wikipedia.org/wiki/D%C3%A4mmerung

**Comment by LMey** [comment]
Ich lache mich kaputt - du scheinst recht zu haben... 
Ok ich stelle das Script um auf "dusk till dawn" und dann sollte es passen?! @mcm1957 danke für den Link, man lernt ja nie aus.

**Comment by klein0r** [comment]
Duplicate of #1580 #1595 #1596

**Comment by klein0r** [comment]
> Javascript Adapter: 8.3.1

Always test with the latest beta before opening new issues. Currently 8.5.0
