### ISSUE TITLE
[Bug]: moment-duration-format generates script error with js-controller 6.x

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.javascript#1613]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

JavaScript

### The problem

With js-controller 6.x, a script with the npm module moment-duration-format generates following error: 
`error: moment.duration(...).format is not a function.`

The npm modules moment and moment-duration-format are installed in the javascript adapter and no errors are output when the adapter is started, only the script itself generates the error in the log. Moment and moment.duration do not generate any errors in the script, the error only occurs with moment.duration.format.

**Sript line:**
`let uptime = (existsState(id + '.uptime')) ? moment.duration(getState(id + '.uptime').val, 'seconds').format("D[T] H[h] m[m]", 0) : '-'; `

The same script works normally under js-controller 5.0.19 without any errors.

**Screenshot npm-module javascript adapter:** 

![Screenshot javascript moduls](https://github.com/ioBroker/ioBroker.javascript/assets/56516310/9732a4b8-499e-4eaa-be45-648f1529d6fb)

### iobroker.current.log (in debug mode!)

**Full error log entry of the script:**
`script.js.MD.MD_AdapterStatus_TEST: [adapterStatus] error:moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at adapterStatus (script.js.MD.MD_AdapterStatus_TEST:248:115) at script.js.MD.MD_AdapterStatus_TEST:561:1 at script.js.MD.MD_AdapterStatus_TEST:711:3 at Script.runInContext (node:vm:148:12) at Script.runInNewContext (node:vm:153:17) at execute (/opt/iobroker/node_modules/iobroker.javascript/main.js:1968:23) at prepareScript (/opt/iobroker/node_modules/iobroker.javascript/main.js:2215:13) at /opt/iobroker/node_modules/iobroker.javascript/main.js:2307:17 at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/main.js:1722:17) at processImmediate (node:internal/timers:480:21)
`

### Version of nodejs

20.14.0

### Version of ioBroker js-controller

6.0.4

### Version of adapter

8.6.0

**Comment by klein0r** [comment]
Looks like moment has no default export

Suggestions @foxriver76  ?

**Comment by foxriver76** [comment]
https://www.npmjs.com/package/moment-duration-format#module
This works correct, controller v6.0.5, js adapter 8.6.0 

![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/25484431/f86605a7-e33c-4196-99f6-616c9c586f10)

So maybe normally it had some side effects automatically which now need to be configured explicitly but for this we would need to see your code @MK-66

**Comment by foxriver76** [comment]
This also works
```
console.log(moment.duration(123, "minutes").format("h:mm"));
```
So maybe you just need `momentDurationFormatSetup(moment);` after the imports.

**Comment by MK-66** [comment]
@foxriver76, @klein0r 
The line momentDurationFormatSetup(moment); is obviously exactly the right one that was missing in the script.
Unfortunately I'm not a javascript pro, so thanks for the hint.
Issue can then be closed from my point of view, should I close the issue then?

**Comment by foxriver76** [comment]
If this happens to a lot of users we will think about adding a short news on how to fix it, please leave it open until we close it.

**Comment by klein0r** [comment]
> please leave it open

sorry 😄

**Comment by agross** [comment]
Probably related: #1642

**Comment by zechnerhubert** [comment]
Hallo! Ich habe das selbe Problem nach dem Update! Betrifft bei mir sehr viele Scripte, welche eigentlich alle mit Blockly ausgeführt werden. Ein Auszug meiner Fehlermeldungen:

`<html>
<body>

javascript.0 | 2024-08-31 18:31:00.107 | error | script.js.common.Homeautomatik.Abends_weg: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Abends_weg:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
-- | -- | -- | --
javascript.0 | 2024-08-31 18:31:00.104 | error | script.js.common.Homeautomatik.Energie: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Energie:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.100 | error | script.js.common.Homeautomatik.Flood_71_auswerten: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Flood_71_auswerten:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.094 | error | script.js.common.Homeautomatik.Infomeldungen: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Infomeldungen:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.090 | error | script.js.common.Homeautomatik.Mainswitch: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Mainswitch:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.087 | error | script.js.common.Homeautomatik.PV: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.PV:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.083 | error | script.js.common.Homeautomatik.Poolpumpensteuerung: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Poolpumpensteuerung:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.079 | error | script.js.common.Homeautomatik.Rollo_Info_Telegram: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Rollo_Info_Telegram:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.077 | error | script.js.common.Homeautomatik.Shelly_Buttons: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Shelly_Buttons:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.074 | error | script.js.common.Homeautomatik.Sonne: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Sonne:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.073 | error | script.js.common.Homeautomatik.Stromverbrauch: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Stromverbrauch:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.071 | error | script.js.common.Homeautomatik.Stromverbrauch_HT_NT: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Stromverbrauch_HT_NT:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.069 | error | script.js.common.Homeautomatik.Szene_Abends_weg_: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Szene_Abends_weg_:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.067 | error | script.js.common.Homeautomatik.Taster_Wohnzimmer_LED: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Taster_Wohnzimmer_LED:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)
javascript.0 | 2024-08-31 18:31:00.065 | error | script.js.common.Homeautomatik.Telegram_Energie: [adapterStatus] error: moment.duration(...).format is not a function, stack: TypeError: moment.duration(...).format is not a function at Object.adapterStatus (script.js.common.Homeautomatik.Telegram_Energie:216:115) at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1876:34) at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/Job.js:171:15) at /opt/iobroker/node_modules/node-schedule/lib/Invocation.js:268:28 at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/Invocation.js:228:7) at listOnTimeout (node:internal/timers:581:17) at processTimers (node:internal/timers:519:7)


</body>
</html>`

Wie ist hier die Lösung?
