### ISSUE TITLE
Version 4.0 - path is not defined

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.javascript#196]
Installed 4.0 + Upload:
Error on launch of instance:

Nodejs: 8.12

```

2018-11-22 12:57:05.574  - error: Caught by controller[0]: /opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:3
--
2018-11-22 12:57:05.575  - error: Caught by controller[0]: const path = require(path);
2018-11-22 12:57:05.576  - error: Caught by controller[0]:                      ^
2018-11-22 12:57:05.576  - error: Caught by controller[0]: ReferenceError: path is not defined
2018-11-22 12:57:05.577  - error: Caught by controller[0]:     at Object. (/opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:3:22)
2018-11-22 12:57:05.577  - error: Caught by controller[0]:     at Module._compile (module.js:653:30)
2018-11-22 12:57:05.577  - error: Caught by controller[0]:     at Object.Module._extensions..js (module.js:664:10)
2018-11-22 12:57:05.578  - error: Caught by controller[0]:     at Module.load (module.js:566:32)
2018-11-22 12:57:05.578  - error: Caught by controller[0]:     at tryModuleLoad (module.js:506:12)
2018-11-22 12:57:05.579  - error: Caught by controller[0]:     at Function.Module._load (module.js:498:3)
2018-11-22 12:57:05.579  - error: Caught by controller[0]:     at Module.require (module.js:597:17)
2018-11-22 12:57:05.579  - error: Caught by controller[0]:     at require (internal/module.js:11:18)
2018-11-22 12:57:05.580  - error: Caught by controller[0]:     at Object. (/opt/iobroker/node_modules/iobroker.javascript/main.js:26:24)
2018-11-22 12:57:05.580  - error: Caught by controller[0]:     at Module._compile (module.js:653:30)
2018-11-22 12:57:05.580  - error: Caught by controller[0]:     at Object.Module._extensions..js (module.js:664:10)
2018-11-22 12:57:05.581  - error: Caught by controller[0]:     at Module.load (module.js:566:32)
2018-11-22 12:57:05.581  - error: Caught by controller[0]:     at tryModuleLoad (module.js:506:12)
2018-11-22 12:57:05.581  - error: Caught by controller[0]:     at Function.Module._load (module.js:498:3)
2018-11-22 12:57:05.582  - error: Caught by controller[0]:     at Function.Module.runMain (module.js:694:10)
2018-11-22 12:57:05.582  - error: Caught by controller[0]:     at startup (bootstrap_node.js:204:16)
2018-11-22 12:57:05.583  - error: Caught by controller[0]:     at bootstrap_node.js:625:3
2018-11-22 12:57:05.583  - error: host.ioBroker-Rock64 instance system.adapter.javascript.0 terminated with code 1 ()
```

**Comment by AlCalzone** [comment]
Seems some quotes were missing

**Comment by Apollon77** [comment]
LOL

**Comment by Apollon77** [comment]
you then need a new shirt? Correct ;-)
