### ISSUE TITLE
v4.1.6 has suffix 0 on all script names in overview

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.javascript#339]

**Comment by Diginix** [comment]
Since v4.1.6 all my scripts has a zero in it's name at the end.

![js_script_names](https://user-images.githubusercontent.com/39678667/53548210-40510a80-3b31-11e9-89ce-f08b43bdfa52.jpg)

**Comment by Ilovegym66** [comment]
yes, I can confirm that issue. Node 8.15, NPM 6.5.0, js-controller 1.5.7, admin 3.6.0.
Linux Mint 18.3.

**Comment by Rantanplan01** [comment]
Kann ich auch bestätigen. Scheint nur in der Auflistung zu sein.
Unter "Objekte/javascriptscript.x/scriptEnabled" ist alles ok.

Ich hatte folgende Fehlermeldungen bei Update auf die 4.1.6 (Host Win10/64bit)

`
2019-02-28 09:25:17.164  - info: javascript.0 Start javascript script.js.common.Skript_1
2019-02-28 09:25:17.179  - error: javascript.0 script.js.common.Skript_1 compile failed:
at script.js.common.Skript_1:2
2019-02-28 09:25:17.179  - error: javascript.0   "common": {
2019-02-28 09:25:17.179  - error: javascript.0           ^
2019-02-28 09:25:17.179  - error: javascript.0 SyntaxError: Unexpected token :
2019-02-28 09:25:17.179  - error: javascript.0     at Object.exports.createScript (vm.js:47:10)
2019-02-28 09:25:17.179  - error: javascript.0     at compile (C:\ioBroker\node_modules\iobroker.javascript\main.js:834:28)
2019-02-28 09:25:17.179  - error: javascript.0     at prepareScript (C:\ioBroker\node_modules\iobroker.javascript\main.js:1023:37)
2019-02-28 09:25:17.179  - error: javascript.0     at Socket.adapter.getForeignState (C:\ioBroker\node_modules\iobroker.javascript\main.js:701:17)
2019-02-28 09:25:17.179  - error:  javascript.0     at Socket.onack  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:312:9)
2019-02-28 09:25:17.179  - error:  javascript.0     at Socket.onpacket  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:236:12)
2019-02-28 09:25:17.179  - error: javascript.0     at Manager. (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
2019-02-28 09:25:17.179  - error:  javascript.0     at Manager.Emitter.emit  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
2019-02-28 09:25:17.179  - error:  javascript.0     at Manager.ondecoded  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:332:8)
2019-02-28 09:25:17.179  - error: javascript.0     at Decoder. (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
2019-02-28 09:25:17.179  - error:  javascript.0     at Decoder.Emitter.emit  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-emitter\index.js:134:20)
2019-02-28 09:25:17.179  - error:  javascript.0     at Decoder.add  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-parser\index.js:246:12)
2019-02-28 09:25:17.179  - error:  javascript.0     at Manager.ondata  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:322:16)
2019-02-28 09:25:17.179  - error: javascript.0     at Socket. (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
2019-02-28 09:25:17.179  - error:  javascript.0     at Socket.Emitter.emit  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
2019-02-28 09:25:17.179  - error:  javascript.0     at Socket.onPacket  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\lib\socket.js:451:14)
2019-02-28 09:25:17.179  - error: javascript.0     at WS. (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\lib\socket.js:268:10)
2019-02-28 09:25:17.179  - error:  javascript.0     at WS.Emitter.emit  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
2019-02-28 09:25:17.195  - error:  javascript.0     at WS.Transport.onPacket  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\lib\transport.js:145:8)
2019-02-28 09:25:17.195  - error:  javascript.0     at WS.Transport.onData  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\lib\transport.js:137:8)
2019-02-28 09:25:17.195  - error:  javascript.0     at WebSocket.ws.onmessage  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\lib\transports\websocket.js:146:10)
2019-02-28 09:25:17.195  - error:  javascript.0     at WebSocket.onMessage  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\WebSocket.js:442:14)
2019-02-28 09:25:17.195  - error: javascript.0     at emitTwo (events.js:106:13)
2019-02-28 09:25:17.195  - error: javascript.0     at WebSocket.emit (events.js:191:7)
2019-02-28 09:25:17.195  - error: javascript.0     at Receiver.ontext (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\WebSocket.js:841:10)
2019-02-28 09:25:17.195  - error: javascript.0     at C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:536:18
2019-02-28 09:25:17.195  - error:  javascript.0     at Receiver.applyExtensions  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:371:5)
2019-02-28 09:25:17.195  - error: javascript.0     at C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:508:14
2019-02-28 09:25:17.195  - error: javascript.0     at Receiver.flush (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:347:3)
2019-02-28 09:25:17.195  - error: javascript.0     at Receiver.finish (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:541:12)
2019-02-28 09:25:17.195  - error:  javascript.0     at Receiver.expectHandler  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:499:31)
2019-02-28 09:25:17.195  - error: javascript.0     at Receiver.add (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:103:24)
2019-02-28 09:25:17.195  - error:  javascript.0     at Socket.realHandler  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\WebSocket.js:825:20)
2019-02-28 09:25:17.195  - error: javascript.0     at emitOne (events.js:96:13)
2019-02-28 09:25:17.195  - error: javascript.0     at Socket.emit (events.js:188:7)
2019-02-28 09:25:17.195  - error: javascript.0     at readableAddChunk (_stream_readable.js:176:18)
2019-02-28 09:25:17.195  - error: javascript.0     at TCP.onread (net.js:548:20)
2019-02-28 09:25:17.211  - info: javascript.0 Start javascript script.js.Test.Skript_1
2019-02-28 09:25:17.211  - info: javascript.0 script.js.Test.Skript_1: registered 0 subscriptions and 0 schedules
`

**Comment by GermanBluefox** [comment]
> Ich hatte folgende Fehlermeldungen bei Update auf die 4.1.6 (Host Win10/64bit)
> 

Please create new issue for that and paste there the whole object  script.js.common.Skript_1

**Comment by GermanBluefox** [comment]
Fixed in 4.1.7
