### ISSUE TITLE
Fehler LOG update auf v4.1.6

### ISSUE THREAD

**Issue by Rantanplan01** [ioBroker/ioBroker.javascript#340]
Beim Update traten folgende Fehler auf:

`
2019-02-28 09:25:17.164  - info: javascript.0 Start javascript script.js.common.Skript_1
2019-02-28 09:25:17.179  - error: javascript.0 script.js.common.Skript_1 compile failed:at script.js.common.Skript_1:2
2019-02-28 09:25:17.179  - error: javascript.0   "common": {
2019-02-28 09:25:17.179  - error: javascript.0           ^
2019-02-28 09:25:17.179  - error: javascript.0 SyntaxError: Unexpected token :
2019-02-28 09:25:17.179  - error: javascript.0     at Object.exports.createScript (vm.js:47:10)
2019-02-28 09:25:17.179  - error: javascript.0     at compile (C:\ioBroker\node_modules\iobroker.javascript\main.js:834:28)
2019-02-28 09:25:17.179  - error: javascript.0     at prepareScript (C:\ioBroker\node_modules\iobroker.javascript\main.js:1023:37)
2019-02-28 09:25:17.179  - error: javascript.0     at Socket.adapter.getForeignState (C:\ioBroker\node_modules\iobroker.javascript\main.js:701:17)
2019-02-28 09:25:17.179  - error:  javascript.0     at Socket.onack  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:312:9)
2019-02-28 09:25:17.179  - error:  javascript.0     at Socket.onpacket  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:236:12)
2019-02-28 09:25:17.179  - error: javascript.0     at Manager. (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
2019-02-28 09:25:17.179  - error:  javascript.0     at Manager.Emitter.emit  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
2019-02-28 09:25:17.179  - error:  javascript.0     at Manager.ondecoded  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:332:8)
2019-02-28 09:25:17.179  - error: javascript.0     at Decoder. (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
2019-02-28 09:25:17.179  - error:  javascript.0     at Decoder.Emitter.emit  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-emitter\index.js:134:20)
2019-02-28 09:25:17.179  - error:  javascript.0     at Decoder.add  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-parser\index.js:246:12)
2019-02-28 09:25:17.179  - error:  javascript.0     at Manager.ondata  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:322:16)
2019-02-28 09:25:17.179  - error: javascript.0     at Socket. (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
2019-02-28 09:25:17.179  - error:  javascript.0     at Socket.Emitter.emit  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
2019-02-28 09:25:17.179  - error:  javascript.0     at Socket.onPacket  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\lib\socket.js:451:14)
2019-02-28 09:25:17.179  - error: javascript.0     at WS. (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\lib\socket.js:268:10)
2019-02-28 09:25:17.179  - error:  javascript.0     at WS.Emitter.emit  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
2019-02-28 09:25:17.195  - error:  javascript.0     at WS.Transport.onPacket  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\lib\transport.js:145:8)
2019-02-28 09:25:17.195  - error:  javascript.0     at WS.Transport.onData  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\lib\transport.js:137:8)
2019-02-28 09:25:17.195  - error:  javascript.0     at WebSocket.ws.onmessage  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\engine.io-client\lib\transports\websocket.js:146:10)
2019-02-28 09:25:17.195  - error:  javascript.0     at WebSocket.onMessage  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\WebSocket.js:442:14)
2019-02-28 09:25:17.195  - error: javascript.0     at emitTwo (events.js:106:13)
2019-02-28 09:25:17.195  - error: javascript.0     at WebSocket.emit (events.js:191:7)
2019-02-28 09:25:17.195  - error: javascript.0     at Receiver.ontext (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\WebSocket.js:841:10)
2019-02-28 09:25:17.195  - error: javascript.0     at C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:536:18
2019-02-28 09:25:17.195  - error:  javascript.0     at Receiver.applyExtensions  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:371:5)
2019-02-28 09:25:17.195  - error: javascript.0     at C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:508:14
2019-02-28 09:25:17.195  - error: javascript.0     at Receiver.flush (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:347:3)
2019-02-28 09:25:17.195  - error: javascript.0     at Receiver.finish (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:541:12)
2019-02-28 09:25:17.195  - error:  javascript.0     at Receiver.expectHandler  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:499:31)
2019-02-28 09:25:17.195  - error: javascript.0     at Receiver.add (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\Receiver.js:103:24)
2019-02-28 09:25:17.195  - error:  javascript.0     at Socket.realHandler  (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\ws\lib\WebSocket.js:825:20)
2019-02-28 09:25:17.195  - error: javascript.0     at emitOne (events.js:96:13)
2019-02-28 09:25:17.195  - error: javascript.0     at Socket.emit (events.js:188:7)
2019-02-28 09:25:17.195  - error: javascript.0     at readableAddChunk (_stream_readable.js:176:18)
2019-02-28 09:25:17.195  - error: javascript.0     at TCP.onread (net.js:548:20)
2019-02-28 09:25:17.211  - info: javascript.0 Start javascript script.js.Test.Skript_1
2019-02-28 09:25:17.211  - info: javascript.0 script.js.Test.Skript_1: registered 0 subscriptions and 0 schedules
`

Das betreffende Script wird mir als **JavaScript** angezeigt, war aber bestimmt ein **Blockly**.
Im **Editor** steht:

`
{
  "common": {
    "name": "Skript 1",
    "expert": true,
    "engineType": "Blockly",
    "engine": "system.adapter.javascript.0",
    "source": "",
    "debug": false,
    "verbose": false
  },
  "type": "script",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1550423166839,
  "_id": "script.js.common.Skript_1",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
`

Unter  **javascript.1.scriptEnabled.common.Skript_1 (RAW)** steht:

`
{
  "from": "system.adapter.javascript.1",
  "user": "system.user.admin",
  "ts": 1550434613212,
  "common": {
    "name": "scriptEnabled.common.Skript_1",
    "desc": "controls script activity",
    "type": "boolean",
    "role": "switch.active",
    "write": true,
    "read": true
  },
  "native": {
    "script": "script.js.common.Skript_1"
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "javascript.1.scriptEnabled.common.Skript_1",
  "type": "state"
}
`

Ich habe keine Ahnung was da mal im Blockly stand. Wird irgendein Test gewesen sein.

**Comment by GermanBluefox** [comment]
Cannot reproduce the error.... With the same object created.

**Comment by Rantanplan01** [comment]
Ok. Ist ja nichts schlimmes passiert.
