### ISSUE TITLE
Get mirror to disk working

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.javascript#360]

**Comment by cyptus** [comment]
funktioniert das mirror den schon? 
wenn ich ein pfad angebe (/home/iobroker/files, permissions und owner gesetzt) kriege ich im log erst

`Watch /home/iobroker/files/scripts`

dann

```
Caught by controller[7]: errno: -2, syscall: 'mkdir', code: 'ENOENT' }
Caught by controller[7]: at processImmediate (timers.js:658:5)
Caught by controller[7]: at tryOnImmediate (timers.js:676:5)
Caught by controller[7]: at runCallback (timers.js:705:18)
Caught by controller[7]: at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1473:79)
Caught by controller[7]: at Object.objectChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:205:30)
Caught by controller[7]: at Mirror.onObjectChange (/opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:261:28)
Caught by controller[7]: at Function.createRecursiveDir (/opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:77:20)
Caught by controller[7]: at Object.mkdirSync (fs.js:757:3)
Caught by controller[7]: { Error: ENOENT: no such file or directory, mkdir

[...]

Error: ENOENT: no such file or directory, mkdir at Object.mkdirSync (fs.js:757:3) at Function.createRecursiveDir (/opt/iobroker/node_modules/iobroker.javascript/lib/mirror.js:77:20)
uncaught exception: ENOENT: no such file or directory, mkdir
```

**Comment by Apollon77** [comment]
@cyptus Welche javascript Version?

**Comment by cyptus** [comment]
@Apollon77 war noch auf stable 4.1.12
mit 4.3.4 funktioniert alles - danke!
