### ISSUE TITLE
e.stack may be undefined in logError

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#369]
https://forum.iobroker.net/topic/21543/mehrere-trigger-auf-das-gleiche-objekt-setzen/17

https://github.com/ioBroker/ioBroker.javascript/blob/3d1f33fa65f4c46fd6cb3aa58e8a2d3ce8100ce1/main.js#L661
called from
https://github.com/ioBroker/ioBroker.javascript/blob/3d1f33fa65f4c46fd6cb3aa58e8a2d3ce8100ce1/main.js#L925

**Comment by AlCalzone** [comment]
```
javascript.0	2019-04-06 13:45:44.353	error	at Socket.adapter.getForeignState (/opt/iobroker/node_modules/iobroker.javascript/main.js:745:17)
javascript.0	2019-04-06 13:45:44.353	error	at createProblemObject (/opt/iobroker/node_modules/iobroker.javascript/main.js:1123:17)
javascript.0	2019-04-06 13:45:44.353	error	at prepareScript (/opt/iobroker/node_modules/iobroker.javascript/main.js:1101:42)
javascript.0	2019-04-06 13:45:44.353	error	at execute (/opt/iobroker/node_modules/iobroker.javascript/main.js:925:21)
javascript.0	2019-04-06 13:45:44.353	error	at Object.context.logError (/opt/iobroker/node_modules/iobroker.javascript/main.js:661:27)
javascript.0	2019-04-06 13:45:44.353	error	TypeError: Cannot read property 'split' of undefined
```

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.javascript/commit/e2b11586e8c60248806a4ffad97894b0f60ba4ce#diff-7a9076d6d94e62c13d641aa71f19ae8eR679
