### ISSUE TITLE
Version 4.1.13 getDate/getAstroDate Error.

### ISSUE THREAD

**Issue by kugelkopf123** [ioBroker/ioBroker.javascript#387]
Since the new Version 4.1.13 i get this Error in Log:

```
2019-06-05 15:18:03.016 - error: javascript.0 Error in callback: TypeError: date.getDate is not a function
--
2019-06-05 15:18:03.016 - error: javascript.0 at getAstroDate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1220:42)
2019-06-05 15:18:03.016 - error: javascript.0 at Object. (script.js.Astro.AstroZeit:323:16)
2019-06-05 15:18:03.016 - error: javascript.0 at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1886:34)
2019-06-05 15:18:03.016 - error: javascript.0 at ontimeout (timers.js:511:34)
2019-06-05 15:18:03.016 - error: javascript.0 at tryOnTimeout (timers.js:323:5)
2019-06-05 15:18:03.016 - error: javascript.0 at Timer.listOnTimeout (timers.js:290:5)

```

I can not explain why. Never had any problems before with V 4.1.12

Code Snippet: 

```
function writeAstroTimes(i) {
    // führende Nummer zur Sortierung in Admin/Objekte
    var nr = (i+1 < 10) ? "0" + (i+1) : (i+1);
    // Erstelle Objekt, falls nicht bereits vorhanden
    var idAstroObject = "javascript." + instance + "." + pfad + ".Zeiten." + nr + " - " + astrotime.elements[i].fname;
    createState(idAstroObject, " ", fC, {
        name: astrotime.elements[i].de.nxt + " " + astrotime.elements[i].de.name + " Uhrzeit",
        desc: astrotime.elements[i].en.desc,
        type: "string"
    });
    
    setTimeout(function() { // kurz warten, damit Objekte ggf. erst angelgt werden können
        var astrotag = getState(idAstrotag).val,
            temp;
        let today = new Date();
        let tomorrow = today.setDate(today.getDate()+1);
        var next_event;
        if (astrotag) { 
            // Wenn Tag (Aufgang vorbei (erst wieder morgen, Untergang kommt noch heute)
            next_event = (astrotime.elements[i].astroday) ? tomorrow : today; // prüfen
        } else { 
            // nach Nacht (Untergang vorbei (erst wieder morgen, Aufgang kommt heute oder morgen)
            next_event = (astrotime.elements[i].astroday) ? today : tomorrow; // prüfen
        }
       log("nextEvent: " + next_event);
        var fname = astrotime.elements[i].fname;
        temp = getAstroDate(fname, next_event;
        setState(idAstroObject, checkSec(temp.toLocaleTimeString()) );
    }, 3 * 1000);
}
```

**Comment by FabianHM** [comment]
I also have the problem that the Astro functions no longer work

**Comment by eumats** [comment]
Me too...

**Comment by AlGu1** [comment]
I have the same problem, example from Github docu dose not work:

```
var today = new Date();
var tomorrow = today.setDate(today.getDate() + 1);
var tomorrowNigh = getAstroDate("night", tomorrow);
```
best regards

**Comment by AlexanderSch90** [comment]
same here

**Comment by paul53** [comment]
Is fixed on github since 06.06.2019.

**Comment by kugelkopf123** [comment]
> Is fixed on github since 06.06.2019.

I've tried both. The one thats on Github and the Version on NPM 4.1.14. Still has Problems... 

iobroker Log: 

```

2019-07-16 00:43:47.752 - info: javascript.0 Start javascript script.js.Astro.AstroZeit
--
2019-07-16 00:43:47.757 - error: javascript.0 script.js.Astro.AstroZeit compile failed:
at script.js.Astro.AstroZeit:323
2019-07-16 00:43:47.758 - error: javascript.0 temp = getAstroDate(fname, next_event;
2019-07-16 00:43:47.758 - error: javascript.0 ^^^^^^^^^^
2019-07-16 00:43:47.758 - error: javascript.0 SyntaxError: missing ) after argument list
2019-07-16 00:43:47.758 - error: javascript.0 at Object.createScript (vm.js:80:10)
2019-07-16 00:43:47.758 - error: javascript.0 at compile (/opt/iobroker/node_modules/iobroker.javascript/main.js:882:28)
2019-07-16 00:43:47.758 - error: javascript.0 at prepareScript (/opt/iobroker/node_modules/iobroker.javascript/main.js:1074:37)
2019-07-16 00:43:47.759 - error: javascript.0 at createProblemObject (/opt/iobroker/node_modules/iobroker.javascript/main.js:1127:17)
2019-07-16 00:43:47.759 - error: javascript.0 at Socket.adapter.getForeignState (/opt/iobroker/node_modules/iobroker.javascript/main.js:749:17)
2019-07-16 00:43:47.759 - error: javascript.0 at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
2019-07-16 00:43:47.759 - error: javascript.0 at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
2019-07-16 00:43:47.759 - error: javascript.0 at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
2019-07-16 00:43:47.759 - error: javascript.0 at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
2019-07-16 00:43:47.759 - error: javascript.0 at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
2019-07-16 00:43:47.760 - error: javascript.0 at Decoder. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
2019-07-16 00:43:47.760 - error: javascript.0 at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
2019-07-16 00:43:47.760 - error: javascript.0 at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
2019-07-16 00:43:47.760 - error: javascript.0 at Manager.ondata (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:322:16)
2019-07-16 00:43:47.760 - error: javascript.0 at Socket. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
2019-07-16 00:43:47.760 - error: javascript.0 at Socket.Emitter.emit (/opt/iobroker/node_modules/engine.io-client/node_modules/component-emitter/index.js:133:20)
2019-07-16 00:43:47.761 - error: javascript.0 at Socket.onPacket (/opt/iobroker/node_modules/engine.io-client/lib/socket.js:451:14)
2019-07-16 00:43:47.761 - error: javascript.0 at WS. (/opt/iobroker/node_modules/engine.io-client/lib/socket.js:268:10)
2019-07-16 00:43:47.761 - error: javascript.0 at WS.Emitter.emit (/opt/iobroker/node_modules/engine.io-client/node_modules/component-emitter/index.js:133:20)
2019-07-16 00:43:47.761 - error: javascript.0 at WS.Transport.onPacket (/opt/iobroker/node_modules/engine.io-client/lib/transport.js:145:8)
2019-07-16 00:43:47.761 - error: javascript.0 at WS.Transport.onData (/opt/iobroker/node_modules/engine.io-client/lib/transport.js:137:8)
2019-07-16 00:43:47.761 - error: javascript.0 at WebSocket.ws.onmessage (/opt/iobroker/node_modules/engine.io-client/lib/transports/websocket.js:146:10)
2019-07-16 00:43:47.761 - error: javascript.0 at WebSocket.onMessage (/opt/iobroker/node_modules/ws/lib/WebSocket.js:442:14)
2019-07-16 00:43:47.762 - error: javascript.0 at emitTwo (events.js:126:13)
2019-07-16 00:43:47.762 - error: javascript.0 at WebSocket.emit (events.js:214:7)
2019-07-16 00:43:47.762 - error: javascript.0 at Receiver.ontext (/opt/iobroker/node_modules/ws/lib/WebSocket.js:841:10)
2019-07-16 00:43:47.762 - error: javascript.0 at /opt/iobroker/node_modules/ws/lib/Receiver.js:536:18
2019-07-16 00:43:47.762 - error: javascript.0 at Receiver.applyExtensions (/opt/iobroker/node_modules/ws/lib/Receiver.js:371:5)
2019-07-16 00:43:47.762 - error: javascript.0 at /opt/iobroker/node_modules/ws/lib/Receiver.js:508:14
2019-07-16 00:43:47.762 - error: javascript.0 at Receiver.flush (/opt/iobroker/node_modules/ws/lib/Receiver.js:347:3)
2019-07-16 00:43:47.763 - error: javascript.0 at Receiver.finish (/opt/iobroker/node_modules/ws/lib/Receiver.js:541:12)
2019-07-16 00:43:47.763 - error: javascript.0 at Receiver.expectHandler (/opt/iobroker/node_modules/ws/lib/Receiver.js:499:31)
2019-07-16 00:43:47.763 - error: javascript.0 at Receiver.add (/opt/iobroker/node_modules/ws/lib/Receiver.js:103:24)
2019-07-16 00:43:47.763 - error: javascript.0 at Socket.realHandler (/opt/iobroker/node_modules/ws/lib/WebSocket.js:825:20)
2019-07-16 00:43:47.763 - error: javascript.0 at emitOne (events.js:116:13)
2019-07-16 00:43:47.763 - error: javascript.0 at Socket.emit (events.js:211:7)
2019-07-16 00:43:47.763 - error: javascript.0 at addChunk (_stream_readable.js:263:12)
2019-07-16 00:43:47.764 - error: javascript.0 at readableAddChunk (_stream_readable.js:250:11)
2019-07-16 00:43:47.764 - error: javascript.0 at Socket.Readable.push (_stream_readable.js:208:10)
2019-07-16 00:43:47.764 - error: javascript.0 at TCP.onread (net.js:601:20)


```

**Comment by Apollon77** [comment]
Naja dann korrigiere mal dein Skript und schließe die Klammer am Ende der Zeile. Die Fehlermeldung sagt was falsch ist.

**Comment by GermanBluefox** [comment]
Please reopen if the error still exists
