### ISSUE TITLE
Wrong search path for library

### ISSUE THREAD

**Issue by cburghardt** [ioBroker/ioBroker.javascript#436]
I just updated the adapter to 4.3.2 and it fails when loading the googleapis node module:

```
2019-11-02 20:59:09.188  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]: { Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/googleapis/build/src/googleapis/index.d.ts'
2019-11-02 20:59:09.189  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at Object.fs.openSync (fs.js:646:18)
2019-11-02 20:59:09.190  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at Object.fs.readFileSync (fs.js:551:33)
2019-11-02 20:59:09.190  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at resolveTypings (/opt/iobroker/node_modules/iobroker.javascript/lib/typescriptTools.js:83:32)
2019-11-02 20:59:09.191  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at loadTypeScriptDeclarations (/opt/iobroker/node_modules/iobroker.javascript/main.js:179:28)
2019-11-02 20:59:09.191  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at installLibraries (/opt/iobroker/node_modules/iobroker.javascript/main.js:479:17)
2019-11-02 20:59:09.191  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at installLibraries (/opt/iobroker/node_modules/iobroker.javascript/main.js:961:23)
2019-11-02 20:59:09.191  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at Object.ready (/opt/iobroker/node_modules/iobroker.javascript/main.js:476:13)
2019-11-02 20:59:09.192  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at initLogging (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6757:64)
2019-11-02 20:59:09.192  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at states.getKeys (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6461:25)
2019-11-02 20:59:09.192  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at client.keys (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:571:17)
2019-11-02 20:59:09.192  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
2019-11-02 20:59:09.192  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
2019-11-02 20:59:09.193  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at <anonymous>:null:null
2019-11-02 20:59:09.193  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:     at process._tickCallback (internal/process/next_tick.js:189:7)
2019-11-02 20:59:09.193  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:   errno: -2,
2019-11-02 20:59:09.193  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:   code: 'ENOENT',
2019-11-02 20:59:09.194  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:   syscall: 'open',
2019-11-02 20:59:09.194  - ^[[31merror^[[39m: host.iobroker1 Caught by controller[0]:   path: '/opt/iobroker/node_modules/iobroker.javascript/node_modules/googleapis/build/src/googleapis/index.d.ts' }
```

Note the additional and superfluous "googleapis" directory in the path. This has been introduced in 4.3.2 as it works in 4.3.1.

**Comment by AlCalzone** [comment]
That is a bug in the loading of 3rd party type definitions. Should be fixed in 4.3.3

**Comment by AlCalzone** [comment]
just out of curiosity, does `index.d.ts` exist somewhere in `/opt/iobroker/node_modules/iobroker.javascript/node_modules/googleapis/build` and how does `/opt/iobroker/node_modules/iobroker.javascript/node_modules/googleapis/package.json` look like?

**Comment by cburghardt** [comment]
yes it does exist in /opt/iobroker/node_modules/iobroker.javascript/node_modules/googleapis/build/src

package.json is that one:
https://github.com/googleapis/google-api-nodejs-client/blob/master/package.json

**Comment by AlCalzone** [comment]
Ok I found the problem. The `index.d.ts` imports a file `./googleapis`. The adapter assumes this is `./googleapis/index.d.ts`, which does not exist. In reality it is `./googleapis.d.ts`.

**Comment by AlCalzone** [comment]
@cburghardt Can you please try if this version of the js adapter https://github.com/ioBroker/ioBroker.javascript/tarball/3rd-party-def-fixes fixes your problem?
