### ISSUE TITLE
Blockly convert block for weekday (long+short) doesn't work

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.javascript#498]
Converting a timestamp to weekday name short or long fails with that error:

`2020-02-10 10:54:57.562  - [31merror[39m: javascript.0 (4044) script.js.automatization.Weather.DWD_Warnings: /opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2348
2020-02-10 10:54:57.562  - [31merror[39m: javascript.0 (4044)                 const d = date.getDay();
2020-02-10 10:54:57.563  - [31merror[39m: javascript.0 (4044)                                ^
2020-02-10 10:54:57.563  - [31merror[39m: javascript.0 (4044) TypeError: date.getDay is not a function
2020-02-10 10:54:57.563  - [31merror[39m: javascript.0 (4044)     at formatDate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2348:32)
2020-02-10 10:54:57.563  - [31merror[39m: javascript.0 (4044)     at script.js.automatization.Weather.DWD_Warnings:119:13
2020-02-10 10:54:57.563  - [31merror[39m: javascript.0 (4044)     at Script.runInContext (vm.js:133:20)`

javascript 4.4.1 (4.4.2)
admin 4.0.1 (4.0.5)
JS-Controller 2.2.8 (2.2.9)
nodejs 10.19.0
npm 6.9.0

**Comment by GermanBluefox** [comment]
That can happen if you give the non Date object to `formatDate`, like
```
formatDate({a: 1}, 'HH')
```

**Comment by Diginix** [comment]
The bug has occured if you try to convert the default system unix timestamp (e.g. lc) of an object/state.
But I have testet it again with javascript 4.6.x and it works now. So, it must be fixed (by misstake) between 4.5.x and 4.6.x.
Sometimes magic happens. ;-)
