### ISSUE TITLE
JavaScript Adapter crashes 'Cannot read property 'split' of undefined'

### ISSUE THREAD

**Issue by seb111425** [ioBroker/ioBroker.javascript#508]
Hi,
I'm running 4.4.2 and it looks like I'm still facing issues with the Astro functions as the adapter keeps crashing with the following error message:

2020-02-24 00:00:21.654  - [32minfo[39m: host.ioBroker-RasPi4 instance system.adapter.javascript.0 started with pid 9591
2020-02-24 00:00:24.428  - [32minfo[39m: javascript.0 (9591) starting. Version 4.4.2 in /opt/iobroker/node_modules/iobroker.javascript, node: v10.18.1
2020-02-24 00:00:24.503  - [32minfo[39m: javascript.0 (9591) requesting all states
2020-02-24 00:00:24.505  - [32minfo[39m: javascript.0 (9591) requesting all objects
2020-02-24 00:00:25.956  - [32minfo[39m: javascript.0 (9591) received all objects
2020-02-24 00:00:26.107  - [32minfo[39m: javascript.0 (9591) received all states
2020-02-24 00:00:26.119  - [31merror[39m: javascript.0 (9591) uncaught exception: Cannot read property 'split' of undefined
2020-02-24 00:00:26.120  - [31merror[39m: javascript.0 (9591) TypeError: Cannot read property 'split' of undefined
    at getNextTimeEvent (/opt/iobroker/node_modules/iobroker.javascript/main.js:777:41)
    at getAstroEvent (/opt/iobroker/node_modules/iobroker.javascript/main.js:793:49)
    at dayTimeSchedules (/opt/iobroker/node_modules/iobroker.javascript/main.js:857:25)
    at getData (/opt/iobroker/node_modules/iobroker.javascript/main.js:506:21)
    at adapter.getForeignStates (/opt/iobroker/node_modules/iobroker.javascript/main.js:1511:59)
    at states.getStates (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5919:17)
    at client.mget (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:619:13)
    at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)

2020-02-24 00:00:26.142  - [32minfo[39m: javascript.0 (9591) terminating
2020-02-24 00:00:26.144  - [32minfo[39m: javascript.0 (9591) Terminated (NO_ERROR): Without reason
2020-02-24 00:00:26.681  - [31merror[39m: host.ioBroker-RasPi4 Caught by controller[0]: TypeError: Cannot read property 'split' of undefined
2020-02-24 00:00:26.682  - [31merror[39m: host.ioBroker-RasPi4 Caught by controller[0]:     at getNextTimeEvent (/opt/iobroker/node_modules/iobroker.javascript/main.js:777:41)
2020-02-24 00:00:26.682  - [31merror[39m: host.ioBroker-RasPi4 Caught by controller[0]:     at getAstroEvent (/opt/iobroker/node_modules/iobroker.javascript/main.js:793:49)
2020-02-24 00:00:26.682  - [31merror[39m: host.ioBroker-RasPi4 Caught by controller[0]:     at dayTimeSchedules (/opt/iobroker/node_modules/iobroker.javascript/main.js:857:25)
2020-02-24 00:00:26.682  - [31merror[39m: host.ioBroker-RasPi4 Caught by controller[0]:     at getData (/opt/iobroker/node_modules/iobroker.javascript/main.js:506:21)
2020-02-24 00:00:26.682  - [31merror[39m: host.ioBroker-RasPi4 Caught by controller[0]:     at adapter.getForeignStates (/opt/iobroker/node_modules/iobroker.javascript/main.js:1511:59)
2020-02-24 00:00:26.682  - [31merror[39m: host.ioBroker-RasPi4 Caught by controller[0]:     at states.getStates (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5919:17)
2020-02-24 00:00:26.683  - [31merror[39m: host.ioBroker-RasPi4 Caught by controller[0]:     at client.mget (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:619:13)
2020-02-24 00:00:26.683  - [31merror[39m: host.ioBroker-RasPi4 Caught by controller[0]:     at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
2020-02-24 00:00:26.683  - [31merror[39m: host.ioBroker-RasPi4 Caught by controller[0]:     at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
2020-02-24 00:00:26.683  - [31merror[39m: host.ioBroker-RasPi4 Caught by controller[0]:     at process._tickCallback (internal/process/next_tick.js:68:7)
2020-02-24 00:00:26.683  - [32minfo[39m: host.ioBroker-RasPi4 instance system.adapter.javascript.0 terminated with code 0 (NO_ERROR)

I deactivated all my scripts and it still crashes in a loop.

Thanks & best,
Seb

**Comment by Apollon77** [comment]
Please execurte "iobroker upload javascript" and then check the javascript config especially for  the sunrise settings and such. There is an empty field that should not be empty

**Comment by seb111425** [comment]
Seems like executing "iobroker upload javascript" solved the problem already as it is not crashing anymore. What does the command actually do?

**Comment by Apollon77** [comment]
In the last version there were new settings introduces and one of the things "Upload" is doing is to merge them into your settings. I also added a fix for a next version
