### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined at checkVersion (/opt/iobroker/node_modules/iobroker.info/main.js:223:23) at checkConditions (/opt/iobroker/node_modules/iobroker.in

### ISSUE THREAD

**Issue by PhilipDiePython** [ioBroker/ioBroker.javascript#530]
Here's my problem:
I've been working with the Iobroker and a Conbee 2 Stick for 4 days. In the log the following error is listed repeatedly.
2020-04-07 00:00:24.522  - [32minfo[39m: host.raspberrypi instance system.adapter.info.0 started with pid 5372
2020-04-07 00:00:29.827  - [32minfo[39m: info.0 (5372) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.info, node: v10.17.0
2020-04-07 00:00:31.970  - [32minfo[39m: info.0 (5372) Popup news was read...
2020-04-07 00:00:32.149  - [31merror[39m: info.0 (5372) uncaught exception: Cannot read property 'split' of undefined
2020-04-07 00:00:32.151  - [31merror[39m: info.0 (5372) TypeError: Cannot read property 'split' of undefined
    at checkVersion (/opt/iobroker/node_modules/iobroker.info/main.js:223:23)
    at checkConditions (/opt/iobroker/node_modules/iobroker.info/main.js:138:25)
    at Object.keys.forEach.key (/opt/iobroker/node_modules/iobroker.info/main.js:185:46)
    at Array.forEach (<anonymous>)
    at messages.forEach.message (/opt/iobroker/node_modules/iobroker.info/main.js:172:57)
    at Array.forEach (<anonymous>)
    at instances (/opt/iobroker/node_modules/iobroker.info/main.js:160:26)
    at adapter.objects.getObjectView (/opt/iobroker/node_modules/iobroker.info/main.js:264:21)
    at (anonymous function).(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:83115)
    at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
2020-04-07 00:00:32.156  - [32minfo[39m: info.0 (5372) cleaned everything up...
2020-04-07 00:00:32.206  - [32minfo[39m: info.0 (5372) terminating
2020-04-07 00:00:32.208  - [32minfo[39m: info.0 (5372) Terminated (NO_ERROR): Without reason
2020-04-07 00:00:32.763  - [31merror[39m: host.raspberrypi Caught by controller[0]: TypeError: Cannot read property 'split' of undefined
2020-04-07 00:00:32.764  - [31merror[39m: host.raspberrypi Caught by controller[0]:     at checkVersion (/opt/iobroker/node_modules/iobroker.info/main.js:223:23)
2020-04-07 00:00:32.764  - [31merror[39m: host.raspberrypi Caught by controller[0]:     at checkConditions (/opt/iobroker/node_modules/iobroker.info/main.js:138:25)
2020-04-07 00:00:32.764  - [31merror[39m: host.raspberrypi Caught by controller[0]:     at Object.keys.forEach.key (/opt/iobroker/node_modules/iobroker.info/main.js:185:46)
2020-04-07 00:00:32.765  - [31merror[39m: host.raspberrypi Caught by controller[0]:     at Array.forEach (<anonymous>)
2020-04-07 00:00:32.765  - [31merror[39m: host.raspberrypi Caught by controller[0]:     at messages.forEach.message (/opt/iobroker/node_modules/iobroker.info/main.js:172:57)
2020-04-07 00:00:32.765  - [31merror[39m: host.raspberrypi Caught by controller[0]:     at Array.forEach (<anonymous>)
2020-04-07 00:00:32.765  - [31merror[39m: host.raspberrypi Caught by controller[0]:     at instances (/opt/iobroker/node_modules/iobroker.info/main.js:160:26)
2020-04-07 00:00:32.766  - [31merror[39m: host.raspberrypi Caught by controller[0]:     at adapter.objects.getObjectView (/opt/iobroker/node_modules/iobroker.info/main.js:264:21)
2020-04-07 00:00:32.766  - [31merror[39m: host.raspberrypi Caught by controller[0]:     at (anonymous function).(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:83115)
2020-04-07 00:00:32.766  - [31merror[39m: host.raspberrypi Caught by controller[0]:     at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
2020-04-07 00:00:32.766  - [32minfo[39m: host.raspberrypi instance system.adapter.info.0 terminated with code 0 (NO_ERROR)
2020-04-07 00:00:32.767  - [32minfo[39m: host.raspberrypi Restart adapter system.adapter.info.0 because enabled
2020-04-07 00:01:02.783  - [32minfo[39m: host.raspberrypi instance system.adapter.info.0 started with pid 6178
[iobroker.2020-04-07.log](https://github.com/ioBroker/ioBroker.javascript/files/4446053/iobroker.2020-04-07.log)

Already tried to troubleshoot with "iobroker upload javascript" but it didnt fixed the problem. 
I am kinda of a newbie and I would be really glad for help.
Kind Regards
Philip

**Comment by PhilipDiePython** [comment]
Neuestes jscontroller update konnte das Problem lösen!
