### ISSUE TITLE
instance crashes after updating js-controller

### ISSUE THREAD

**Issue by dercaptainbc** [ioBroker/ioBroker.javascript#539]
My javascript instance crashes everytime after getting the following error : 

`TypeError: Cannot read property 'time' of undefined` 

The root of the error is a missing value in a external json response, which happens from time to time. Nevertheless, this should not cause that the instance crashes

This happend after updating the js-controller to Version 3

Current Version of js-controller : 3.0.14
Current Version of javascript : 4.5.1

**Comment by AlCalzone** [comment]
Can you share more of the stack trace?

**Comment by GermanBluefox** [comment]
I tried to execute:
```
const a = null;

request('http://download.iobroker.net/list.html', (error, state, body) => {
    console.log(a.time);
});
```
and
```
const a = null;

setTimeout(() => {
    console.log(a.time);
});
```
and simple
```
const a = null;
console.log(a.time);
```

And no instance crash could be monitored...

**Comment by Apollon77** [comment]
really @GermanBluefox !? with 4.6.x? Can you show the full stack please?

**Comment by AlCalzone** [comment]
```

2020-05-16 13:21:56.348  - error: javascript.0 (1776) script.js.Skript_1: TypeError: Cannot read property 'time' of null
--
2020-05-16 13:21:56.348  - error: javascript.0 (1776)     at Request._callback (script.js.Skript_1:4:19)
2020-05-16 13:21:56.348  - error: javascript.0 (1776)     at Request.self.callback (C:\iobroker\node_modules\request\request.js:185:22)
2020-05-16 13:21:56.348  - error: javascript.0 (1776)     at Request.emit (events.js:310:20)
2020-05-16 13:21:56.348  - error: javascript.0 (1776)     at Request.EventEmitter.emit (domain.js:482:12)
2020-05-16 13:21:56.348  - error: javascript.0 (1776)     at Request. (C:\iobroker\node_modules\request\request.js:1154:10)
2020-05-16 13:21:56.349  - error: javascript.0 (1776)     at Request.emit (events.js:310:20)
2020-05-16 13:21:56.349  - error: javascript.0 (1776)     at Request.EventEmitter.emit (domain.js:482:12)
2020-05-16 13:21:56.349  - error: javascript.0 (1776)     at IncomingMessage. (C:\iobroker\node_modules\request\request.js:1076:12)
2020-05-16 13:21:56.349  - error: javascript.0 (1776)     at Object.onceWrapper (events.js:416:28)
2020-05-16 13:21:56.349  - error: javascript.0 (1776)     at IncomingMessage.emit (events.js:322:22)

```

**Comment by Apollon77** [comment]
Yes, but this is not "crasdh of adapter" ... thats only error logging of Javascript ... Sorry where is the crash? ;-)

**Comment by AlCalzone** [comment]
I can check later. 😅

**Comment by GermanBluefox** [comment]
I tried to fix it in the latest version (GitHub)

**Comment by Apollon77** [comment]
check Github 4.6.8 please, I also fixed one bug in error filtering

**Comment by AlCalzone** [comment]
Fixed on github:
![grafik](https://user-images.githubusercontent.com/17641229/82152174-cdc86980-985f-11ea-96a6-91602d697ce0.png)

The previous error was indeed a crash - I just didn't copy it.
