### ISSUE TITLE
Adapter latest installation 4.10.3 some chron jobs in my old scripts not working . In 4.9.8 is all ok

### ISSUE THREAD

**Issue by smartboart** [ioBroker/ioBroker.javascript#708]
Hello i have errors in some of my schedules after update from 4.9.8 to 4.10.13.
here is one example...

going back to 4.9.8 everything is fine again...

`
2020-11-09 13:05:50.953  - error: javascript.0 (13235)     at Scheduler.get (/opt/iobroker/node_modules/iobroker.javascript/lib/scheduler.js:373:42)
2020-11-09 13:05:50.953  - error: javascript.0 (13235)     at clearSchedule (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1357:35)
2020-11-09 13:05:50.954  - error: javascript.0 (13235)     at TimerMorgen (script.js.common.Rolladensteuerung.RolladenEG_GaesteWC:255:5)
2020-11-09 13:05:50.954  - error: javascript.0 (13235)     at script.js.common.Rolladensteuerung.RolladenEG_GaesteWC:303:1
2020-11-09 13:05:50.954  - error: javascript.0 (13235)     at script.js.common.Rolladensteuerung.RolladenEG_GaesteWC:436:3
2020-11-09 13:05:50.955  - error: javascript.0 (13235)     at Script.runInContext (vm.js:130:18)
2020-11-09 13:05:50.955  - error: javascript.0 (13235) script.js.common.Rolladensteuerung.RolladenEG_Couch: TypeError: Cannot read property 'type' of null
2020-11-09 13:05:50.956  - error: javascript.0 (13235)     at Scheduler.get (/opt/iobroker/node_modules/iobroker.javascript/lib/scheduler.js:373:42)
2020-11-09 13:05:50.956  - error: javascript.0 (13235)     at clearSchedule (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1357:35)
2020-11-09 13:05:50.956  - error: javascript.0 (13235)     at TimerMorgen (script.js.common.Rolladensteuerung.RolladenEG_Couch:206:5)
2020-11-09 13:05:50.956  - error: javascript.0 (13235)     at script.js.common.Rolladensteuerung.RolladenEG_Couch:254:1
2020-11-09 13:05:50.957  - error: javascript.0 (13235)     at script.js.common.Rolladensteuerung.RolladenEG_Couch:390:3
2020-11-09 13:05:50.957  - error: javascript.0 (13235)     at Script.runInContext (vm.js:130:18)

`

**Comment by GermanBluefox** [comment]
You are trying to clear `null` timer. But Ok it will be checked in next version

**Comment by smartboart** [comment]
Hi... Ja alle chron Jobs ist etwas überspitzt, aber ich benutze mehrere dieser null timer.Bzw.Mache ich das einleitend um sicher zustellen das der schedule gecleared ist bevor ich neu schreibe... Eingabe über Vis... Wenn ein script Beispiel benötigt wird, stelle ich es gerne ein.. . Die Meldung betrifft auch das aws Script / Anwesenbeitssimulation.. . Danke fuer die Annahme des Problems...

**Comment by smartboart** [comment]
Hi, das ging ja fix..Update auf 4.10.4 hat meine Fehler oben wohl behoben..
Ich habe jetzt noch folgende Fehler im log:

`

javascript.0 | 2020-11-10 07:56:39.681 | error | (29638)     at Script.runInContext (vm.js:130:18)
-- | -- | -- | --
javascript.0 | 2020-11-10 07:56:39.681 | error | (29638)     at script.js.common.Anwesenheit.Anwesenheitssimulation.AWS.AWS:724:3
javascript.0 | 2020-11-10 07:56:39.680 | error | (29638)     at script.js.common.Anwesenheit.Anwesenheitssimulation.AWS.AWS:254:1
javascript.0 | 2020-11-10 07:56:39.679 | error | (29638)     at schedule (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1296:36)
javascript.0 | 2020-11-10 07:56:39.678 | error | (29638) script.js.common.Anwesenheit.Anwesenheitssimulation.AWS.AWS: TypeError: Cannot set property '_ioBroker' of null

`

**Comment by oke24** [comment]
Bei mir treten nach Update der Javascript-Version auf  4.10.5 ebenfalls Probleme mit der schedule- Funktion auf.

Ich habe wie @smartboard das Script "Anwesenheitssimulation" in Produktion. Die Meldung bei mir lautet:

`javascript.0 | 2020-11-15 18:32:24.551 | error | (22704) script.js.common.SmartHome.Anwesenheitssimulation: schedule("*/0 * * * *"): cannot create schedule
`
Der Fehler tritt scheinbar beim Parsen des cron-Strings auf.

In einem anderen Script trat  der Fehler wie bei @smartboart als 
`TypeError: Cannot set property '_ioBroker' of null`
auf. Ich habe daraufhin die zweite Syntax-Option des cron-Strings "{hour: 24, minute: 0}" genutzt. 
Der TypeError ist damit verschwunden, ich erhalte hier aber nun einen anderen Fehler:

`javascript.0 | 2020-11-15 18:32:25.268 | error | (22704) Cannot parse schedule: {hour: 24, minute: 0}
`

**Comment by winnyschuster** [comment]
> schedule("*/0 * * * *")

/ gibt eine Schrittweite an und kann somit nicht 0 sein, korrekt wäre `0 * * * *`

> {hour: 24, minute: 0} 

Stunden können Werte zwischen 0 und 23 haben, also `{hour:0,minute:0}`

[mehr dazu](https://de.wikipedia.org/wiki/Cron)

**Comment by oke24** [comment]
Vielen Dank @winnyschuster für den Hinweis ! 
Der Fehler tritt aber auch bei anderen Zeitangaben auf, z.B. 

`javascript.0 | 2020-11-15 21:05:56.759 | error | (22704) Cannot parse schedule: {hour: 2, minute: 5}`

oder

`javascript.0 | 2020-11-15 21:05:56.763 | error | (22704) Cannot parse schedule: {hour: 21, minute: 5}`

Hinzufügen möchte ich gerne, dass die Scripte wie bei @smartboart vor dem Update des Javascript-Adapter über viele Monate fehlerfrei funktionierten.

**Comment by smartboart** [comment]
Mit 4.10.5 laufen bei mir noch ganz andere scripte wieder nicht, welche mit 4.10.4 noch liefen. werde erst mal mit 4.9.8 weiter vorlieb nehmen.

**Comment by oke24** [comment]
Ich konnte das Problem einkreisen und einen Workaround finden.
Der "Cannot parse schedule: {hour: 2, minute: 5}" - Fehler tritt auf wenn der schedule-string als var übergeben wird, also z.B.

```
var AufZeitAus4 = "{hour: " + idTimerStundeAus4 + ", minute: " + idTimerMinuteAus4 + "}";
TimerOnAus4 = schedule(AufZeitAus4, function(){

```

Mit der Formulierung
`TimerOnAus4 = schedule({hour:idTimerStundeAus4,minute:idTimerMinuteAus4}, function(){ `
wird der schedule-String fehlerfrei übernommen.

**Comment by winnyschuster** [comment]
Das ist ja kein Wunder, schedule() erwartet da ein `Objekt`, mit "{hour: " blabla.... erzeugst du aber einen `String`. Der Fehler sitzt hier **vor** dem Computer...
