### ISSUE TITLE
Fehler: event.enumNames.indexOf is not a function, seit Version 3.4.1

### ISSUE THREAD

**Issue by peoples2** [ioBroker/ioBroker.javascript#81]
Bezugnehmend auf diesen Forumthread: [http://forum.iobroker.net/viewtopic.php?f=22&t=10843](url)

Hier wie gewünscht ein neuer issue. Ich habe den Fehler dass mir der Log nach dem Update auf eine Version höher der 3.4.0 lauter Fehler im Log produziert. Für jeden "Datenpunkt/Gerät"

Hier ein Auszug:
`
2018-02-05 22:20:52.078  - [31merror[39m: javascript.0 message system.adapter.simple-api.0.memRss [object Object] event.enumNames.indexOf is not a function
2018-02-05 22:20:52.079  - [31merror[39m: javascript.0 TypeError: event.enumNames.indexOf is not a function
    at Array.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/lib/patternCompareFunctions.js:342:60)
    at patternMatching (/opt/iobroker/node_modules/iobroker.javascript/javascript.js:3283:36)
    at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/javascript.js:386:28)
    at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3190:37)
    at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
    at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
    at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
    at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
    at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
    at Manager.ondata (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:322:16)
    at Socket.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/opt/iobroker/node_modules/engine.io-client/node_modules/component-emitter/index.js:133:20)
    at Socket.onPacket (/opt/iobroker/node_modules/engine.io-client/lib/socket.js:451:14)
    at WS.<anonymous> (/opt/iobroker/node_modules/engine.io-client/lib/socket.js:268:10)
    at WS.Emitter.emit (/opt/iobroker/node_modules/engine.io-client/node_modules/component-emitter/index.js:133:20)
    at WS.Transport.onPacket (/opt/iobroker/node_modules/engine.io-client/lib/transport.js:145:8)
    at WS.Transport.onData (/opt/iobroker/node_modules/engine.io-client/lib/transport.js:137:8)
    at WebSocket.ws.onmessage (/opt/iobroker/node_modules/engine.io-client/lib/transports/websocket.js:146:10)
    at WebSocket.onMessage (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:841:10)
    at /opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:371:5)
    at /opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
`
.................... usw..............................
`
    2018-02-05 22:21:31.889  - [31merror[39m: javascript.0 message system.adapter.hm-rega.0.alive [object Object] event.enumNames.indexOf is not a function
2018-02-05 22:21:31.890  - [31merror[39m: javascript.0 TypeError: event.enumNames.indexOf is not a function
    at Array.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/lib/patternCompareFunctions.js:342:60)
    at patternMatching (/opt/iobroker/node_modules/iobroker.javascript/javascript.js:3283:36)
    at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/javascript.js:386:28)
    at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3190:37)
    at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
    at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
    at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
    at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
    at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
    at Manager.ondata (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:322:16)
    at Socket.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/opt/iobroker/node_modules/engine.io-client/node_modules/component-emitter/index.js:133:20)
    at Socket.onPacket (/opt/iobroker/node_modules/engine.io-client/lib/socket.js:451:14)
    at WS.<anonymous> (/opt/iobroker/node_modules/engine.io-client/lib/socket.js:268:10)
    at WS.Emitter.emit (/opt/iobroker/node_modules/engine.io-client/node_modules/component-emitter/index.js:133:20)
    at WS.Transport.onPacket (/opt/iobroker/node_modules/engine.io-client/lib/transport.js:145:8)
    at WS.Transport.onData (/opt/iobroker/node_modules/engine.io-client/lib/transport.js:137:8)
    at WebSocket.ws.onmessage (/opt/iobroker/node_modules/engine.io-client/lib/transports/websocket.js:146:10)
    at WebSocket.onMessage (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:841:10)
    at /opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:371:5)
    at /opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
`
............................ usw. ...............................  
`    
    2018-02-05 22:21:53.444  - [31merror[39m: javascript.0 message hm-rpc.0.OEQxxxxxxxx.4.VALVE_STATE [object Object] enumIds.indexOf is not a function
2018-02-05 22:21:53.445  - [31merror[39m: javascript.0 TypeError: enumIds.indexOf is not a function
    at getObjectEnumsSync (/opt/iobroker/node_modules/iobroker.javascript/javascript.js:3409:29)
    at getObjectEnumsSync (/opt/iobroker/node_modules/iobroker.javascript/javascript.js:3419:28)
    at EventObj.get (/opt/iobroker/node_modules/iobroker.javascript/javascript.js:186:17)
    at Array.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/lib/patternCompareFunctions.js:342:30)
    at patternMatching (/opt/iobroker/node_modules/iobroker.javascript/javascript.js:3283:36)
    at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/javascript.js:386:28)
    at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3190:37)
    at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
    at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
    at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
    at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
    at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
    at Manager.ondata (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:322:16)
    at Socket.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/opt/iobroker/node_modules/engine.io-client/node_modules/component-emitter/index.js:133:20)
    at Socket.onPacket (/opt/iobroker/node_modules/engine.io-client/lib/socket.js:451:14)
    at WS.<anonymous> (/opt/iobroker/node_modules/engine.io-client/lib/socket.js:268:10)
    at WS.Emitter.emit (/opt/iobroker/node_modules/engine.io-client/node_modules/component-emitter/index.js:133:20)
    at WS.Transport.onPacket (/opt/iobroker/node_modules/engine.io-client/lib/transport.js:145:8)
    at WS.Transport.onData (/opt/iobroker/node_modules/engine.io-client/lib/transport.js:137:8)
    at WebSocket.ws.onmessage (/opt/iobroker/node_modules/engine.io-client/lib/transports/websocket.js:146:10)
    at WebSocket.onMessage (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:841:10)
    at /opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:371:5)
    at /opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/opt/iobroker/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
`

Gruß
Peoples

**Comment by peoples2** [comment]
Fehlerursache gefunden!
Folgender Scriptteil eines Javascripts war verantwortlich:
`on({enumName:'weckerdatenpunkte', change: "ne"}, function (obj) {
    WeckerStellen();
});`
Danke für die Hilfe!
