### ISSUE TITLE
Axios Script nach Update fehlerhaft

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.javascript#944]
Habe gerade ein Update vom JavaScript Adapter gemacht von 5.2.16 oder 5.2.18 auf 5.2.21

Seit dem laufen meine Scripte mit Axios abfragen nicht mehr.

Logausgabe: 
`

javascript.0 | 2022-01-19 20:42:37.778 | error | at Script.runInContext (vm.js:130:18)
-- | -- | -- | --
javascript.0 | 2022-01-19 20:42:37.778 | error | at script.js.Serverraum.CCU-Firmware:288:3
javascript.0 | 2022-01-19 20:42:37.778 | error | at script.js.Serverraum.CCU-Firmware:286:5
javascript.0 | 2022-01-19 20:42:37.777 | error | at func_Version (script.js.Serverraum.CCU-Firmware:133:5)
javascript.0 | 2022-01-19 20:42:37.777 | error | at wrap (/opt/iobroker/node_modules/iobroker.javascript/node_modules/axios/lib/helpers/bind.js:9:15)
javascript.0 | 2022-01-19 20:42:37.776 | error | at Axios.request (/opt/iobroker/node_modules/iobroker.javascript/node_modules/axios/lib/core/Axios.js:40:11)
javascript.0 | 2022-01-19 20:42:37.776 | error | script.js.Serverraum.CCU-Firmware: Error: Provided config url is not valid

`

Hier das Script:

Läuft schon sehr lange ohne Fehler.

```
const logging = true; 
const debugging = false; 
const debugging_response = false;       //nur im Fehlerfall auf true. Hiermit wird die Antwort der Internetadresse protokolliert
let Serial = 'NEQ7777777'               //der eigenen CCU eintragen (nur relevant für ccu2 und 3)
let CCU_Version = 2;                  //Hier eine Zahl eintragen: 2 = CCU2 // 3 = CCU3 // 4 = Rasperrymatic // 5= pivccu2 lastest 
//= 6 pivccu3 latest // 7 = debimatic = latest bzw 51, 61 bzw 71 für die jeweilige Testing Version
//Datenpunkt auswählen wo die installierte Version ersichtlich ist (aus Homematic.Rega Adapter)
const id_Version_installiert = "hm-rega.0.MEQ0228930.0.FIRMWARE_VERSION"/*hm-rega.0.MEQ0228930.0.FIRMWARE_VERSION*/;
//Datenpunkt muss manuell angelegt werden. Kann irgendwo angelegt werden. Anschließend hier ersetzen
const id_Version_Internet = '0_userdata.0.Serverraum.CCU.Verfuegbare_CCU-Firmware'/*Verfuegbare CCU-Firmware*/;

const observation = true;         //Dauerhafte Überwachung der Firmware (true = aktiv // false =inaktiv)
const onetime = true;             //Prüft beim Scriptstart auf aktuelle Firmware

//Prio für Pushover
const prio_Firmware = 0;

//Variablen für Pushover
const sendpush = true;            //true = verschickt per Pushover Nachrchten // false = Pushover wird nicht benutzt
const pushover_Instanz0 =  'pushover.0';     // Pushover instance für Pio = 0
const pushover_Instanz1 =  'pushover.1';     // Pushover instance für Pio = 1
const pushover_Instanz2 =  'pushover.2';     // Pushover instance für Pio = 2
const pushover_Instanz3 =  'pushover.3';     // Pushover instance für Pio = -1 oder -2
let _prio;
let _titel;
let _message;
const _device = 'TPhone';         //Welches Gerät soll die Nachricht bekommen
//const _device = 'All'; 

//Variablen für Telegram
const sendtelegram = false;            //true = verschickt per Telegram Nachrchten // false = Telegram wird nicht benutzt
const user_telegram = '';             //User der die Nachricht bekommen soll

//Variable zum verschicken der Servicemeldungen per eMail
const sendmail = false;            //true = verschickt per email Nachrchten // false = email wird nicht benutzt

// **************************** ab hier keine Änderung *********************************************************
let _message_tmp;
const request = require('request');

function send_pushover_V4 (_device, _message, _titel, _prio) {
        let pushover_Instanz;
        if (_prio === 0){pushover_Instanz =  pushover_Instanz0}
        else if (_prio == 1){pushover_Instanz =  pushover_Instanz1}
        else if (_prio == 2){pushover_Instanz =  pushover_Instanz2}
        else {pushover_Instanz =  pushover_Instanz3}
        sendTo(pushover_Instanz, { 
        device: _device,
        message: _message, 
        title: _titel, 
        priority: _prio,
        retry: 60,
        expire: 600,
        html: 1
    }); 
}

function send_telegram (_message, user_telegram) {
    sendTo('telegram.0', { 
        text: _message,
        user: user_telegram,
        parse_mode: 'HTML'
    }); 
}

function send_mail (_message) {
    sendTo("email", {
        //from:    "iobroker@mydomain.com",
        //to:      "aabbcc@gmail.com",
        subject: "Servicemeldung",
        text:    _message
    });
}


function func_Version(){
    //const ccu2 = 'http://update.homematic.com/firmware/download?cmd=js_check_version&version=12345&product=HM-CCU2&serial=12345';
    const ccu2 = 'https://update.homematic.com/firmware/download?cmd=js_check_version&version=2.22.22&product=HM-CCU2&serial=NEQ7777777';
    const ccu3 = 'http://update.homematic.com/firmware/download?cmd=js_check_version&version=3.22.22&product=HM-CCU3&serial=NEQ7777777';
    const Raspi = 'https://raspberrymatic.de/LATEST-VERSION.js';
    const pivccu2 = 'https://www.pivccu.de/pivccu.latestVersion?serial=ioBroker';
    const pivccu3 = 'https://www.pivccu.de/pivccu3.latestVersion?serial=ioBroker';
    const debimatic = 'https://www.debmatic.de/latestVersion?serial=ioBroker';
    const testing_pivccu = 'https://www.pivccu.de/pivccu.latestVersion?serial=ioBroker';
    const testing_pivccu3 = 'https://www.pivccu.de/pivccu3.latestVersion?serial=ioBroker';
    const testing_debimatic = 'https://www.debmatic.de/latestVersion?serial=ioBroker';
        
    let ccu;
    if(CCU_Version == 3){ccu = ccu3;}
    else if(CCU_Version == 4){ccu = Raspi;}
    else if(CCU_Version == 5){ccu = pivccu2;}
    else if(CCU_Version == 6){ccu = pivccu3;}
    else if(CCU_Version == 7){ccu = debimatic;}
    else if(CCU_Version == 51){ccu = testing_pivccu;}
    else if(CCU_Version == 61){ccu = testing_pivccu3;}
    else if(CCU_Version == 71){ccu = testing_debimatic;}
    else {ccu = ccu2;}
    let url = ccu;



    const axios = require('axios');
    axios({
        method: 'get',
        baseURL: url,
        timeout: 4500,
         responseType: 'json'
     })
     .then((response) => {
                           
        if(debugging){
            console.log('data:' +response.data);
            console.log('Status: ' +response.status);
            console.log('Header:' +response.headers);
        }
        if(response.status = 200){
            //Umwandeln in String
            var data_string = JSON.stringify(response.data)
            //1. Split
            //var data_split= data_string.split("{");
            //Unnötige Sachen entfernen
            //var data_replace = data_split[2].replace(/}|,|]|:/gi,'');
            //mit 2. Split zum Ergebnis
            //var data_final = data_replace.split('"');
            //Ergebnisse
            //var _Status = parseInt(data_final[2],10);
            //var _Helligkeit = parseInt(data_final[4],10);
            //var _Temperatur = parseInt(data_final[6],10);
           

            const Version_Internet = getState(id_Version_Internet).val;
            const Version_installiert = (getState(id_Version_installiert).val).trim();
            //log('[DEBUG] ' +'Typ body: ' +typeof body);
            
            const Version = data_string.split("'");
            //log('[DEBUG] ' +'Typ Version: ' +typeof Version);
            //Fehler finden
            if(debugging){
                log('[DEBUG] ' +'Typ body: ' +typeof data_string);
                log('[DEBUG] ' +'Typ Version: ' +typeof Version);
                log('[DEBUG] ' +'Typ Version1: ' +typeof Version[1]);
                log('[DEBUG] ' +'Typ Version2: ' +typeof Version[2]);
                log('[DEBUG] ' +'Typ Version3: ' +typeof Version[3]);
            }
            
            
            
                if(debugging){
                    log('[DEBUG] ' +'Version installiert: '+Version_installiert);
                    log('[DEBUG] ' +'Version Internet: '+Version_Internet);
                    log('[DEBUG] ' +'Version aus URL: '+Version[1]);
                    log('[DEBUG] ' +'Name aus URL für Version: '+Version[3]);
                }
                if(typeof Version[1] !='undefined' || Version[1] != undefined){
                    if(Version_Internet === ''){
                        if(logging){
                            log('ausgewähltes Objekt leer. Firmware wird erstmalig gesetzt. Firmware: '+Version[1] +' Zentrale: ' +Version[3]);
                        }
                        setState(id_Version_Internet,Version[1]);
                    }
                
                    if(Version_installiert == Version[1]){
                        if(logging){
                            log('Installierte Firmware '+Version_installiert  +' der CCU ('+Version[3]  +') ist aktuell.');
                        }
                    }
                    else{
                        if(!isNaN(parseInt(Version[1].substr(0,1)))){
                            if(logging){
                                log('Installierte Firmware '+Version_installiert  +' der CCU ('+Version[3]  +') ist nicht aktuell. Aktuell verfügbare Version: '+Version[1]);
                            }
                        }
                    
                        if(Version_Internet == Version[1]){
                            if(debugging){
                                log('[DEBUG] ' +'Version Internet hat sich nicht verändert');
                            }
                        } else {
                            if(debugging){
                                log('[DEBUG] ' +'Installierte Firmware der CCU ist nicht aktuell.');
                            }
                            if(isNaN(parseInt(Version[1].substr(0,1)))){
                                if(logging){
                                    log('Version im Internet konnte nicht ermittelt werden');    
                                }
                            }
                            else{
                                setState(id_Version_Internet,Version[1]);
                            
                                _message_tmp = 'Installierte Firmware der CCU ('+Version[3]  +') ist nicht aktuell. Installiert: ' +Version_installiert +' --- Verfügbare Version: '+Version[1];
                        
                                //Push verschicken
                                if(sendpush){
                                    _prio = prio_Firmware;
                                    _titel = 'CCU-Firmware';
                                    _message = _message_tmp;
                                    send_pushover_V4(_device, _message, _titel, _prio);
                                }
                                if(sendtelegram){
                                    _message = _message_tmp;
                                    send_telegram(_message, user_telegram);
                                }
                                if(sendmail){
                                    _message = _message_tmp;
                                    send_mail(_message);
                                }
                            }
                        }         
                    }
                }
                else{
                    if(logging){
                        log('Version im Internet kann zur Zeit nicht abgefragt werden.');
                    }
                }
        
                if(debugging_response){
                    log('body: ' + data_string);
                    log('Länge ' + Version.length + ' --- Version: ' + Version[1]);
                    log('response: ' + JSON.stringify(response));
                }
            
        

                     

            
            
        }
        else{
            if(logging){
                log('Hier stimmt etwas nicht. Meldung: '+response.status)
            }
        } 

                            

    })
    .catch(
        (error) => {
            // handle error
            log('Fehler bei der Abfrage der Firmware: '+error,'warn');                    
        }
    );

}


if(observation){
    //Nachts einmalig ausführen 00:30 Schaltzeiten berechnen
    schedule("54 05 * * *", func_Version);
}

if(onetime){
    //beim Starten
    func_Version();
}
```

**Comment by Apollon77** [comment]
There should be no reason that a javascript update can cause this. Also google on this is not giving anything in return.

can you tell which codeplace is referenced in the error message? I can not map it to your script.

Are you sure thatyou not try to set "ccu2"? WHich is commented out and so not defined ad so you would give an empty url into axios ... and in my eyes this happens

CCU_Version = 2  ... this is ending in the case that url = undefined

**Comment by Apollon77** [comment]
According to Axios code this happens when no url is set in config https://github.com/axios/axios/blob/master/lib/core/Axios.js#L39 ... maybe with the update also Axios was updated and so there is an issue with your request... please fix your code

**Comment by Apollon77** [comment]
PS: Yes this seems to have happened https://github.com/axios/axios/releases/tag/v0.25.0 ...

> Adding error handling when missing url (#3791)

https://github.com/axios/axios/issues/1765
