### ISSUE TITLE
CreateStateAsync generiert Fehlermeldungen innerhalb einer Schleife

### ISSUE THREAD

**Issue by peoples0815** [ioBroker/ioBroker.javascript#955]
Beim Versuch innerhalb einer Schleife mit CreateStateAsync Datenpunkte zu erstellen, wird immer beim ersten Durchlauf Fehler ausgegeben unabhängig was als erster Datenpunkt erstellt werden soll.

Entfernt man das Async oder kommentiert es aus, werden die Datenpunkte erstellt.

**Link zum Beitrag:**
[https://forum.iobroker.net/topic/52375/createstateasync-erzeugt-fehlermeldung?_=1644574543996](url)
Hier wurde gebeten ein Issue zu eröffnen

**Script**
```
var instanz = '0_userdata.0'; instanz = instanz +'.';
var pfad0 = 'DeviceSwitchingTimers'; pfad0 = pfad0 +'.';


const devices = [
                    /*Device ID */                                                /*Device Name für Datenpunkt */                       /*Device Typ (state / level) */                            
    /*Doppelfenster Küche - Steckdose rechts - rechts*/
    {'deviceID':'shelly.0.xxxxxxx',                                 'deviceName':'Steckdose_Kueche_Doppelfenster_rechts-rechts',            'deviceType':'state'},                
    /*Doppelfenster Küche rechts - Steckdose rechts - links*/
    {'deviceID':'shelly.0.xxxxxxx',                                 'deviceName':'Steckdose_Kueche_Doppelfenster_rechts-links',             'deviceType':'state'},
    /*Doppelfenster Küche - Steckdose links - rechts*/
    {'deviceID':'hm-rpc.0.xxxxxxx',                                 'deviceName':'Steckdose_Kueche_Doppelfenster_links-rechts',             'deviceType':'state'},
    /*Doppelfenster Küche - Steckdose links - links*/
    {'deviceID':'hm-rpc.0.xxxxxxx',                                 'deviceName':'Steckdose_Kueche_Doppelfenster_links-links',              'deviceType':'state'}
];
async function createDeviceStates(){
    try {

        for(var i = 0; i < Object.keys(devices).length; i++) { 
            await createStateAsync(instanz + pfad0 + devices[i].deviceName +  '.switchingAutomatic', {name: 'Automatisches Schalten', type:'boolean', def:false, read:true, write:true});
            await createStateAsync(instanz + pfad0 + devices[i].deviceName +  '.onTime1', {name: 'Einschaltzeit 1', type:'string', def:'00:00', read:true, write:true});
            await createStateAsync(instanz + pfad0 + devices[i].deviceName +  '.onTime2', {name: 'Einschaltzeit 2', type:'string', def:'00:00' , read:true, write:true});
            await createStateAsync(instanz + pfad0 + devices[i].deviceName +  '.offTime1', {name: 'Ausschaltzeit 1', type:'string', def:'23:59' , read:true, write:true});
            await createStateAsync(instanz + pfad0 + devices[i].deviceName +  '.offTime2', {name: 'Ausschaltzeit 2', type:'string', def:'23:59' , read:true, write:true});
            await createStateAsync(instanz + pfad0 + devices[i].deviceName +  '.reactOnSleepingMode', {name: 'Einschaltzeit 1', type:'boolean', def:false , read:true, write:true});

            // Unterscheidung Typen (state / level)
            switch(devices[i].deviceType){ 
                case 'state': // Gerätetyp State
                    await createStateAsync(instanz + pfad0 + devices[i].deviceName +  '.stateSleepingModeOn', {name: 'Gerätestatus bei Schlafmodus ein', type:'boolean', def:false , read:true, write:true});
                    await createStateAsync(instanz + pfad0 + devices[i].deviceName +  '.stateSleepingModeOff', {name: 'Gerätestatus bei Schlafmodus aus', type:'boolean', def:true , read:true, write:true});
                break;
                case 'level': // Gerätetyp Level
                    await createStateAsync(instanz + pfad0 + devices[i].deviceName +  '.levelSleepingModeOn', {name: 'Gerätelevel bei Schlafmodus ein', type:'number', def:0 , read:true, write:true});
                    await createStateAsync(instanz + pfad0 + devices[i].deviceName +  '.levelSleepingModeOff', {name: 'Gerätelevel bei Schlafmodus aus', type:'number', def:100 , read:true, write:true});               
                break;
            }   
        }
    } catch (error) {
        log(`Unexpected error - ${error}`, 'error');
    }
}

createDeviceStates();
```

**Schritte um Fehler nachzustellen**
Einfach Script in Iobroker anlegen und ausführen 

**Fehlermeldung im Log**  
```
2022-02-10 14:23:27.808 - warn: javascript.0 (694436) State "0_userdata.0.DeviceSwitchingTimers.Steckdose_Kueche_Doppelfenster_links-rechts.switchingAutomatic" not found
2022-02-10 14:23:27.808 - warn: javascript.0 (694436) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1967:33)
2022-02-10 14:23:27.808 - warn: javascript.0 (694436) at processImmediate (internal/timers.js:466:21)
2022-02-10 14:23:27.808 - error: javascript.0 (694436) script.js.Wandtablet.Schaltuhr: Unexpected error - Error: State "0_userdata.0.DeviceSwitchingTimers.Steckdose_Kueche_Doppelfenster_links-rechts.switchingAutomatic" not found
```

**Versions:**  
 - Js-Adapter version: 5.2.13
 - JS-Controller version: 3.3.22
 - Node version: 14.18.2
 - Operating system: debian

**Comment by ticaki** [comment]
Kann das obrige Fehlverhalten bestätigen, jedoch ist es scheinbar abhängig von der Installation, bei einem Skript das ich mit Leuten teile hab ich nicht den Fehler jedoch einer der Nutzer

```
115229	2022-02-09 19:53:41.231	error	script.js.Wetter.DWD-UWZ: info: error in .data create Error: State "javascript.0.Wetterwarnung.data.nina.51#xxxx/6#xxxx.warning1.certainty" not found
```

**Comment by Nashra-ioB** [comment]
Und der bin ich, wie schon geschrieben kommt dies beim ersten Start des Skripts von ticaki

- Js-Adapter: 5.2.13
- Js-Controller: 3.3.22
- Node: 14.18.2
- System: debian
