### ISSUE TITLE
 Error in callback: TypeError: Cannot read property 'call' of undefined at Immediate._onImmediate

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.javascript#973]
**Describe the bug**  
Update javascript adapter to version 5.3.0 After restart of the instance the error in the log is available

**To Reproduce**  
1. Update javascript to 5.3.0
2. restart instance

**Expected behavior**  
No error in the log :-)

**Versions:**  
 - Adapter version: 5.3.0
 - JS-Controller version: 4.0.15
 - Node version: v14.19.0

**Additional context**  
Log

```
2022-03-03 21:11:04.532 - info: javascript.0 (9468) script.js.Skripte.Lueftungsanlage.Lueftung_Aussentemperatur: registered 1 subscription and 1 schedule
2022-03-03 21:11:04.534 - info: javascript.0 (9468) Start javascript script.js.Skripte.Lueftungsanlage.Lueftung
2022-03-03 21:11:04.543 - info: javascript.0 (9468) script.js.Skripte.Lueftungsanlage.Lueftung: Starting lueftung.js V1.0.0
2022-03-03 21:11:04.563 - info: javascript.0 (9468) script.js.Skripte.Lueftungsanlage.Lueftung: registered 2 subscriptions and 3 schedules
2022-03-03 21:11:04.564 - info: javascript.0 (9468) Start javascript script.js.Skripte.Homematic.Fenster_Status
2022-03-03 21:11:04.572 - info: javascript.0 (9468) script.js.Skripte.Homematic.Fenster_Status: registered 1 subscription and 0 schedules
2022-03-03 21:11:04.574 - info: javascript.0 (9468) Start javascript script.js.Skripte.mqtt.mqtt_iobdaten_bereitstellen
2022-03-03 21:11:04.583 - info: javascript.0 (9468) script.js.Skripte.mqtt.mqtt_iobdaten_bereitstellen: registered 8 subscriptions and 0 schedules
2022-03-03 21:11:04.590 - info: javascript.0 (9468) script.js.Skripte.Homematic.Homematic_Servicemeldungen: Es werden: 96 Datenpunkte überwacht. Derzeit: 2 Servicemeldung(en).
2022-03-03 21:11:04.593 - warn: javascript.0 (9468) script.js.Blockly.Rasenmaeher: Aktuelle Systemzeit: 21:11:04
2022-03-03 21:11:05.342 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.344 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.345 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.351 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.352 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.354 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.359 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.360 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.362 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.517 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.520 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.522 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.528 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.530 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.532 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.537 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.538 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.540 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.545 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.546 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.547 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.552 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.554 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.555 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.560 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.562 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.563 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.568 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.570 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.571 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.576 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.577 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.579 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.584 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.585 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.586 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.591 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.593 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.594 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.599 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.600 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.601 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.606 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.608 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.609 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.613 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.615 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.616 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.620 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.622 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.623 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.628 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.629 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.631 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.636 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.637 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.639 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.644 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.645 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.646 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)
2022-03-03 21:11:05.655 - error: javascript.0 (9468) Error in callback: TypeError: Cannot read property 'call' of undefined
2022-03-03 21:11:05.657 - error: javascript.0 (9468) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:3056:34)
2022-03-03 21:11:05.658 - error: javascript.0 (9468) at processImmediate (internal/timers.js:466:21)

```

**Comment by Apollon77** [comment]
5.3.1 o its way soon
